import { HatchSourceRelations } from './Entities/HatchSourceRelations.js';
import { RegisterDatabaseModel } from '../runtime/DatabaseModel.js';
// Copyright (c) Daniel Carvajal and netDxf contributors. MIT License; see package LICENSE.
import * as api from '../index.js';
import { DxfObject } from './DxfObject.js';
import { HeaderVariables } from './Header/HeaderVariables.js';
import { ObservableDictionary } from './Collections/ObservableDictionary.js';
import { TableNameComparer } from './Collections/TableObjects.js';
import { SupportFolders } from './Collections/SupportFolders.js';
import { DrawingEntities } from './Collections/DrawingEntities.js';
import { ReferenceList } from '../runtime/ReferenceList.js';
import { BindResource, ChangeResource, Listen, Unlisten } from '../runtime/RegisteredTable.js';
import { InstallDocumentObjects } from './DxfDocument.Objects.js';
import { InstallDocumentMultiLeader } from './DxfDocument.MultiLeader.js';
import { InstallDocumentSection } from './DxfDocument.Section.js';
import { InstallDocumentMetadata, ObjectMetadataMembers } from './DxfDocument.MetadataReferences.js';
import { ArgumentException, ArgumentNullException, NotSupportedException, NullReferenceException } from '../runtime/Errors.js';
const transportPending=new Set(['ACAD_TABLE']);
const tables=[['VPorts','VPorts'],['Views','Views'],['ApplicationRegistries','ApplicationRegistries'],['Layers','Layers'],['Linetypes','Linetypes'],
  ['TextStyles','TextStyles'],['ShapeStyles','ShapeStyles'],['DimensionStyles','DimensionStyles'],['MlineStyles','MLineStyles'],['UCSs','UCSs'],
  ['Blocks','BlockRecords'],['ImageDefinitions','ImageDefinitions'],['UnderlayDgnDefinitions','UnderlayDgnDefinitions'],
  ['UnderlayDwfDefinitions','UnderlayDwfDefinitions'],['UnderlayPdfDefinitions','UnderlayPdfDefinitions'],['Groups','Groups'],['Layouts','Layouts']];
const simpleEntities=new Set(['ARC','CIRCLE','ELLIPSE','3DFACE','LINE','POINT','POLYLINE','LWPOLYLINE','SOLID','SPLINE','HELIX','TRACE','MESH','RAY','XLINE','WIPEOUT','HATCH','LIGHT','OLEFRAME','OLE2FRAME','BODY','REGION','3DSOLID']);
/** Typed in-memory authoring/registration core. Typed file IO and the database-backed
 * entity families are not implemented by this checkpoint; see DOCUMENT_OWNERSHIP.md.
 */
export class DxfDocument extends DxfObject {
  #variables; #handles=0n; #thumbnail=new Uint8Array(); #raster;
  Name=null; BuildDimensionBlocks=false; DimensionBlocksIndex=-1; GroupNamesIndex=0;
  constructor(value=new HeaderVariables(),folders=[]){
    super('DOCUMENT');
    if(typeof value==='number'){const variables=new HeaderVariables();variables.AcadVer=value;value=variables;}
    else if(value!==null&&!(value instanceof HeaderVariables)){folders=value;value=new HeaderVariables();}
    this.SupportFolders=new SupportFolders(folders);this.#variables=value;
    this.Comments=new ReferenceList(['DXF file generated by netDxf https://github.com/haplokuon/netDxf, Copyright(C) Daniel Carvajal, Licensed under MIT']);
    this.Classes=new api.DxfClassCollection();this.NumHandles=this.AssignHandle(0n);this.Entities=new DrawingEntities(this);
    this.AddedObjects=new ObservableDictionary(0,TableNameComparer,'string');
    this.AddedObjects.AddItem.Add((_,e)=>{for(const item of ObjectMetadataMembers(e.Item.Value))this.BindMetadataObject(item);});
    this.AddedObjects.RemoveItem.Add((_,e)=>{for(const item of ObjectMetadataMembers(e.Item.Value))this.UnbindMetadataObject(item);});
    this.AddedObjects.Add(this.Handle,this);
    for(const [property,name] of tables)this[property]=new api[name](this);
    this.Layers.Add(api.Layer.Default);
    this.Linetypes.Add(api.Linetype.ByLayer);this.Linetypes.Add(api.Linetype.ByBlock);this.Linetypes.Add(api.Linetype.Continuous);
    this.TextStyles.Add(api.TextStyle.Default);this.ApplicationRegistries.Add(api.ApplicationRegistry.Default);
    this.DimensionStyles.Add(api.DimensionStyle.Default);this.MlineStyles.Add(api.MLineStyle.Default);
    this.Layouts.Add(api.Layout.ModelSpace);this.RasterVariables=new api.RasterVariables(this);
    for(const key of ['SupportFolders','Comments','Classes','Entities']){const value=this[key];Object.defineProperty(this,key,{get:()=>value,enumerable:true,configurable:false});}
  }
  get DrawingVariables(){return this.#variables;}
  get NumHandles(){return this.#handles;}
  set NumHandles(value){if(this.#variables===null)throw new NullReferenceException();this.#variables.HandleSeed=BigInt.asUintN(64,value).toString(16).toUpperCase();this.#handles=value;}
  get ThumbnailImage(){return this.#thumbnail.slice();}
  set ThumbnailImage(value){if(value==null)throw new ArgumentNullException('value');this.#thumbnail=Uint8Array.from(value);}
  get Viewport(){return this.VPorts.get_Item('*Active');}
  get RasterVariables(){return this.#raster;}
  set RasterVariables(value){if(value==null)throw new ArgumentNullException('value');if(!value.Handle)this.NumHandles=value.AssignHandle(this.NumHandles);this.AddedObjects.Add(value.Handle,value);this.#raster=value;}
  GetObjectByHandle(handle){if(typeof handle!=='string'||handle.length===0||handle.length>16||!/^[0-9a-f]+$/i.test(handle))return null;
    const result={};return this.AddedObjects.TryGetValue(BigInt('0x'+handle).toString(16).toUpperCase(),result)?result.value:null;}
  ValidateStoredTableEntityAdoption(entity){
    if(entity==null)throw new ArgumentNullException('entity');
    if(entity instanceof api.MultiLeader)entity.ValidateIncoming(this);
    if(entity instanceof api.Section)entity.Validate(this);
    if(transportPending.has(entity.CodeName))
      throw new NotSupportedException('Database-backed entity adoption is not yet available: '+entity.CodeName);
    if(entity instanceof api.Insert)this.ValidateStoredTableBlockAdoption(entity.Block);
    else if(entity instanceof api.Dimension&&entity.Block!==null)this.ValidateStoredTableBlockAdoption(entity.Block);
    if(entity.StoredRecords?.Count>0)throw new NotSupportedException('Stored polyline record adoption is not yet available.');
    if(!simpleEntities.has(entity.CodeName)&&!['DIMENSION','ARC_DIMENSION','LEADER','TOLERANCE','INSERT','SHAPE','TEXT','MTEXT','IMAGE','MLINE','DGNUNDERLAY','DWFUNDERLAY','PDFUNDERLAY','VIEWPORT','MULTILEADER','SECTION','SECTIONOBJECT'].includes(entity.CodeName))
      throw new NotSupportedException('Unknown entity registration: '+entity.CodeName);
  }
  ValidateStoredTableBlockAdoption(root){
    const visited=new Set();
    const visit=block=>{
      if(block==null||visited.has(block)||this.Blocks.Contains(block.Name))return;
      visited.add(block);
      for(const entity of block.Entities){
        if(entity instanceof api.Hatch)HatchSourceRelations.ValidateOwner(entity,block,this);
        if(entity.StoredRecords?.Count>0)throw new NotSupportedException('Stored polyline record adoption is not yet available.');
        if(entity instanceof api.Section)entity.Validate(this);
        else if(transportPending.has(entity.CodeName))throw new NotSupportedException('Database-backed entity adoption is not yet available: '+entity.CodeName);
        else if(entity instanceof api.Insert)visit(entity.Block);
        else if(entity instanceof api.Dimension)visit(entity.Block);
      }
    };visit(root);
  }
  StoredTableReferencesRemoval(root){
    // The source's section-reference scan initializes the object database even
    // for an ordinary entity. Keep that observable allocation and inspect every
    // registered schema reference which can constrain the admitted objects.
    const removed=new Set(ObjectMetadataMembers(root));
    const block=root instanceof api.Block?root:root instanceof api.Layout?root.AssociatedBlock:null;
    if(block!==null){for(const member of ObjectMetadataMembers(block))removed.add(member);removed.add(block.Record);for(const item of [...block.Entities,...block.AttributeDefinitions.Values])for(const member of ObjectMetadataMembers(item))removed.add(member);}
    for(const item of removed)if(item instanceof api.Hatch)item.ValidateOpaqueSourceRelease();
    if(this.SectionReferencesRemoval(removed))return true;
    const database=this.Objects;
    for(const item of removed)if(api.SunReferences.Get(item)!==null)return true;
    for(const item of database.Items){
      if(removed.has(item))continue;
      if(['SECTION_SETTINGS','TABLECONTENT','TABLEGEOMETRY','CELLSTYLEMAP','SUNSTUDY','FIELD','DIMASSOC'].includes(item.CodeName)){
        if(Array.from(item.DatabaseReferences).some(target=>removed.has(target)))return true;
        const seen=new Set();for(let owner=item.Owner;owner!==null&&!seen.has(owner);owner=owner.Owner){if(removed.has(owner))return true;seen.add(owner);}
      }
    }
    return false;
  }
  #resource(entity,property,name,event,assignHandle){BindResource(this,entity,property,this[name],assignHandle);Listen(this,entity,event,(sender,e)=>ChangeResource(sender,e,this[name]));}
  #release(entity,property,name){if(entity[property]!==null)this[name].References.get_Item(entity[property].Name).Remove(entity);}
  #underlay(definition){return definition.Type===api.UnderlayType.DGN?this.UnderlayDgnDefinitions:definition.Type===api.UnderlayType.DWF?this.UnderlayDwfDefinitions:this.UnderlayPdfDefinitions;}
  #overrides(entity,assignHandle){
    const T=api.DimensionStyleOverrideType;
    for(const [type,name] of [[T.TextStyle,'TextStyles'],[T.LeaderArrow,'Blocks'],[T.DimArrow1,'Blocks'],[T.DimArrow2,'Blocks'],[T.DimLineLinetype,'Linetypes'],[T.ExtLine1Linetype,'Linetypes'],[T.ExtLine2Linetype,'Linetypes']]){
      const result={};if(!entity.StyleOverrides.TryGetValue(type,result)||result.value.Value===null)continue;
      const item=result.value,resource=item.Value;entity.StyleOverrides.set_Item(type,new api.DimensionStyleOverride(type,this[name].Add(resource,assignHandle)));
      this[name].References.get_Item(resource.Name).Add(entity);
    }
  }
  #overrideTable(type){const T=api.DimensionStyleOverrideType;return [T.DimLineLinetype,T.ExtLine1Linetype,T.ExtLine2Linetype].includes(type)?this.Linetypes:[T.LeaderArrow,T.DimArrow1,T.DimArrow2].includes(type)?this.Blocks:type===T.TextStyle?this.TextStyles:null;}
  #watchOverrides(entity){
    Listen(this,entity,'DimensionStyleOverrideAdded',(sender,e)=>{
      const table=this.#overrideTable(e.Item.Type);if(table===null||e.Item.Value===null)return;
      const resource=e.Item.Value;sender.StyleOverrides.set_Item(e.Item.Type,new api.DimensionStyleOverride(e.Item.Type,table.Add(resource)));
      table.References.get_Item(resource.Name).Add(sender);
    });
    Listen(this,entity,'DimensionStyleOverrideRemoved',(sender,e)=>{const table=this.#overrideTable(e.Item.Type);if(table!==null&&e.Item.Value!==null)table.References.get_Item(e.Item.Value.Name).Remove(sender);});
  }
  #removeOverrides(entity){for(const pair of entity.StyleOverrides){const item=pair instanceof api.DimensionStyleOverride?pair:pair.Value,table=this.#overrideTable(item.Type);if(table!==null&&item.Value!==null)table.References.get_Item(item.Value.Name).Remove(entity);}}
  #associatedAdded(sender,item){
    const layout=sender.Owner.Record.Layout;
    if(item.Owner!==null){if(item.Owner.Record.Layout!==layout)throw new ArgumentException('Associated entities must belong to the same layout and document.');}
    else this.Blocks.get_Item(layout.AssociatedBlock.Name).Entities.Add(item);
  }
  AddEntityToDocument(entity,assignHandle=true){
    this.ValidateStoredTableEntityAdoption(entity);
    if(assignHandle||!entity.Handle)this.NumHandles=entity.AssignHandle(this.NumHandles);
    const code=entity.CodeName;
    if(entity instanceof api.Dimension){
      BindResource(this,entity,'Style',this.DimensionStyles,assignHandle);this.#overrides(entity,assignHandle);
      if(this.BuildDimensionBlocks){let block=api.DimensionBlock.Build(entity,'DimBlock');block.SetName('*D'+ ++this.DimensionBlocksIndex,false);entity.Block=this.Blocks.Add(block);this.Blocks.References.get_Item(block.Name).Add(entity);}
      else if(entity.Block!==null){if(!this.Blocks.Contains(entity.Block)||!/^\*d/i.test(entity.Block.Name))entity.Block.SetName('*D'+ ++this.DimensionBlocksIndex,false);entity.Block=this.Blocks.Add(entity.Block);this.Blocks.References.get_Item(entity.Block.Name).Add(entity);}
      Listen(this,entity,'DimensionStyleChanged',(sender,e)=>ChangeResource(sender,e,this.DimensionStyles));
      Listen(this,entity,'DimensionBlockChanged',(sender,e)=>{
        if(e.OldValue!==null){this.Blocks.References.get_Item(e.OldValue.Name).Remove(sender);this.Blocks.Remove(e.OldValue);}
        if(e.NewValue!==null){if(!e.NewValue.Name.startsWith('*D'))e.NewValue.SetName('*D'+ ++this.DimensionBlocksIndex,false);e.NewValue=this.Blocks.Add(e.NewValue);this.Blocks.References.get_Item(e.NewValue.Name).Add(sender);}
      });this.#watchOverrides(entity);
    }else if(code==='LEADER'){
      this.#resource(entity,'Style','DimensionStyles','LeaderStyleChanged',assignHandle);this.#overrides(entity,assignHandle);this.#watchOverrides(entity);
      Listen(this,entity,'AnnotationAdded',(sender,e)=>this.#associatedAdded(sender,e.Item));Listen(this,entity,'AnnotationRemoved',(_,e)=>this.Entities.Remove(e.Item));
    }else if(code==='TOLERANCE')this.#resource(entity,'Style','DimensionStyles','ToleranceStyleChanged',assignHandle);
    else if(code==='INSERT'){
      BindResource(this,entity,'Block',this.Blocks,assignHandle);
      for(const attribute of entity.Attributes)this.#bindAttribute(attribute,assignHandle,false);
      Listen(this,entity,'AttributeAdded',(_,e)=>{this.BindMetadataObject(e.Item);this.NumHandles=e.Item.AssignHandle(this.NumHandles);this.#bindAttribute(e.Item,true,false);});
      Listen(this,entity,'AttributeRemoved',(_,e)=>{this.UnbindMetadataObject(e.Item);this.#unbindAttribute(e.Item);});
    }else if(code==='TEXT'||code==='MTEXT')this.#resource(entity,'Style','TextStyles','TextStyleChanged',assignHandle);
    else if(code==='SHAPE')this.#resource(entity,'Style','ShapeStyles','StyleChanged',assignHandle);
    else if(code==='MLINE')this.#resource(entity,'Style','MlineStyles','MLineStyleChanged',assignHandle);
    else if(code==='IMAGE'){
      BindResource(this,entity,'Definition',this.ImageDefinitions,assignHandle);
      Listen(this,entity,'ImageDefinitionChanged',(sender,e)=>{
        this.ImageDefinitions.References.get_Item(e.OldValue.Name).Remove(sender);e.NewValue=this.ImageDefinitions.Add(e.NewValue);
        this.ImageDefinitions.References.get_Item(e.OldValue.Name).Add(sender); // pinned source uses OldValue here
      });
    }else if(['DGNUNDERLAY','DWFUNDERLAY','PDFUNDERLAY'].includes(code)){
      const table=this.#underlay(entity.Definition);BindResource(this,entity,'Definition',table,assignHandle);
      Listen(this,entity,'UnderlayDefinitionChanged',(sender,e)=>{
        this.#underlay(e.OldValue).References.get_Item(e.OldValue.Name).Remove(sender);const next=this.#underlay(e.NewValue);
        e.NewValue=next.Add(e.NewValue);next.References.get_Item(e.NewValue.Name).Add(sender);
      });
    }else if(code==='VIEWPORT'){
      for(let i=0;i<entity.FrozenLayers.Count;i++)entity.FrozenLayers.set_Item(i,this.Layers.Add(entity.FrozenLayers.get_Item(i),assignHandle));
      Listen(this,entity,'ClippingBoundaryAdded',(sender,e)=>this.#associatedAdded(sender,e.Item));Listen(this,entity,'ClippingBoundaryRemoved',(_,e)=>this.Entities.Remove(e.Item));
    }
    if(entity instanceof api.PolyfaceMesh){for(const face of entity.Faces)if(face.Layer!==null){face.Layer=this.Layers.Add(face.Layer,assignHandle);this.Layers.References.get_Item(face.Layer.Name).Add(entity);}Listen(this,entity,'PolyfaceMeshFaceLayerChanged',(sender,e)=>ChangeResource(sender,e,this.Layers));}
    // HATCH is admitted below as a model with relationship-aware Block validation.
    if(entity instanceof api.Hatch){
      Listen(this,entity,'HatchBoundaryPathAdded',(sender,e)=>{HatchSourceRelations.ValidatePathOwner(sender,e.Item,sender.Owner);for(const item of e.Item.Entities)if(item.Owner===null)sender.Owner.Entities.Add(item);});
      Listen(this,entity,'HatchBoundaryPathRemoved',(sender,e)=>{for(const item of e.Item.Entities)sender.Owner.Entities.Remove(item);});
    }
    BindResource(this,entity,'Layer',this.Layers,assignHandle);BindResource(this,entity,'Linetype',this.Linetypes,assignHandle);
    this.AddedObjects.Add(entity.Handle,entity);
    Listen(this,entity,'LayerChanged',(sender,e)=>ChangeResource(sender,e,this.Layers));Listen(this,entity,'LinetypeChanged',(sender,e)=>ChangeResource(sender,e,this.Linetypes));
  }
  #bindAttribute(attribute,assignHandle,definition){
    if(definition){this.#resource(attribute,'Style','TextStyles','TextStyleChange',assignHandle);}
    this.#resource(attribute,'Layer','Layers','LayerChanged',assignHandle);this.#resource(attribute,'Linetype','Linetypes','LinetypeChanged',assignHandle);
    if(!definition)this.#resource(attribute,'Style','TextStyles','TextStyleChanged',assignHandle);
  }
  #unbindAttribute(attribute){this.#release(attribute,'Layer','Layers');this.#release(attribute,'Linetype','Linetypes');this.#release(attribute,'Style','TextStyles');Unlisten(this,attribute);}
  AddAttributeDefinitionToDocument(attribute,assignHandle=true){if(attribute==null)throw new ArgumentNullException('attDef');if(assignHandle||!attribute.Handle)this.NumHandles=attribute.AssignHandle(this.NumHandles);this.#bindAttribute(attribute,assignHandle,true);this.AddedObjects.Add(attribute.Handle,attribute);}
  RemoveAttributeDefinitionFromDocument(attribute){this.#unbindAttribute(attribute);this.AddedObjects.Remove(attribute.Handle);attribute.Handle=null;attribute.Owner=null;return true;}
  RemoveEntityFromDocument(entity){
    const code=entity.CodeName;
    if(entity instanceof api.Dimension){
      if(entity.Block!==null){this.Blocks.References.get_Item(entity.Block.Name).Remove(entity);entity.Block=null;}
      this.#release(entity,'Style','DimensionStyles');this.#removeOverrides(entity);
    }else if(code==='LEADER'){
      this.#release(entity,'Style','DimensionStyles');if(entity.Annotation!==null){entity.Annotation.RemoveReactor(entity);this.Entities.Remove(entity.Annotation);}this.#removeOverrides(entity);
    }else if(code==='TOLERANCE')this.#release(entity,'Style','DimensionStyles');
    else if(code==='INSERT'){this.#release(entity,'Block','Blocks');for(const attribute of entity.Attributes)this.#unbindAttribute(attribute);}
    else if(code==='TEXT'||code==='MTEXT')this.#release(entity,'Style','TextStyles');
    else if(code==='SHAPE')this.#release(entity,'Style','ShapeStyles');
    else if(code==='MLINE')this.#release(entity,'Style','MlineStyles');
    else if(code==='IMAGE')this.#release(entity,'Definition','ImageDefinitions');
    else if(['DGNUNDERLAY','DWFUNDERLAY','PDFUNDERLAY'].includes(code))this.#underlay(entity.Definition).References.get_Item(entity.Definition.Name).Remove(entity);
    else if(code==='VIEWPORT'&&entity.ClippingBoundary!==null){entity.ClippingBoundary.RemoveReactor(entity);this.Entities.Remove(entity.ClippingBoundary);}
    if(entity instanceof api.Hatch)entity.UnLinkBoundary();
    if(entity instanceof api.PolyfaceMesh)for(const face of entity.Faces)if(face.Layer!==null)this.Layers.References.get_Item(face.Layer.Name).Remove(entity);
    this.#release(entity,'Layer','Layers');this.#release(entity,'Linetype','Linetypes');this.AddedObjects.Remove(entity.Handle);Unlisten(this,entity);entity.Handle=null;entity.Owner=null;return true;
  }
}
InstallDocumentMetadata(DxfDocument);
InstallDocumentObjects(DxfDocument);
InstallDocumentMultiLeader(DxfDocument);
InstallDocumentSection(DxfDocument);

RegisterDatabaseModel('DxfDocument',DxfDocument);
