import test from 'node:test';
import assert from 'node:assert/strict';
import {Spline,Polyline3D,Polyline3DRecord,BezierCurveCubic,Vector3,Matrix3,EntityType,DxfTag,Layer} from '../../index.js';
import {ReferenceList} from '../../runtime/ReferenceList.js';
import {ArgumentException,ArgumentNullException,InvalidOperationException,NotSupportedException,IndexOutOfRangeException} from '../../runtime/Errors.js';
import {Copy} from '../../runtime/GeometryRuntime.js';
import {jsGeometry} from '../../tools/foundations-wire.mjs';
const points=()=>[Vector3.Zero,Vector3.UnitX,new Vector3(1,2,3),new Vector3(2,3,4)];
const spline=()=>new Spline(points(),[1,.5,.75,1],2);
const xyz=v=>[v.X,v.Y,v.Z];
function retained(){const p=new Polyline3D(points()),records=new ReferenceList(Array.from(p.Vertexes,()=>new Polyline3DRecord('VERTEX',new ReferenceList([new DxfTag(0,'VERTEX')])))),end=new Polyline3DRecord('SEQEND',new ReferenceList([new DxfTag(0,'SEQEND')]));p.SetStoredRecords(null,records,end);return {p,records,end};}
test('spline arrays expose fixed element locations and copy-on-index value adapters',()=>{const s=spline(),c=s.ControlPoints;const value=c.get_Item(1);value.Y=99;assert.equal(c[1].Y,0);c[1].Y=7;assert.equal(c.get_Item(1).Y,7);assert.throws(()=>{c.length=0;},NotSupportedException);assert.throws(()=>{c[4]=Vector3.Zero;},IndexOutOfRangeException);const v=new Vector3(2,3,4);c[0]=v;v.X=99;assert.equal(c[0].X,2);assert.equal(c,s.ControlPoints);});
test('fit creation enumerates the original input twice and does not replace stored controls on clone',()=>{let count=0;const input={[Symbol.iterator](){count++;return points()[Symbol.iterator]();}};const s=new Spline(input);assert.equal(count,2);s.ControlPoints[0]=new Vector3(9,8,7);const clone=s.Clone();assert.equal(clone.ControlPoints[0].X,9);assert.equal(clone.FitPoints[0].X,0);assert.equal(count,2);});
test('Bezier overloads consume caller enumeration once and preserve every span boundary',()=>{const curve=new BezierCurveCubic(...points());let calls=0;const curves={*[Symbol.iterator](){calls++;yield curve;yield curve;}};const s=Spline.CreateOverload('System.Collections.Generic.IEnumerable<netDxf.BezierCurveCubic>',curves);assert.equal(calls,1);assert.equal(s.ControlPoints.length,8);assert.deepEqual(Array.from(s.Knots),[0,0,0,0,.5,.5,.5,.5,1,1,1,1]);curve.StartPoint=Vector3.UnitZ;assert.equal(s.ControlPoints[0].Z,0);});
test('spline reversal preserves caller array identities and periodic twice-reverse state',()=>{const s=new Spline(points(),[1,.5,.75,1],2,true),cp=s.ControlPoints,w=s.Weights,k=s.Knots;const before={cp:Array.from(cp,Copy),w:Array.from(w),k:Array.from(k)};s.Reverse();s.Reverse();assert.equal(s.ControlPoints,cp);assert.equal(s.Weights,w);assert.equal(s.Knots,k);assert.deepEqual(Array.from(cp),before.cp);assert.deepEqual(Array.from(w),before.w);assert.deepEqual(Array.from(k),before.k);});
test('periodicity setter replaces knots even for repeated assignments without replacing controls',()=>{const s=spline(),k=s.Knots,cp=s.ControlPoints;k[0]=-5;s.IsClosedPeriodic=false;assert.notEqual(s.Knots,k);assert.equal(s.Knots[0],0);assert.equal(k[0],-5);assert.equal(s.ControlPoints,cp);const next=s.Knots;s.IsClosedPeriodic=false;assert.notEqual(s.Knots,next);});
test('tangents have nullable value semantics and linear-only transformations',()=>{const s=spline(),t=new Vector3(2,3,4);s.StartTangent=t;t.X=99;s.StartTangent.Y=99;assert.deepEqual(xyz(s.StartTangent),[2,3,4]);s.TransformBy(Matrix3.Scale(2,3,-4),new Vector3(100,200,300));assert.deepEqual(xyz(s.StartTangent),[4,9,-16]);assert.equal(s.EndTangent,null);});
test('derived spline copy adapter preserves stored geometry and ordinary Clone slices to SPLINE',()=>{class Derived extends Spline{constructor(s){super(...Spline.CopyConstructor(s,EntityType.Helix,'HELIX'));}}const s=spline(),d=new Derived(s);d.ControlPoints[0]=Vector3.UnitZ;assert.equal(s.ControlPoints[0].Z,0);assert.equal(d.CodeName,'HELIX');const q=d.Clone();assert.equal(q.constructor,Spline);assert.equal(q.CodeName,'SPLINE');assert.equal(q.ControlPoints[0].Z,1);});
test('polyline list indexing copies values and smoothing clone keeps the pinned omission',()=>{const p=new Polyline3D(points());p.Vertexes.get_Item(0).X=99;assert.equal(p.Vertexes.get_Item(0).X,0);p.SmoothType=6;const c=p.Clone();assert.equal(c.SmoothType,0);assert.equal(c.Flags,p.Flags);});
test('retained 3D record view is live, identity-stable and invalidates iterators on reverse',()=>{const {p,records,end}=retained(),view=p.VertexRecords,it=view.GetEnumerator();it.MoveNext();const last=records.get_Item(3);p.Reverse();assert.equal(p.VertexRecords,view);assert.equal(view.get_Item(0),last);assert.throws(()=>it.MoveNext(),InvalidOperationException);assert.equal(p.EndSequenceRecord,end);assert.equal(view.Add,undefined);});
test('retained 3D clone copies record resources but does not fabricate registration',()=>{const {p,records}=retained();records.get_Item(0).Resources.set(2,new Layer('V'));p.Handle='P';const q=p.Clone();assert.equal(q.Handle,null);assert.equal(q.VertexRecords.get_Item(0).Owner,q);assert.notEqual(q.VertexRecords.get_Item(0).Layer,records.get_Item(0).Layer);assert.throws(()=>q.InsertVertex(0,Vector3.Zero),InvalidOperationException);assert.throws(()=>q.RemoveVertexAt(0),InvalidOperationException);});
test('topology index and finite-point validation precede mutation and registration',()=>{const p=new Polyline3D([new Vector3(NaN,0,0),Vector3.UnitX]);assert.throws(()=>p.InsertVertex(-1,Vector3.Zero),{name:'ArgumentOutOfRangeException',ParamName:'index'});assert.throws(()=>p.InsertVertex(0,new Vector3(Infinity,0,0)),{name:'ArgumentException',ParamName:'position'});assert.throws(()=>p.MoveVertex(0,0),{name:'ArgumentException',ParamName:'Vertexes'});assert.equal(p.Vertexes.Count,2);});
test('registered topology adapter calls host checks before changing identities',()=>{const {p,records,end}=retained(),map=new Map(),trace=[];let next=0;const owner={Handle:'B'};p.Handle='P';p.Owner=owner;map.set('B',owner);map.set('P',p);for(const r of [...records,end]){r.Handle='R'+next++;map.set(r.Handle,r);}
 const doc={DrawingVariables:{AcadVer:0},GetObjectByHandle:h=>map.get(h)??null,PreparePolylineVertexInsertion(owner,position){trace.push('prepare');const r=new Polyline3DRecord('VERTEX',new ReferenceList());r.Owner=owner;r.Handle='NEW';return r;},RegisterPolylineVertexInsertion(r){trace.push('register');map.set(r.Handle,r);},ValidatePolylineVertexRemoval(r){trace.push('validate-remove');},UnregisterPolylineVertexRemoval(r){trace.push('unregister');map.delete(r.Handle);}};
 p.BindStoredRecordDocument(doc);const before=records.get_Item(0);p.InsertVertex(1,Vector3.UnitY);assert.deepEqual(trace,['prepare','register']);const inserted=records.get_Item(1);p.MoveVertex(1,4);assert.equal(records.get_Item(4),inserted);p.RemoveVertexAt(4);assert.deepEqual(trace,['prepare','register','validate-remove','unregister']);assert.equal(inserted.IsRemoved,true);assert.equal(inserted.Owner,null);assert.equal(inserted.Handle,'NEW');assert.equal(records.get_Item(0),before);assert.equal(p.EndSequenceRecord,end);
});
test('missing scenario targets report oracle lookup failures rather than fabricated production errors',()=>{const [r]=jsGeometry({steps:[{kind:'call',target:'absent',member:'Clone'}]});assert.deepEqual(r,{ok:false,error:'KeyNotFoundException',param:null});});
test('new spline and 3D-polyline audit preserves unique scenario identities',async()=>{const {splineModelCorpus,polyline3dCorpus}=await import('../../tools/spline-model-corpus.mjs');const p=[...splineModelCorpus(),...polyline3dCorpus()];assert.equal(new Set(p.map(v=>v.name)).size,p.length);});
