// Copyright (c) netDxf contributors. Licensed under the MIT License.
using System;
using System.Collections.Generic;
using System.Linq;
using netDxf.Objects;

namespace netDxf.IO
{
    internal sealed partial class DxfReader
    {
        private void RestoreEmptyLayerStateIdentities(DictionaryObject projection)
        {
            // Only the canonical empty pair generated by netDxf is claimed here.
            // Extra entries, application metadata, alternate flags or private fields
            // stay on the existing conversion path; do not mislabel it lossless.
            var parent = this.databaseRecords.SingleOrDefault(r => r.Object.Handle == projection.Handle);
            if (parent == null || parent.Entries.Count != 1) return;
            var entry = parent.Entries[0];
            if (entry.Item1 != DxfObjectCode.LayerStates || !entry.Item3) return;
            var child = this.databaseRecords.SingleOrDefault(r => r.Object.Handle == entry.Item2);
            if (child == null || child.Entries.Count != 0) return;
            if (!EmptyLayerDictionaryShape(parent.DictionaryTags, false)
                || !EmptyLayerDictionaryShape(child.DictionaryTags, true)) return;
            // An absent or payload-only LAYER identity is handled by the existing
            // late reference checks. Do not legitimize a generated replacement or
            // mask the original dangling-reference diagnostic with this optional path.
            if (!ReferenceEquals(this.GetObjectBySourceHandle(this.doc.Layers.Handle, true), this.doc.Layers)) return;
            if (!ReferenceEquals(this.GetObjectBySourceHandle(parent.Metadata.Owner, true), this.doc.Layers)
                || !SameLayerDictionaryHandle(child.Metadata.Owner, parent.Object.Handle))
                throw new FormatException("Canonical layer-state dictionaries have inconsistent structural ownership.");
            var manager = this.doc.Layers.StateManager;
            manager.RestoreEmptyDictionaryIdentities(parent.Object.Handle, child.Object.Handle);
            this.RecordSourceObject(manager, parent.SourceIdentity);
            this.RecordSourceObject(manager.StatesDictionaryObject, child.SourceIdentity);
        }

        private static bool EmptyLayerDictionaryShape(List<DxfTag> tags, bool child)
        {
            if (tags == null || tags.Count != (child ? 5 : 7)) return false;
            short[] codes = child ? new short[] { 5, 330, 100, 280, 281 }
                : new short[] { 5, 330, 100, 280, 281, 3, 360 };
            for (int i = 0; i < codes.Length; i++) if (tags[i].Code != codes[i]) return false;
            return Equals(tags[2].Value, "AcDbDictionary") && Equals(tags[3].Value, (short)1)
                && Equals(tags[4].Value, (short)1)
                && (child || Equals(tags[5].Value, DxfObjectCode.LayerStates));
        }

        private static bool SameLayerDictionaryHandle(string a, string b)
        {
            return ulong.TryParse(a, System.Globalization.NumberStyles.AllowHexSpecifier,
                    System.Globalization.CultureInfo.InvariantCulture, out ulong first)
                && ulong.TryParse(b, System.Globalization.NumberStyles.AllowHexSpecifier,
                    System.Globalization.CultureInfo.InvariantCulture, out ulong second)
                && first != 0 && first == second;
        }
    }
}
