// Copyright (c) Daniel Carvajal. MIT License; see package LICENSE.
// Generated from the pinned C# source by tools/SourceInventory. Do not hand-edit.
export const EntityType = Object.freeze({
  "Arc": 0,
  "Circle": 1,
  "Dimension": 2,
  "Ellipse": 3,
  "Face3D": 4,
  "Hatch": 5,
  "Image": 6,
  "Insert": 7,
  "Leader": 8,
  "Line": 9,
  "Mesh": 10,
  "MLine": 11,
  "MText": 12,
  "Point": 13,
  "PolyfaceMesh": 14,
  "PolygonMesh": 15,
  "Polyline2D": 16,
  "Polyline3D": 17,
  "Ray": 18,
  "Shape": 19,
  "Solid": 20,
  "Spline": 21,
  "Text": 22,
  "Tolerance": 23,
  "Trace": 24,
  "Underlay": 25,
  "Viewport": 26,
  "Wipeout": 27,
  "XLine": 28,
  "Helix": 29,
  "Light": 30,
  "Ole2Frame": 31,
  "OleFrame": 32,
  "Body": 33,
  "Region": 34,
  "Solid3D": 35,
  "MultiLeader": 36,
  "StoredTable": 37,
  "Section": 38,
  "OpaqueEntity": 39
});
