namespace NetDxf.Conformance;

internal static partial class Program
{
    static partial void RunAdditionalTests()
    {
        RegisterBinarySentinelTests();
        RegisterBinaryChunkTests();
        RegisterXDataCloneTests();
        RegisterUcsElevationTests();
        RegisterNamedViewTests();
        RegisterTextFramingTests();
        RegisterMinimalDocumentTests();
        RegisterHeaderProbeTests();
        RegisterStrictTextValueTests();
        RegisterStrictBinaryValueTests();
        RegisterUcsOrthographicTests();
        RegisterMTextCloneDirectionTests();
        RegisterMTextBackgroundTests();
        RegisterRasterOwnershipTests();
        RegisterCustomHeaderUnicodeTests();
        RegisterHeaderCommentTests();
        RegisterSurfaceDensityHeaderTests();
        RegisterClassDefinitionTests();
        RegisterInsertArrayTests();
        RegisterRawTagTests();
        RegisterDoublePrecisionWriterTests();
        RegisterBinaryChunkWriterTests();
        RegisterRawDocumentTests();
        RegisterRawDocumentBoundaryTests();
        RegisterFileStreamLifetimeTests();
        RegisterRawRecordTests();
        RegisterSupportFolderLookupTests();
        RegisterRawDimensionStyleNameTests();
        RegisterRawLegacyProfileTests();
        RegisterRawR12Tests();
        RegisterMeshVersionTests();
        RegisterMeshBlendCreaseTests();
        RegisterMeshReadValidationTests();
        RegisterHatchDoublePatternTests();
        RegisterHatchSeedPointTests();
        RegisterHatchSeedPointApiTests();
        RegisterHatchPixelSizeTests();
        RegisterHatchPixelSizeApiTests();
        RegisterHatchXDataPreservationTests();
        RegisterHatchPolylineClosureTests();
        RegisterHatchPolylineInputTests();
        RegisterHatchPatternValidationTests();
        RegisterHatchBoundaryFlagsTests();
        RegisterHatchPatternOrderTests();
        RegisterHatchEdgeDispatchTests();
        RegisterHatchGradientAngleTests();
        RegisterHatchGradientShiftTests();
        RegisterHatchGradientShiftApiTests();
        RegisterHatchGradientColorStateTests();
        RegisterHatchGradientPacketTests();
        RegisterSplineTangentTransformTests();
        RegisterHatchSplineFitTests();
        RegisterHatchSplineFitApiTests();
        RegisterHatchPathCountTests();
        RegisterHatchGradientAciTests();
        RegisterHatchGradientAciApiTests();
    }
}
