#!/usr/bin/env python3
# SPDX-License-Identifier: LGPL-2.1-or-later
# Audited, pin-checked translation of a fixed glibc source set, not a general C translator.
import re, struct, json, pathlib, hashlib, shutil
import sys
ROOT=pathlib.Path(__file__).resolve().parents[2]
SOURCE=pathlib.Path(sys.argv[1]).resolve() if len(sys.argv)>1 and sys.argv[1]!='--check' else ROOT/'third_party/glibc-math'
CHECK='--check' in sys.argv
(ROOT/'runtime/reference-math').mkdir(parents=True,exist_ok=True)
manifest=json.loads((ROOT/'tools/ReferenceMath/source-manifest.json').read_text())
for name,expected in manifest['files'].items():
 actual=hashlib.sha256((SOURCE/name).read_bytes()).hexdigest()
 if actual!=expected:raise ValueError('Unpinned upstream source: '+name)
if not CHECK:
 for name in manifest['files']:
  target=ROOT/'third_party/glibc-math'/name
  if target.resolve()!=(SOURCE/name).resolve():
   target.parent.mkdir(parents=True,exist_ok=True);shutil.copyfile(SOURCE/name,target)
 shutil.copyfile(SOURCE/'COPYING.LIB',ROOT/'runtime/reference-math/LICENSE.LGPL-2.1')
 shutil.copyfile(SOURCE/'COPYING',ROOT/'runtime/reference-math/LICENSE.GPL-2')
 (ROOT/'runtime/reference-math/source-manifest.json').write_text(json.dumps(manifest,indent=2)+'\n')
if CHECK:
 for name,target in [('COPYING.LIB','LICENSE.LGPL-2.1'),('COPYING','LICENSE.GPL-2')]:
  if (SOURCE/name).read_bytes()!=(ROOT/'runtime/reference-math'/target).read_bytes():raise ValueError('License text drift: '+target)
 if json.loads((ROOT/'runtime/reference-math/source-manifest.json').read_text())!=manifest:raise ValueError('Runtime source manifest drift')
src=SOURCE/'sysdeps/ieee754/dbl-64'
out=ROOT/'runtime/reference-math';out.mkdir(exist_ok=True)
license='''// SPDX-License-Identifier: LGPL-2.1-or-later
// Adapted from the IBM Accurate Mathematical Library in glibc 2.35.
// Copyright (C) 2001-2022 Free Software Foundation, Inc.
// JavaScript adaptation: 2026 netDxf contributors.
// See LICENSE.LGPL-2.1 and source-manifest.json for source provenance.
// Generated by tools/ReferenceMath/generate.py; upstream preferred sources are bundled.
'''
def clean(s):return re.sub(r'/\*.*?\*/','',s,flags=re.S)
def dec(s):
 s=s.strip()
 return repr(float.fromhex(s) if 'p' in s.lower() and '0x' in s.lower() else float(s))
def getfn(file,name):
 s=clean((src/file).read_text());m=re.search(r'\b'+name+r'\s*\([^;{}]*\)\s*\{',s);assert m,(file,name)
 start=s.index('{',m.start());i=start+1;depth=1
 while depth:
  depth+=(s[i]=='{')-(s[i]=='}');i+=1
 return s[start+1:i-1]
def consts(file):
 s=clean((src/file).read_text());d={}
 if '#ifdef BIG_ENDI' in s:
  big=s.split('#ifdef BIG_ENDI',1)[1].split('#else',1)[0]
  for n,hi,lo in re.findall(r'\b(\w+)\s*=\s*\{\{\s*(0x\w+)\s*,\s*(0x\w+)\s*\}',big):d[n]=repr(struct.unpack('>d',struct.pack('>II',int(hi,16),int(lo,16)))[0])
 for decl in re.findall(r'static\s+const\s+double\s+([^;]+);',s):
  if '[' in decl:continue
  for part in decl.split(','):
   n,v=part.split('=');n=n.strip();v=v.strip();d[n]=dec(v) if v!='CN' else '134217729.0'
 return d

def constdecl(d):return '\n'.join('const '+n+' = '+v+';' for n,v in d.items())+'\n'
def table(file,name,width=None):
 s=clean((src/file).read_text());s=s.split('#ifdef BIG_ENDI')[1].split('#else')[0]
 s=s[s.index('=')+1:];words=re.findall(r'0[xX][0-9a-fA-F]{8}',s);assert len(words)%2==0
 vals=[struct.unpack('>d',struct.pack('>II',int(words[i],16),int(words[i+1],16)))[0] for i in range(0,len(words),2)]
 expected={'sincostab.c':440,'uatan.tbl':1687,'asincos.tbl':2568,'utan.tbl':744}[file]
 assert len(vals)==expected,(file,len(vals),expected)
 if width:vals=[vals[i:i+width] for i in range(0,len(vals),width)]
 text='const '+name+' = Object.freeze([\n'+',\n'.join('  '+('Object.freeze('+json.dumps(v)+')' if isinstance(v,list) else repr(v)) for v in vals)+'\n]);\n'
 return text

def array(file,name):
 s=clean((src/file).read_text());s=re.search(r'\b'+name+r'\[\d*\]\s*=\s*\{([^}]+)\}',s).group(1)
 return 'const '+name+' = Object.freeze(['+s.strip()+']);\n'

def casts(s):
 pat=re.compile(r'\(int\)\s*')
 while m:=pat.search(s):
  st=m.end()
  if s[st]=='(':
   depth=1;e=st+1
   while depth:depth+=(s[e]=='(')-(s[e]==')');e+=1
  else:
   e=st+len(re.match(r'[a-zA-Z_]\w*(?:\.\w+)?',s[st:]).group())
  s=s[:m.start()]+'Math.trunc('+s[st:e]+')'+s[e:]
 return s

def transform(s,d):
 s=re.sub(r'^\s*#.*$','',s,flags=re.M)
 s=re.sub(r'\bint\s+__branred\s*\([^;]+;','',s)
 s=re.sub(r'\b(?:SET_RESTORE_ROUND_53BIT|SET_RESTORE_ROUND|math_check_force_underflow_nonneg|math_check_force_underflow|math_force_eval)\s*\([^;]+;',';',s)
 s=s.replace('__set_errno (EDOM);',';')
 s=re.sub(r'\bmynumber\s+([^;]+);',lambda m:'let '+', '.join(x.strip()+' = new Words()' for x in m[1].split(','))+';',s)
 s=re.sub(r'\bstatic\s+const\s+int\b','const',s)
 s=re.sub(r'\b(?:double|int4|int)\s+([\w,\[\]\s]+)(?=[;=])',r'let \1',s)
 s=s.replace('let r[6],','let r = new Array(6),')
 s=casts(s)
 for n in d:s=re.sub(r'\b'+n+r'\.(?:d|x)\b',n,s)
 s=re.sub(r'(cij\[[^\]]+\]\[[^\]]+\]|xfg\[[^\]]+\]\[[^\]]+\])\.d',r'\1',s)
 s=s.replace('asncs.x[','asncs[').replace('HIGH_HALF','1').replace('LOW_HALF','0')
 s=re.sub(r'\b(ux|uy)\s*==\s*(0x[89a-fA-F][0-9a-fA-F]{7})',r'(\1 >>> 0) === \2',s)
 s=s.replace('fabs','Math.abs').replace('copysign','copySign').replace('DBL_MIN','2.2250738585072014e-308')
 s=s.replace('__signArctan','signArctan').replace('signArctan2','signArctan')
 s=re.sub(r'\b(EADD|ESUB|EMULV)\s*\(([^;]+)\);',lambda m: macro(m),s)
 s=re.sub(r'\bDIV2\s*\(([^;]+)\);',lambda m:'['+','.join(x.strip() for x in m[1].split(',')[4:6])+'] = div2('+','.join(m[1].split(',')[:4])+');',s)
 s=s.replace('goto ret;','return retval;').replace('ret:','')
 s=re.sub(r'n\s*=\s*\(__branred\s*\(x,\s*&a,\s*&da\)\)\s*&\s*0x00000001;',r'[n,a,da] = branred(x); n &= 1;',s)
 s=re.sub(r'n\s*=\s*(?:__branred|reduce_sincos)\s*\(x,\s*&a,\s*&da\);',lambda m:'[n,a,da] = '+('branred' if '__branred' in m[0] else 'reduce_sincos')+'(x);',s)
 s=re.sub(r'\(k-450\)/24',r'Math.trunc((k-450)/24)',s)
 s=s.replace('return ((Math.trunc(sum)))&3;', 'return [Math.trunc(sum)&3,a,aa];')
 s=re.sub(r'0x[0-9a-fA-F]+(?:\.[0-9a-fA-F]*)?p[+-]?\d+',lambda m:dec(m[0]),s)
 return s

def macro(m):
 args=[v.strip() for v in m[2].split(',')];assert len(args)==4
 return f'[{args[2]},{args[3]}] = '+{'EADD':'add2','ESUB':'sub2','EMULV':'mul2'}[m[1]]+'('+','.join(args[:2])+');'
common="import { Words, copySign, signArctan, add2, sub2, mul2, div2, fma } from './arithmetic.js';\n"
def write(name,text):
 text=license+text
 if CHECK:
  if not (out/name).exists() or (out/name).read_text()!=text:raise ValueError('Generated reference-math drift: '+name)
 else:(out/name).write_text(text)

for fname,srcfile,head,fnnames,tables in [
 ('atan.js','s_atan.c','atnat.h',[('__atan','Atan')],table('uatan.tbl','cij',7)),
 ('atan2.js','e_atan2.c','atnat2.h',[('__ieee754_atan2','Atan2')],table('uatan.tbl','cij',7)),
 ('asincos.js','e_asin.c','uasncs.h',[('__ieee754_asin','Asin'),('__ieee754_acos','Acos')],table('asincos.tbl','asncs')+array('root.tbl','inroot')+array('powtwo.tbl','powtwo')),
 ('tan.js','s_tan.c','utan.h',[('__tan','Tan')],table('utan.tbl','xfg',4)),
]:
 d=consts(head);extra='const TWO52 = 4503599627370496;\n'
 if head=='atnat.h':
  for upper,lower in [('A','a'),('B','b'),('C','c'),('D','d'),('E','e'),('HPI','hpi'),('HPI1','hpi1'),('MHPI','mhpi')]:d[upper]=d[lower]
 text=common+('import { branred } from "./branred.js";\n' if fname=='tan.js' else '')+constdecl(d)+extra+tables
 for fn,new in fnnames:
  body=transform(getfn(srcfile,fn),d)
  if new=='Atan2':body=body.replace('return x + y;', 'return x + x;')
  text+=f'export function {new}('+('y,x' if new=='Atan2' else 'x')+') {\n'+body+'\n}\n'
 write(fname,text)
d=consts('branred.h');body=getfn('branred.c','__branred').replace('*a=s;','a=s;').replace('*aa=t;','aa=t;');body=transform(body,d)
body=re.sub(r'return\s+\(Math.trunc\(sum\)\)&3;',r'return [Math.trunc(sum)&3,a,aa];',body)
write('branred.js',common+constdecl(d)+array('branred.h','toverp')+'export function branred(x) {\nlet a,aa;\n'+body+'\n}\n')
# The two sin/cos small-argument helpers have statement-expression macros in C.
# Spell out those macros without altering the operation grouping.
d=consts('usncs.h')
text=common+'import { branred } from "./branred.js";\n'+constdecl(d)+table('sincostab.c','sincostab')+'''const sn3 = -1.66666666666664880952546298448555E-01;
const sn5 = 8.33333214285722277379541354343671E-03;
const cs2 = 4.99999999999999999999950396842453E-01;
const cs4 = -4.16666666666664434524222570944589E-02;
const cs6 = 1.38888874007937613028114285595617E-03;
function taylor_sin(xx,x,dx) {
  const poly = ((((s5*xx+s4)*xx+s3)*xx+s2)*xx)+s1;
  const t = ((poly*x-0.5*dx)*xx+dx);
  return x+t;
}
'''
for fn in ['do_cos','do_sin','reduce_sincos','do_sincos','__sin','__cos']:
 body=getfn('s_sin.c',fn)
 body=body.replace('return TAYLOR_SIN (x * x, x, dx);','return taylor_sin(x*x,x,dx);')
 body=body.replace('SINCOS_TABLE_LOOKUP (u, sn, ssn, cs, ccs);','const k = u.i[0] << 2; sn=sincostab[k]; ssn=sincostab[k+1]; cs=sincostab[k+2]; ccs=sincostab[k+3];')
 if fn=='reduce_sincos': body=body.replace('*a = b;','a = b;').replace('*da = db;','da = db;').replace('return n;','return [n,a,da];');body='let a,da;\n'+body
 body=transform(body,d)
 if fn=='do_cos':
  body=body.replace('s = x + x * xx * (sn3 + xx * sn5);','s = fma(x*xx, fma(xx,sn5,sn3), x);')
  body=body.replace('c = xx * (cs2 + xx * (cs4 + xx * cs6));','c = xx * fma(xx,fma(xx,cs6,cs4),cs2);')
  body=body.replace('cor = (ccs - s * ssn - cs * c) - sn * s;','cor = fma(-sn,s,fma(-cs,c,fma(-s,ssn,ccs)));')
 if fn=='do_sin':
  body=body.replace('s = x + (dx + x * xx * (sn3 + xx * sn5));','s = x + fma(x*xx,fma(xx,sn5,sn3),dx);')
  body=body.replace('c = x * dx + xx * (cs2 + xx * (cs4 + xx * cs6));','c = fma(x,dx,xx*fma(xx,fma(xx,cs6,cs4),cs2));')
  body=body.replace('cor = (ssn + s * ccs - sn * c) + cs * s;','cor = fma(cs,s,fma(-sn,c,fma(s,ccs,ssn)));')
 name={'__sin' :'Sin','__cos':'Cos'}.get(fn,fn)
 args={'do_cos':'x,dx','do_sin':'x,dx','reduce_sincos':'x','do_sincos':'a,da,n','__sin':'x','__cos':'x'}[fn]
 text+=('export ' if fn.startswith('__') else '')+'function '+name+'('+args+') {\n'+body+'\n}\n'
write('sincos.js',text)
