// SPDX-License-Identifier: LGPL-2.1-or-later
// Adapted from the IBM Accurate Mathematical Library in glibc 2.35.
// Copyright (C) 2001-2022 Free Software Foundation, Inc.
// JavaScript adaptation: 2026 netDxf contributors.
// See LICENSE.LGPL-2.1 and source-manifest.json for source provenance.
// Generated by tools/ReferenceMath/generate.py; upstream preferred sources are bundled.
import { Words, copySign, signArctan, add2, sub2, mul2, div2, fma } from './arithmetic.js';
const t576 = 2.4733040147310453e+173;
const tm600 = 2.409919865102884e-181;
const tm24 = 5.960464477539063e-08;
const big = 6755399441055744.0;
const big1 = 2.7021597764222976e+16;
const hp0 = 1.5707963267948966;
const hp1 = 6.123233995736766e-17;
const mp1 = 1.5707963407039642;
const mp2 = -1.3909067675399456e-08;
const split = 134217729.0;
const toverp = Object.freeze([10680707.0,  7228996.0,  1387004.0,  2578385.0, 16069853.0,
  12639074.0,  9804092.0,  4427841.0, 16666979.0, 11263675.0,
  12935607.0,  2387514.0,  4345298.0, 14681673.0,  3074569.0,
  13734428.0, 16653803.0,  1880361.0, 10960616.0,  8533493.0,
   3062596.0,  8710556.0,  7349940.0,  6258241.0,  3772886.0,
   3769171.0,  3798172.0,  8675211.0, 12450088.0,  3874808.0,
   9961438.0,   366607.0, 15675153.0,  9132554.0,  7151469.0,
   3571407.0,  2607881.0, 12013382.0,  4155038.0,  6285869.0,
   7677882.0, 13102053.0, 15825725.0,   473591.0,  9065106.0,
  15363067.0,  6271263.0,  9264392.0,  5636912.0,  4652155.0,
   7056368.0, 13614112.0, 10155062.0,  1944035.0,  9527646.0,
  15080200.0,  6658437.0,  6231200.0,  6832269.0, 16767104.0,
   5075751.0,  3212806.0,  1398474.0,  7579849.0,  6349435.0,
  12618859.0,  4703257.0, 12806093.0, 14477321.0,  2786137.0,
  12875403.0,  9837734.0, 14528324.0, 13719321.0,   343717.0]);
export function branred(x) {
let a,aa;

  let i,k;
  let u = new Words(), gor = new Words();
  let r = new Array(6),s,t,sum,b,bb,sum1,sum2,b1,bb1,b2,bb2,x1,x2,t1,t2;

  x*=tm600;
  t=x*split;   
  x1=t-(t-x);
  x2=x-x1;
  sum=0;
  u.x = x1;
  k = (u.i[1]>>20)&2047;
  k = Math.trunc((k-450)/24);
  if (k<0)
    k=0;
  gor.x = t576;
  gor.i[1] -= ((k*24)<<20);
  for (i=0;i<6;i++)
    { r[i] = x1*toverp[k+i]*gor.x; gor.x *= tm24; }
  for (i=0;i<3;i++) {
    s=(r[i]+big)-big;
    sum+=s;
    r[i]-=s;
  }
  t=0;
  for (i=0;i<6;i++)
    t+=r[5-i];
  bb=(((((r[0]-t)+r[1])+r[2])+r[3])+r[4])+r[5];
  s=(t+big)-big;
  sum+=s;
  t-=s;
  b=t+bb;
  bb=(t-b)+bb;
  s=(sum+big1)-big1;
  sum-=s;
  b1=b;
  bb1=bb;
  sum1=sum;
  sum=0;

  u.x = x2;
  k = (u.i[1]>>20)&2047;
  k = Math.trunc((k-450)/24);
  if (k<0)
    k=0;
  gor.x = t576;
  gor.i[1] -= ((k*24)<<20);
  for (i=0;i<6;i++)
    { r[i] = x2*toverp[k+i]*gor.x; gor.x *= tm24; }
  for (i=0;i<3;i++) {
    s=(r[i]+big)-big;
    sum+=s;
    r[i]-=s;
  }
  t=0;
  for (i=0;i<6;i++)
    t+=r[5-i];
  bb=(((((r[0]-t)+r[1])+r[2])+r[3])+r[4])+r[5];
  s=(t+big)-big;
 sum+=s;
 t-=s;
 b=t+bb;
 bb=(t-b)+bb;
 s=(sum+big1)-big1;
 sum-=s;

 b2=b;
 bb2=bb;
 sum2=sum;

 sum=sum1+sum2;
 b=b1+b2;
 bb = (Math.abs(b1)>Math.abs(b2))? (b1-b)+b2 : (b2-b)+b1;
 if (b > 0.5)
   {b-=1.0; sum+=1.0;}
 else if (b < -0.5)
   {b+=1.0; sum-=1.0;}
 s=b+(bb+bb1+bb2);
 t=((b-s)+bb)+(bb1+bb2);
 b=s*split;
 t1=b-(b-s);
 t2=s-t1;
 b=s*hp0;
 bb=(((t1*mp1-b)+t1*mp2)+t2*mp1)+(t2*mp2+s*hp1+t*hp0);
 s=b+bb;
 t=(b-s)+bb;
 a=s;
 aa=t;
 return [Math.trunc(sum)&3,a,aa]; 

}
