// Copyright (c) netDxf contributors. Licensed under the MIT License.
using System.Collections.Generic;
using netDxf.Header;
using netDxf.Tables;

namespace netDxf.Entities
{
    public static partial class DimensionBlock
    {
        // Only labels generated by this builder are passed here. Do not traverse
        // custom arrow blocks or alter existing user-authored MTEXT entities.
        internal static void ApplyDimensionTextFill(Dimension dim,
            IEnumerable<EntityObject> entities, DxfVersion? targetVersion)
        {
            AciColor color = dim.Style.TextFillColor;
            if (dim.StyleOverrides.TryGetValue(DimensionStyleOverrideType.TextFillColor,
                out DimensionStyleOverride item))
                color = (AciColor)item.Value; // A present null explicitly clears the inherited fill.

            // Retain the existing MTEXT writer eligibility and legacy generation
            // behavior. The DIMSTYLE/DSTYLE settings remain stored, not erased.
            bool enabled = color != null && (!targetVersion.HasValue || targetVersion >= DxfVersion.AutoCad2007);
            foreach (EntityObject entity in entities)
            {
                MText text = entity as MText;
                if (text == null) continue;
                // DIMTFILLCLR is an indexed field, unlike general MTEXT RGB fills.
                // Copy its value, never retain a mutable AciColor or a shared mask.
                text.BackgroundFill = enabled ? new MTextBackgroundFill
                {
                    Flags = MTextBackgroundFillFlags.UseColor,
                    ColorIndex = color.Index
                } : null;
            }
        }
    }
}
