// Copyright (c) netDxf contributors. Licensed under the MIT License.
using System;
using System.Collections.Generic;

namespace netDxf.Entities
{
    public partial class Polyline3D
    {
        /// <summary>Maximum vertices generated by one polyline conversion.</summary>
        /// <remarks>Both sampled and unsmoothed output counts are bounded before generated allocation.</remarks>
        public const int MaximumConvertedVertices = CurvePolylineConversion.MaximumVertices;

        /// <summary>Projects this curve onto a plane parallel to its normal's object XY plane.</summary>
        /// <param name="precision">Sample count for a smoothed curve; nonnegative and ignored for an unsmoothed curve.</param>
        /// <param name="elevation">Finite signed offset of the output plane along the unit normal.</param>
        /// <returns>A detached, unsmoothed 2D polyline with independently copied ordinary appearance and XData.</returns>
        /// <remarks>
        /// This is an explicit orthogonal projection, not a planarity test. Each sampled point's object Z coordinate
        /// is discarded and replaced by elevation. Identity, proxy graphics and unsupported dependencies are not copied.
        /// </remarks>
        public Polyline2D ToPolyline2D(int precision, double elevation)
        {
            if (precision < 0) throw new ArgumentOutOfRangeException(nameof(precision), precision, "Precision must be nonnegative.");
            CurvePolylineConversion.CheckElevation(elevation);
            this.ValidateExplosionGeometry();
            this.ValidateExplosionDependencies();
            IList<Vector3> points = this.vertexes;
            int count = this.smoothType == PolylineSmoothType.NoSmooth ? points.Count : Math.Max(2, precision);
            CurvePolylineConversion.CheckCount(count, nameof(precision));
            if (this.smoothType != PolylineSmoothType.NoSmooth) points = this.PolygonalVertexes(precision);
            Polyline2D result = CurvePolylineConversion.Project(this, points, base.Normal, this.IsClosed, elevation);
            result.LinetypeGeneration = this.LinetypeGeneration;
            return result;
        }
    }
}
