// Copyright (c) netDxf contributors. Licensed under the MIT License.
using System;
using System.Collections.Generic;
using netDxf.Tables;

namespace netDxf.Entities
{
    public partial class Polyline3D
    {
        /// <summary>Maximum number of line segments generated by one Explode call.</summary>
        /// <remarks>Spline sampling and output counts are checked before allocating generated geometry.</remarks>
        public const int MaximumExplodedSegments = 1000000;

        private List<EntityObject> ExplodeLines()
        {
            this.ValidateExplosionDependencies();
            IList<Vector3> points = this.PrepareExplosionPoints();
            int count = this.IsClosed ? points.Count : Math.Max(0, points.Count - 1);
            var result = new List<EntityObject>(count);
            for (int i = 0; i < count; i++)
            {
                var line = new Line(points[i], points[(i + 1) % points.Count])
                {
                    Layer = (Layer)this.Layer.Clone(), Linetype = (Linetype)this.Linetype.Clone(),
                    Color = (AciColor)this.Color.Clone(), Transparency = (Transparency)this.Transparency.Clone(),
                    Lineweight = this.Lineweight, LinetypeScale = this.LinetypeScale,
                    Normal = base.Normal, IsVisible = this.IsVisible,
                    ColorName = this.ColorName, ShadowMode = this.ShadowMode
                };
                foreach (XData data in this.XData.Values) line.XData.Add((XData)data.Clone());
                result.Add(line);
            }
            return result;
        }

        // HATCH retains the original contour objects and validates/adopts their
        // associations itself. Its edge extraction is not a detached conversion
        // and must not discard, clone, or reject metadata it does not consume.
        internal List<EntityObject> GetBoundaryLineGeometry()
        {
            IList<Vector3> points = this.PrepareExplosionPoints();
            int count = this.IsClosed ? points.Count : Math.Max(0, points.Count - 1);
            var result = new List<EntityObject>(count);
            for (int i = 0; i < count; i++)
                result.Add(new Line(points[i], points[(i + 1) % points.Count]) { Normal = base.Normal });
            return result;
        }

        private IList<Vector3> PrepareExplosionPoints()
        {
            this.ValidateExplosionGeometry();
            IList<Vector3> points = this.vertexes;
            if (this.smoothType != PolylineSmoothType.NoSmooth)
            {
                var document = this.Owner?.Record?.Owner?.Owner;
                int segments = document == null ? DefaultSplineSegs : document.DrawingVariables.SplineSegs;
                long precision = (long)segments * (this.IsClosed ? this.vertexes.Count : this.vertexes.Count - 1);
                if (precision > MaximumExplodedSegments)
                    throw new ArgumentOutOfRangeException(nameof(precision), precision, "Exploded spline sample budget exceeded.");
                // Keep PolygonalVertexes' existing minimum of two samples.
                points = this.PolygonalVertexes((int)Math.Max(2L, precision));
            }
            int count = this.IsClosed ? points.Count : Math.Max(0, points.Count - 1);
            if (count > MaximumExplodedSegments)
                throw new ArgumentOutOfRangeException(nameof(count), count, "Exploded line budget exceeded.");
            // Validate sampled coordinates as well as the source controls.
            foreach (Vector3 point in points) CheckExplosionPoint(point);
            return points;
        }

        private void ValidateExplosionGeometry()
        {
            if (this.smoothType != PolylineSmoothType.NoSmooth && this.smoothType != PolylineSmoothType.Quadratic
                && this.smoothType != PolylineSmoothType.Cubic)
                throw new NotSupportedException("Unknown polyline smoothing cannot be exploded.");
            if (this.HasStoredRecords) this.ValidateStoredRecordGeometry();
            foreach (Vector3 point in this.vertexes) CheckExplosionPoint(point);
            Vector3 normal = base.Normal;
            CheckExplosionPoint(normal);
            if (Math.Abs(Vector3.DotProduct(normal, normal) - 1.0) > 2e-15)
                throw new InvalidOperationException("Polyline explosion requires a finite unit auxiliary normal.");
        }

        private void ValidateExplosionDependencies()
        {
            if (this.ExtensionDictionary != null || this.PersistentReactors.Count != 0 || this.Reactors.Count != 0)
                throw new NotSupportedException("Associated polyline graphs require explicit dependency conversion.");
            foreach (XData data in this.XData.Values)
                foreach (XDataRecord record in data.XDataRecord)
                    if (record.Code == XDataCode.DatabaseHandle)
                        throw new NotSupportedException("Polyline XData handles require explicit dependency conversion.");
            foreach (Polyline3DRecord record in this.StoredRecords)
            {
                if (!record.CanClone() || record.XData.Count != 0)
                    throw new NotSupportedException("Decorated polyline children require explicit dependency conversion.");
                foreach (var tag in record.Tags)
                {
                    switch (tag.Code)
                    {
                        case 0: case 5: case 330: case 100: case 10: case 20: case 30: case 70: break;
                        case 40: case 41:
                            if ((double)tag.Value != 0.0)
                                throw new NotSupportedException("Nonzero child widths require explicit conversion.");
                            break;
                        case 62:
                            if ((short)tag.Value != this.Color.Index)
                                throw new NotSupportedException("Child-specific colors require explicit conversion.");
                            break;
                        case 420:
                            if (!this.Color.UseTrueColor || (int)tag.Value != ((this.Color.R << 16) | (this.Color.G << 8) | this.Color.B))
                                throw new NotSupportedException("Child-specific true colors require explicit conversion.");
                            break;
                        case 8:
                            if ((string)tag.Value != "0" && !string.Equals((string)tag.Value, this.Layer.Name, StringComparison.OrdinalIgnoreCase))
                                throw new NotSupportedException("Child-specific layers require explicit conversion.");
                            break;
                        default: throw new NotSupportedException("Decorated polyline children require explicit dependency conversion.");
                    }
                }
            }
        }

        private static void CheckExplosionPoint(Vector3 point)
        {
            if (double.IsNaN(point.X) || double.IsInfinity(point.X) || double.IsNaN(point.Y) || double.IsInfinity(point.Y)
                || double.IsNaN(point.Z) || double.IsInfinity(point.Z))
                throw new InvalidOperationException("Polyline explosion requires finite geometry.");
        }
    }
}
