// Copyright (c) netDxf contributors. Licensed under the MIT License.
using System;

namespace netDxf.Entities
{
    public partial class Spline
    {
        /// <summary>Maximum control points generated by one knot-refinement operation.</summary>
        public const int MaximumRefinedControlPoints = 1000000;

        /// <summary>Returns a detached nonperiodic spline with an interior knot inserted without refitting.</summary>
        /// <param name="parameter">Finite parameter strictly inside the active knot domain.</param>
        /// <param name="times">Additional copies of the knot, not its target multiplicity.</param>
        /// <returns>A new spline with the same degree, parameter domain and independently copied metadata.</returns>
        /// <remarks>
        /// Supports finite positive weights and degrees 1 through MaxDegree. Final interior multiplicity
        /// cannot exceed the degree. Exact rational homogeneous arithmetic precedes one rounding of each
        /// changed weight and coordinate; binary64 storage can introduce rounding error. Unaffected controls
        /// retain their exact components. Source arrays, fits, tangents and ownership are not mutated.
        /// Private dependency graphs and derived entity types require explicit conversion and reject.
        /// </remarks>
        public Spline InsertKnot(double parameter, int times = 1)
        {
            if (times < 1 || times > this.degree)
                throw new ArgumentOutOfRangeException(nameof(times), "Insert between one and Degree additional knots.");
            this.ValidateKnotOperation(parameter, times, out int span, out int multiplicity);
            if (times > this.degree - multiplicity)
                throw new ArgumentOutOfRangeException(nameof(times), "The final interior knot multiplicity cannot exceed the degree.");
            PeriodicSplineExactEvaluation.InsertKnot(this.controlPoints, this.weights, this.knots,
                this.degree, parameter, span, multiplicity, times,
                out Vector3[] points, out double[] resultWeights, out double[] resultKnots);
            return this.CreateKnotResult(points, resultWeights, resultKnots, this.fitPoints, this.creationMethod,
                this.startTangent, this.endTangent);
        }

        private void ValidateKnotOperation(double parameter, int additional, out int span, out int multiplicity)
        {
            if (!NonPeriodicFinite(parameter))
                throw new ArgumentOutOfRangeException(nameof(parameter), "The knot parameter must be finite.");
            if (this.GetType() != typeof(Spline) || this.isClosedPeriodic)
                throw new NotSupportedException("Knot refinement requires an ordinary nonperiodic SPLINE.");
            if (this.degree < 1 || this.degree > MaxDegree || this.controlPoints == null
                || this.weights == null || this.knots == null || this.fitPoints == null)
                throw new InvalidOperationException("The stored spline definition is incomplete.");
            if ((long)this.controlPoints.Length + additional > MaximumRefinedControlPoints)
                throw new NotSupportedException("The refined control-point budget would be exceeded.");
            if (this.controlPoints.Length <= this.degree || this.weights.Length != this.controlPoints.Length
                || (long)this.knots.Length != (long)this.controlPoints.Length + this.degree + 1)
                throw new InvalidOperationException("Spline degree, control, weight and knot counts must agree.");
            CurvePolylineConversion.CheckDependencies(this);
            CurvePolylineConversion.CheckNormal(base.Normal);
            foreach (Vector3 point in this.controlPoints) CurvePolylineConversion.CheckPoint(point);
            foreach (Vector3 point in this.fitPoints) CurvePolylineConversion.CheckPoint(point);
            if (this.startTangent.HasValue) CurvePolylineConversion.CheckPoint(this.startTangent.Value);
            if (this.endTangent.HasValue) CurvePolylineConversion.CheckPoint(this.endTangent.Value);
            foreach (double weight in this.weights)
                if (!NonPeriodicFinite(weight) || weight <= 0)
                    throw new NotSupportedException("Knot refinement requires finite strictly positive weights.");
            if (!NonPeriodicFinite(this.knotTolerance) || this.knotTolerance <= 0
                || !NonPeriodicFinite(this.ctrlPointTolerance) || this.ctrlPointTolerance <= 0
                || !NonPeriodicFinite(this.fitTolerance) || this.fitTolerance <= 0)
                throw new InvalidOperationException("Spline tolerances must be finite and positive.");
            int repeat = 0;
            multiplicity = 0;
            for (int i = 0; i < this.knots.Length; i++)
            {
                double knot = this.knots[i];
                if (!NonPeriodicFinite(knot) || (i > 0 && knot < this.knots[i - 1]))
                    throw new InvalidOperationException("Spline knots must be finite and nondecreasing.");
                repeat = i > 0 && knot == this.knots[i - 1] ? repeat + 1 : 1;
                if (repeat > this.degree + 1)
                    throw new InvalidOperationException("Stored knot multiplicity exceeds degree plus one.");
                if (knot == parameter) multiplicity++;
            }
            if (!(this.knots[this.degree] < parameter && parameter < this.knots[this.controlPoints.Length]))
                throw new ArgumentOutOfRangeException(nameof(parameter), "The knot must be strictly inside the active domain.");
            int low = this.degree, high = this.controlPoints.Length;
            while (low + 1 < high)
            {
                int middle = low + (high - low) / 2;
                if (parameter < this.knots[middle]) high = middle; else low = middle;
            }
            span = low;
        }

        private Spline CreateKnotResult(Vector3[] points, double[] resultWeights, double[] resultKnots,
            Vector3[] resultFits, SplineCreationMethod method, Vector3? firstTangent, Vector3? lastTangent)
        {
            var result = new Spline(points, resultWeights, resultKnots, this.degree, resultFits, method, false)
            {
                startTangent = firstTangent, endTangent = lastTangent,
                knotTolerance = this.knotTolerance, ctrlPointTolerance = this.ctrlPointTolerance,
                fitTolerance = this.fitTolerance, knotParameterization = this.knotParameterization
            };
            CurvePolylineConversion.CopyAppearance(this, result, base.Normal);
            return result;
        }
    }
}
