// Copyright (c) netDxf contributors. Licensed under the MIT License.
using System;
using System.Collections.Generic;

namespace netDxf.Entities
{
    public partial class Spline
    {
        /// <summary>Maximum sampled vertices generated by one polyline conversion.</summary>
        public const int MaximumConvertedVertices = CurvePolylineConversion.MaximumVertices;

        /// <summary>Projects sampled spline points onto an explicitly elevated object XY plane.</summary>
        /// <param name="precision">Number of samples, between two and MaximumConvertedVertices.</param>
        /// <param name="elevation">Finite signed offset of the output plane along the unit normal.</param>
        /// <returns>A detached unsmoothed polyline with independently copied ordinary appearance and XData.</returns>
        /// <remarks>
        /// Projection discards each sample's object Z coordinate and replaces it with elevation; it is not
        /// a planarity test. Sampling follows PolygonalVertexes. Source identities, fitted definitions,
        /// proxy graphics and unsupported dependency graphs are not copied onto the approximation.
        /// </remarks>
        public Polyline2D ToPolyline2D(int precision, double elevation)
        {
            CurvePolylineConversion.CheckElevation(elevation);
            List<Vector3> samples = this.PolylineConversionSamples(precision);
            return CurvePolylineConversion.Project(this, samples, base.Normal,
                this.IsClosed || this.isClosedPeriodic, elevation);
        }

        private Polyline3D ConvertToPolyline3D(int precision)
        {
            List<Vector3> samples = this.PolylineConversionSamples(precision);
            var result = new Polyline3D(samples, this.IsClosed || this.isClosedPeriodic);
            CurvePolylineConversion.CopyAppearance(this, result, base.Normal);
            return result;
        }

        private List<Vector3> PolylineConversionSamples(int precision)
        {
            if (precision < 2)
                throw new ArgumentOutOfRangeException(nameof(precision), precision, "At least two samples are required.");
            CurvePolylineConversion.CheckCount(precision, nameof(precision));
            CurvePolylineConversion.CheckDependencies(this);
            CurvePolylineConversion.CheckNormal(base.Normal);
            foreach (Vector3 point in this.controlPoints) CurvePolylineConversion.CheckPoint(point);
            foreach (Vector3 point in this.fitPoints) CurvePolylineConversion.CheckPoint(point);
            if (this.startTangent.HasValue) CurvePolylineConversion.CheckPoint(this.startTangent.Value);
            if (this.endTangent.HasValue) CurvePolylineConversion.CheckPoint(this.endTangent.Value);
            foreach (double weight in this.weights)
                if (double.IsNaN(weight) || double.IsInfinity(weight))
                    throw new InvalidOperationException("Polyline conversion requires finite spline weights.");
            for (int i = 0; i < this.knots.Length; i++)
                if (double.IsNaN(this.knots[i]) || double.IsInfinity(this.knots[i])
                    || (i > 0 && this.knots[i] < this.knots[i - 1]))
                    throw new InvalidOperationException("Polyline conversion requires finite nondecreasing spline knots.");
            List<Vector3> samples = this.PolygonalVertexes(precision);
            foreach (Vector3 point in samples) CurvePolylineConversion.CheckPoint(point);
            return samples;
        }
    }
}
