// Copyright (c) netDxf contributors. Licensed under the MIT License.
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.IO;
using System.Linq;
using netDxf.Blocks;
using netDxf.Header;
using netDxf.IO;

namespace netDxf.Entities
{
    /// <summary>A loaded ACAD_TABLE retaining its ordered subclass payload and source document dependencies.</summary>
    /// <remarks>
    /// This is stored table data, not a layout or formula engine. Unknown packets remain in Payload.
    /// Geometry, cells and backing objects cannot be regenerated by this model. Save uses the source
    /// DXF version and document. Cloning, geometric changes and reattachment after removal reject.
    /// Common entity appearance and XData retain their ordinary editable interfaces.
    /// </remarks>
    public sealed class StoredTable : EntityObject
    {
        private readonly DxfDocument source;
        private readonly IReadOnlyList<DxfTag> payload;
        private readonly Dictionary<string, DxfObject> handles = new Dictionary<string, DxfObject>(StringComparer.OrdinalIgnoreCase);
        private readonly List<DxfObject> references = new List<DxfObject>();
        private readonly Vector3 storedNormal;
        private Block displayBlock;
        private string displayName;
        private bool pending = true;
        private bool removed;

        internal StoredTable(DxfDocument source, IList<DxfTag> payload, Func<string, string> decode)
            : base(EntityType.StoredTable, DxfObjectCode.AcadTable)
        {
            this.source = source;
            this.SourceVersion = source.DrawingVariables.AcadVer;
            this.payload = new ReadOnlyCollection<DxfTag>(new List<DxfTag>(payload));
            int blockEnd = payload.ToList().FindIndex(t => t.Code == 100 && (string)t.Value == "AcDbTable");
            if (blockEnd < 0) blockEnd = payload.Count;
            var block = payload.Take(blockEnd).ToList();
            this.storedNormal = ReadVector(block, 210, Vector3.UnitZ);
            if (Vector3.IsZero(this.storedNormal)) throw new InvalidDataException("ACAD_TABLE has a zero normal.");
            base.Normal = this.storedNormal;
            this.Position = ReadVector(block, 10, Vector3.Zero);
            var names = block.Where(t => t.Code == 2).ToList();
            if (names.Count == 1) this.displayName = decode((string)names[0].Value);
            this.Grid = StoredTableGrid.TryRead(this.payload, decode, this.SourceVersion);
        }

        /// <summary>Gets the source DXF version; exporting to another version is not qualified.</summary>
        public DxfVersion SourceVersion { get; }
        /// <summary>Gets exact immutable subclass tags, including unknown packets, excluding common metadata and XData.</summary>
        public IReadOnlyList<DxfTag> Payload { get { return this.payload; } }
        /// <summary>Gets the stored insertion point in the source coordinate convention.</summary>
        public Vector3 Position { get; }
        /// <summary>Gets the validated flat cell projection, or null when the stored schema is not recognized.</summary>
        public StoredTableGrid Grid { get; }
        /// <summary>Gets registered semantic dependencies; arbitrary group 320–329 handles are excluded.</summary>
        public IReadOnlyList<DxfObject> References { get { return this.references.AsReadOnly(); } }
        /// <summary>Gets the source normal; changing geometry without regenerating backing data is not supported.</summary>
        public override Vector3 Normal
        {
            get { return this.storedNormal; }
            set
            {
                if (value.X != this.storedNormal.X || value.Y != this.storedNormal.Y || value.Z != this.storedNormal.Z)
                    throw new NotSupportedException("Stored TABLE normal changes require backing geometry regeneration.");
            }
        }
        internal void Resolve()
        {
            foreach (DxfTag tag in this.payload)
            {
                if (tag.Code < 330 || tag.Code > 369) continue;
                string handle = (string)tag.Value;
                DxfObject target = this.source.GetObjectByHandle(handle);
                if (target == null) continue;
                this.handles[handle] = target;
                this.references.Add(target);
            }
            if (this.displayName != null && this.source.Blocks.TryGetValue(this.displayName, out Block block))
            {
                this.displayBlock = block;
                this.references.Add(block.Record);
            }
            this.pending = false;
        }
        internal void ValidateIncoming(DxfDocument document)
        {
            if (this.removed) throw new InvalidOperationException("A removed stored TABLE cannot be reattached.");
            if (this.pending && document == null) return;
            if (!ReferenceEquals(document, this.source))
                throw new InvalidOperationException("A stored TABLE can only belong to its source document.");
            if (!this.pending) this.Validate(document);
        }
        internal void Validate(DxfDocument document)
        {
            if (this.pending || this.removed || !ReferenceEquals(document, this.source))
                throw new InvalidOperationException("The stored TABLE is detached or has unresolved input state.");
            if (document.DrawingVariables.AcadVer != this.SourceVersion)
                throw new NotSupportedException("Stored TABLE conversion between DXF versions requires schema regeneration.");
            foreach (var pair in this.handles)
                if (!ReferenceEquals(document.GetObjectByHandle(pair.Key), pair.Value))
                    throw new InvalidOperationException("A stored TABLE dependency is no longer registered: " + pair.Key);
            if (this.displayBlock != null && !ReferenceEquals(document.GetObjectByHandle(this.displayBlock.Record.Handle), this.displayBlock.Record))
                throw new InvalidOperationException("The stored TABLE display block is no longer registered.");
        }
        internal string ChangedDisplayName(DxfTag tag)
        {
            if (tag.Code != 2 || this.displayBlock == null || this.displayBlock.Name == this.displayName) return null;
            // Group 2 belongs to the first block-reference subclass only; later private names are left intact.
            int index = this.payload.IndexOfReference(tag);
            int boundary = this.payload.ToList().FindIndex(t => t.Code == 100 && (string)t.Value == "AcDbTable");
            return index < boundary ? this.displayBlock.Name : null;
        }
        internal void MarkRemoved() { this.removed = true; }
        /// <summary>Rejects copying a stored TABLE without its application-defined backing graph.</summary>
        public override object Clone() { throw new NotSupportedException("Stored TABLE cloning requires a complete application schema."); }
        /// <summary>Accepts only the exact identity transformation.</summary>
        public override void TransformBy(Matrix3 transformation, Vector3 translation)
        {
            for (int row = 0; row < 3; row++) for (int column = 0; column < 3; column++)
                if (transformation[row, column] != (row == column ? 1.0 : 0.0))
                    throw new NotSupportedException("Stored TABLE transforms require backing geometry regeneration.");
            if (translation.X != 0 || translation.Y != 0 || translation.Z != 0)
                throw new NotSupportedException("Stored TABLE transforms require backing geometry regeneration.");
        }
        /// <summary>Accepts only the exact four-by-four identity transformation.</summary>
        public override void TransformBy(Matrix4 transformation)
        {
            for (int row = 0; row < 4; row++) for (int column = 0; column < 4; column++)
                if (transformation[row, column] != (row == column ? 1.0 : 0.0))
                    throw new NotSupportedException("Stored TABLE transforms require backing geometry regeneration.");
        }
        private static Vector3 ReadVector(IList<DxfTag> tags, short code, Vector3 fallback)
        {
            var xs = tags.Where(t => t.Code == code).ToList();
            var ys = tags.Where(t => t.Code == code + 10).ToList();
            var zs = tags.Where(t => t.Code == code + 20).ToList();
            if (xs.Count + ys.Count + zs.Count == 0) return fallback;
            if (xs.Count != 1 || ys.Count != 1 || zs.Count != 1) throw new InvalidDataException("Incomplete or repeated TABLE vector.");
            return new Vector3((double)xs[0].Value, (double)ys[0].Value, (double)zs[0].Value);
        }
    }
    internal static class StoredTableTagList
    {
        internal static int IndexOfReference(this IReadOnlyList<DxfTag> tags, DxfTag target)
        { for (int i = 0; i < tags.Count; i++) if (ReferenceEquals(tags[i], target)) return i; return -1; }
    }
}
