import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { spawnSync } from 'node:child_process';
import { javascriptRoot } from './dotnet.mjs';
import { runtimeFingerprint, verificationFingerprint } from './evidence.mjs';
const proof={runtimeFingerprint:runtimeFingerprint(),verificationFingerprint:verificationFingerprint()};
const temp=fs.mkdtempSync(path.join(os.tmpdir(),'netdxf-package-'));
const npm=process.platform==='win32'?'npm.cmd':'npm';
function run(command,args,cwd){const r=spawnSync(command,args,{cwd,encoding:'utf8',shell:process.platform==='win32' && command===npm});if(r.status!==0)throw r.error||new Error(r.stdout+'\n'+r.stderr);return r.stdout;}
try {
  const [info]=JSON.parse(run(npm,['pack','--ignore-scripts','--json','--pack-destination',temp],javascriptRoot));
  if(!info.files.some(f=>f.path==='node-entry.js')) throw new Error('Packed Node entry is missing.');
  if(!info.files.some(f=>f.path==='Enums.generated.js')) throw new Error('Packed enum barrel is missing.');
  if(info.files.some(f=>/^artifacts\/|^tools\/|^tests\//.test(f.path) && !['tools/ReferenceMath/generate.py','tools/ReferenceMath/source-manifest.json','tools/ReferenceMath/generate-exp-log.py','tools/ReferenceMath/exp-log-manifest.json','tools/ReferenceMath/exp-log.template.js'].includes(f.path))) throw new Error('Development artifacts leaked into the runtime package.');
  for(const file of ['netDxf/GTE/LICENSE.BSL-1.0','THIRD_PARTY_NOTICES.md','runtime/reference-math/LICENSE.LGPL-2.1','runtime/reference-math/LICENSE.GPL-2','third_party/glibc-math/COPYING.LIB','third_party/glibc-math/sysdeps/ieee754/dbl-64/dla.h','tools/ReferenceMath/generate.py','tools/ReferenceMath/source-manifest.json','tools/ReferenceMath/generate-exp-log.py','tools/ReferenceMath/exp-log-manifest.json','tools/ReferenceMath/exp-log.template.js','runtime/reference-math/exp-log.js','runtime/reference-math/exp-log-data.js','runtime/reference-math/exp-log-source.json'])
    if(!info.files.some(f=>f.path===file)) throw new Error('Required mathematical source/notice is missing: '+file);
  const install=path.join(temp,'install');fs.mkdirSync(install);
  run(npm,['install','--offline','--ignore-scripts','--no-audit','--no-fund','--prefix',install,path.join(temp,info.filename)],install);
  const script=`import fs from 'node:fs';
    import {createHash} from 'node:crypto';
    import {DotNetMath} from '@netdxf/javascript/runtime/GeometryRuntime.js';
    const packageRoot=new URL('./node_modules/@netdxf/javascript/',import.meta.url);
    const pkg=JSON.parse(fs.readFileSync(new URL('package.json',packageRoot)));
    if(pkg.license!=='MIT AND LGPL-2.1-or-later AND BSL-1.0')throw new Error('Aggregate license metadata is wrong');
    const provenance=JSON.parse(fs.readFileSync(new URL('tools/ReferenceMath/source-manifest.json',packageRoot)));
    for(const [file,expected] of Object.entries(provenance.files))
      if(createHash('sha256').update(fs.readFileSync(new URL('third_party/glibc-math/'+file,packageRoot))).digest('hex')!==expected)throw new Error('Packaged preferred source drift: '+file);
    const expLogProvenance=JSON.parse(fs.readFileSync(new URL('tools/ReferenceMath/exp-log-manifest.json',packageRoot)));
    const runtimeProvenance=JSON.parse(fs.readFileSync(new URL('runtime/reference-math/exp-log-source.json',packageRoot)));
    if(JSON.stringify(expLogProvenance)!==JSON.stringify(runtimeProvenance))throw new Error('Packaged exp/log source manifests disagree');
    for(const [file,expected] of Object.entries(expLogProvenance.files))
      if(createHash('sha256').update(fs.readFileSync(new URL('third_party/glibc-math/'+file,packageRoot))).digest('hex')!==expected)throw new Error('Packaged exp/log preferred source drift: '+file);
    if(DotNetMath.Exp(-745)!==Number.MIN_VALUE||DotNetMath.Log(1)!==0)throw new Error('Packed exp/log runtime failed');
    if(DotNetMath.Sin(-0.20148213487118483)!==-0.2001217029035577)throw new Error('Packed reference math failed');
    import {Layout,Viewport,Block,Insert,AttributeDefinition,MLine,MLineStyle,MLineStyleElement,PlotSettings,PaperMargin,DxfPlotSettingsObject,DxfWipeoutVariables,RasterVariables,Group,Line,Hatch,HatchBoundaryPath,HatchPattern,Circle,Vector2,DxfRawDocument,DxfRawObjectStore,DxfTag,Vector3,Matrix3,AciColor,ObservableCollection,DxfClass,DxfClassCollection,ApplicationRegistry,XData,XDataRecord,XDataCode} from '@netdxf/javascript';
    const block=new Block('PACKED_BLOCK',[new Line(Vector3.Zero,Vector3.UnitX)],[new AttributeDefinition('TAG')]);
    const insertion=new Insert(block);insertion.ColumnCount=3;insertion.ColumnSpacing=4;
    if(insertion.Explode().Count!==6||insertion.GetGridPosition(0,2).X!==8)throw new Error('Packed INSERT array failed');
    const insertionCopy=insertion.Clone();
    if(insertionCopy.Block===block||insertionCopy.Attributes.get_Item(0)===insertion.Attributes.get_Item(0)||insertionCopy.Block.Entities.get_Item(0).Owner!==insertionCopy.Block)throw new Error('Packed block/INSERT ownership failed');
    const sheet=new Layout('PACKED_SHEET');sheet.TabOrder=1;
    const paperViewport=new Viewport(new Circle(Vector3.Zero,2));sheet.Viewport=paperViewport;
    paperViewport.TransformBy(Matrix3.Identity,new Vector3(4,5,0));
    const sheetCopy=sheet.Clone('PACKED_COPY');
    if(sheetCopy.Viewport===paperViewport||sheetCopy.Viewport.ClippingBoundary===paperViewport.ClippingBoundary||sheetCopy.AssociatedBlock!==null||sheetCopy.Viewport.Width!==4||sheetCopy.Viewport.Center.X!==4)throw new Error('Packed layout/viewport clone or clipping geometry failed');
    if(Layout.ModelSpace.Viewport!==null)throw new Error('Packed model layout created a paper viewport');
    const multilineStyle=new MLineStyle('PACKED_MLINE');
    const multiline=new MLine([Vector2.Zero,new Vector2(10,0)],multilineStyle,2);
    if(multiline.Explode().Count!==2)throw new Error('Packed multiline geometry failed');
    const multilineCopy=multiline.Clone();multilineCopy.Vertexes.get_Item(0).Distances[0].Clear();
    if(multiline.Vertexes.get_Item(0).Distances[0].Count!==2||multilineCopy.Style===multilineStyle)throw new Error('Packed multiline clone isolation failed');
    const nanElement=new MLineStyleElement(NaN);multilineStyle.Elements.Add(nanElement);
    if(multilineStyle.Elements.Contains(nanElement))throw new Error('Packed multiline non-reflexive equality failed');
    const settings=new PlotSettings();settings.StandardScaleType=25;settings.ScaleToFit=false;settings.StandardScaleFactor=-0;
    settings.PaperMargin=new PaperMargin(1,2,3,4);const page=new DxfPlotSettingsObject(settings);settings.PaperMargin.Left=99;
    if(page.Settings.StandardScaleType!==25||!Object.is(page.Settings.StandardScaleFactor,-0)||page.Settings.PaperMargin.Left!==1)throw new Error('Packed plot settings value state failed');
    const wipeout=new DxfWipeoutVariables();wipeout.DisplayFrame=true;
    if(!wipeout.CloneShell().DisplayFrame||new RasterVariables(null).DisplayQuality!==1)throw new Error('Packed output variables failed');
    const grouped=new Line(Vector3.Zero,Vector3.UnitX),group=new Group('GROUP',[grouped]),groupCopy=group.Clone('COPY');
    if(groupCopy.Entities.get_Item(0)===grouped||grouped.Reactors.get_Item(0)!==group)throw new Error('Packed group clone/reactor behavior failed');
    group.Entities.Clear();if(grouped.Reactors.Count!==0)throw new Error('Packed group unlink failed');
    const hatchSource=new Circle(Vector3.Zero,2), hatchPath=new HatchBoundaryPath([hatchSource]);
    const hatch=new Hatch(HatchPattern.Solid,[hatchPath],true);hatch.SeedPoints.Add(new Vector2(3,4));hatch.PixelSize=null;
    hatch.TransformBy(Matrix3.Identity,Vector3.Zero);
    if(hatch.Associative||hatchSource.Reactors.Count||hatchPath.Entities.Count||hatch.BoundaryPaths.get_Item(0)!==hatchPath)throw new Error('Packed HATCH identity unlink failed');
    const hatchClone=hatch.Clone();hatchClone.TransformBy(Matrix3.Scale(2,3,1),new Vector3(5,7,0));
    if(!(hatchClone.BoundaryPaths.get_Item(0).Edges.get_Item(0) instanceof HatchBoundaryPath.Ellipse)||hatchClone.PixelSize!==null)throw new Error('Packed HATCH affine conversion failed');
    if(hatchClone.SeedPoints.get_Item(1).X!==11||hatchClone.SeedPoints.get_Item(1).Y!==19||hatch.SeedPoints.get_Item(1).X!==3)throw new Error('Packed HATCH seed clone isolation failed');
    if(hatchClone.CreateBoundary(false).Count!==1)throw new Error('Packed HATCH boundary conversion failed');
    const registry=new ApplicationRegistry('REGISTRY'),data=new XData(registry);
    data.XDataRecord.Add(new XDataRecord(XDataCode.BinaryData,Uint8Array.of(1,2)));registry.XData.Add(data);
    const clone=registry.Clone('COPY');if(clone.XData.get_Item('COPY').ApplicationRegistry!==clone)throw new Error('Packed cyclic registry clone failed');
    clone.Name='RENAMED';if(!clone.XData.ContainsAppId('RENAMED'))throw new Error('Packed registry binding failed');
    const tags=[[0,'SECTION'],[2,'HEADER'],[9,'$ACADVER'],[1,'AC1032'],[0,'ENDSEC'],[0,'EOF']].map(([c,v])=>new DxfTag(c,v));
    const tx=DxfRawObjectStore.Open(DxfRawDocument.Create(tags)).BeginEdit();
    const root=tx.EnsureRootDictionary();tx.CreateVariable(root,'Test','Zażółć 東京');
    const result=DxfRawObjectStore.Open(DxfRawDocument.Load(tx.Commit().ToBytes(true)));
    if(result.Get(result.RootDictionary.Find('test').Handle).Value!=='Zażółć 東京')throw new Error('Packed round trip failed');
    if(Vector3.Normalize(new Vector3(3,4,0)).X!==0.6000000000000001)throw new Error('Packed geometry failed');
    const classes=new DxfClassCollection();classes.Add(new DxfClass('Name','Cpp','App'));
    if(classes.get_Item('Name').CppClassName!=='Cpp')throw new Error('Packed classes failed');
    const collection=new ObservableCollection();collection.Add(3);collection.Insert(0,2);
    if(collection.get_Item(0)!==2)throw new Error('Packed collection failed');`;
  run(process.env.PYTHON||'python',['tools/ReferenceMath/generate-exp-log.py','--check'],path.join(install,'node_modules','@netdxf','javascript'));
  run(process.execPath,['--input-type=module','-e',script],install);
  run(process.execPath,['--input-type=module','-e',`import fs from 'node:fs';
    import {DxfRawDocument,DxfTag,FileStream,UnitHelper,XDataRecord,XDataCode} from '@netdxf/javascript/node';
    const tags=[[0,'SECTION'],[2,'HEADER'],[9,'$ACADVER'],[1,'AC1032'],[0,'ENDSEC'],[0,'EOF']].map(([c,v])=>new DxfTag(c,v));
    const raw=DxfRawDocument.Create(tags);raw.SaveAtomic('packed.dxf');
    const stream=new FileStream('packed.dxf');try{raw.SaveAtomic('packed.dxf');if(DxfRawDocument.Load(stream).Version!==18)throw new Error('Atomic packed read failed');}finally{stream.Dispose();fs.unlinkSync('packed.dxf');}
    if(typeof UnitHelper.ConversionFactor!=='function'||new XDataRecord(XDataCode.Int16,12).Value!==12)throw new Error('Recovered exports missing');`],install);
  const dir=path.join(javascriptRoot,'artifacts/package');fs.mkdirSync(dir,{recursive:true});
  fs.writeFileSync(path.join(dir,'results.json'),JSON.stringify({...proof,completed:true,private:true,files:info.files.length,packedBytes:info.size,unpackedBytes:info.unpackedSize},null,2)+'\n');
  console.log(`Packed-package offline import and binary object round trip passed (${info.files.length} files).`);
} finally {fs.rmSync(temp,{recursive:true,force:true});}
