// Port of all original cases/assertions in pinned AttributeDefaultValueTests.cs.
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { DxfDocument, DxfRawDocument, Block, Insert, AttributeDefinition, Attribute, TextStyle, Line, Vector3, MemoryStream } from '../../index.js';
import { ArgumentNullException, InvalidOperationException } from '../../runtime/Errors.js';
import { Run, Check, Equal, Throws, SupportedVersions, VersionName, BooleanName } from './TestHarness.js';
const artifactDirectory=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../../artifacts/conformance/fixtures');
const single=items=>{const rows=Array.from(items);Equal(1,rows.length,'Expected exactly one item');return rows[0];};
export function RegisterAttributeDefaultValueTests(){Run('attribute-default/api',AttributeDefaultApi);for(const v of SupportedVersions)for(const b of [false,true]){Run(`attribute-default/roundtrip/${VersionName(v)}/${BooleanName(b)}`,()=>AttributeDefaultRoundTrip(v,b));Run(`attribute-default/omitted-reader/${VersionName(v)}/${BooleanName(b)}`,()=>AttributeDefaultOmitted(v,b));}}
export function AttributeDefaultApi(){for(const definition of [new AttributeDefinition('TAG'),new AttributeDefinition('TAG',TextStyle.Default),new AttributeDefinition('TAG',2,TextStyle.Default)]){
  Equal('',definition.Value,'New ATTDEF must have a valid empty value');Equal('',definition.Prompt,'New ATTDEF must have a valid empty prompt');definition.Prompt='kept prompt';Equal('kept prompt',definition.Clone().Prompt,'ATTDEF clone prompt');definition.Prompt=null;Equal('',definition.Prompt,'Null prompt assignment semantics');Equal('',definition.Clone().Prompt,'ATTDEF clone normalized prompt');Equal('',new Attribute(definition).Value,'New ATTRIB must inherit a valid empty value');Equal('',definition.Clone().Value,'ATTDEF clone default');
  const attribute=new Attribute(definition);Equal('',attribute.Clone().Value,'ATTRIB clone default');definition.Value='value';attribute.Value='override';definition.Value=null;attribute.Value=null;Equal('',definition.Value,'Null ATTDEF assignment semantics');Equal('',attribute.Value,'Null ATTRIB assignment semantics');definition.Value='  padded  ';attribute.Value='   ';Equal('  padded  ',definition.Value,'ATTDEF whitespace must not be trimmed');Equal('   ',attribute.Value,'ATTRIB whitespace must not be trimmed');}
  Throws(ArgumentNullException,()=>new AttributeDefinition(null));Throws(ArgumentNullException,()=>new AttributeDefinition(''));Throws(ArgumentNullException,()=>new Attribute(null));
  for(const args of [['TAG',null],['TAG',2,null]]){try{new AttributeDefinition(...args);throw new InvalidOperationException('Null attribute style accepted.');}catch(error){Check(error instanceof ArgumentNullException,'Expected null style error');Equal('style',error.ParamName,'Null style parameter name');}}
  const automatic=new TextStyle('ATTRIBUTE_AUTO','txt.shx'),fixed=new TextStyle('ATTRIBUTE_FIXED','txt.shx');automatic.Height=0;fixed.Height=2.5;Equal(1,new AttributeDefinition('TAG',automatic).Height,'Zero style height default');Equal(2.5,new AttributeDefinition('TAG',fixed).Height,'Fixed style height inheritance');Equal(4,new AttributeDefinition('TAG',4,fixed).Height,'Explicit attribute height');
  const block=new Block('ATTRIBUTE_SYNC'),insert=new Insert(block);block.AttributeDefinitions.Add(new AttributeDefinition('NEW_TAG'));insert.Sync();Equal('',single(insert.Attributes).Value,'Synced ATTRIB inherited null');const clone=insert.Clone();Equal('',single(clone.Attributes).Value,'INSERT clone default ATTRIB');Equal('',clone.Block.AttributeDefinitions.get_Item('NEW_TAG').Value,'Block clone default ATTDEF');
}
export function AttributeDefaultDocument(version,mode){const document=new DxfDocument(version),block=new Block('ATTRIBUTE_DEFAULT'),definition=new AttributeDefinition('TAG'),value=mode===1?null:mode===2?'':mode===3?'retained value':'   ';if(mode!==0){definition.Value=value;definition.Prompt=value;}block.AttributeDefinitions.Add(definition);const insert=new Insert(block);if(mode!==0)single(insert.Attributes).Value=value;document.Entities.Add(insert);document.Entities.Add(new Line(new Vector3(1,2,3),new Vector3(4,5,6)));return document;}
export function AttributeDefaultAssert(document,definition,attribute,prompt){const insert=single(document.Entities.Inserts),att=single(insert.Attributes);Equal(definition,insert.Block.AttributeDefinitions.get_Item('TAG').Value,'Loaded ATTDEF value');Equal(attribute,att.Value,'Loaded ATTRIB value');Equal(prompt,insert.Block.AttributeDefinitions.get_Item('TAG').Prompt,'Loaded ATTDEF prompt');Equal('TAG',att.Tag,'ATTRIB tag changed');Check(new Vector3(1,2,3).Equals(single(document.Entities.Lines).StartPoint),'Following LINE changed');}
export function AttributeDefaultRoundTrip(version,binary){for(let mode=0;mode<5;mode++){let document=AttributeDefaultDocument(version,mode);const expected=mode<3?'':mode===3?'retained value':'   ';AttributeDefaultAssert(document,expected,expected,expected);
  for(let cycle=0;cycle<2;cycle++){const output=new MemoryStream();try{Check(document.Save(output,cycle===0?binary:!binary),'Attribute default save failed.');output.Position=0;const raw=DxfRawDocument.Load(output),records=Array.from(raw.Sections).flatMap(s=>Array.from(s.Records)).filter(r=>r.Name==='ATTDEF'||r.Name==='ATTRIB');Equal(2,records.length,'Expected ATTDEF and ATTRIB records');for(const record of records){Equal(expected,single(Array.from(record.Tags).filter(t=>t.Code===1)).Value,'Explicit attribute text field');if(record.Name==='ATTDEF')Equal(expected,single(Array.from(record.Tags).filter(t=>t.Code===3)).Value,'Explicit prompt text field');}
    if(mode===0&&cycle===0){fs.mkdirSync(artifactDirectory,{recursive:true});fs.writeFileSync(path.join(artifactDirectory,`attribute-default-${VersionName(version)}-${BooleanName(binary)}.dxf`),output.ToArray());}
    output.Position=0;document=DxfDocument.Load(output);if(!document)throw new InvalidOperationException('Attribute default reload failed.');AttributeDefaultAssert(document,expected,expected,expected);Check(output.CanRead,'Attribute roundtrip closed caller stream.');
  }finally{output.Dispose();}}}}
export function AttributeDefaultOmitted(version,binary){const original=AttributeDefaultDocument(version,3),source=new MemoryStream();try{Check(original.Save(source,binary),'Attribute omission source save failed.');source.Position=0;const raw=DxfRawDocument.Load(source);
  for(const omitFrom of ['ATTDEF','ATTRIB','PROMPT']){let active='';const tags=[];for(const tag of raw.Tags){if(tag.Code===0)active=tag.Value;const omitted=omitFrom==='PROMPT'?active==='ATTDEF'&&tag.Code===3:active===omitFrom&&tag.Code===1;if(!omitted)tags.push(tag);}
    const changed=new MemoryStream(),output=new MemoryStream();try{DxfRawDocument.Create(tags,binary).Save(changed);changed.Position=0;const loaded=DxfDocument.Load(changed);if(!loaded)throw new InvalidOperationException('Omitted attribute value load failed.');AttributeDefaultAssert(loaded,omitFrom==='ATTDEF'?'':'retained value',omitFrom==='ATTRIB'?'':'retained value',omitFrom==='PROMPT'?'':'retained value');Check(loaded.Save(output,!binary),'Normalized omitted attribute save failed.');output.Position=0;const normalized=DxfRawDocument.Load(output),record=single(Array.from(normalized.Sections).flatMap(s=>Array.from(s.Records)).filter(r=>r.Name===(omitFrom==='PROMPT'?'ATTDEF':omitFrom)));Equal('',single(Array.from(record.Tags).filter(t=>t.Code===(omitFrom==='PROMPT'?3:1))).Value,'Omitted attribute must materialize existing empty-string default');}finally{changed.Dispose();output.Dispose();}}
}finally{source.Dispose();}}
