// Complete port of pinned CompositeTableOwnershipTests.cs. Private reflection
// hooks map to existing internal JavaScript methods/properties, not replacement models.
import fs from 'node:fs';
import path from 'node:path';
import { gunzipSync } from 'node:zlib';
import { createHash } from 'node:crypto';
import { sourceRoot } from '../../tools/dotnet.mjs';
import { DxfDocument, DxfVersion, DxfRawDocument, DxfTag, MemoryStream, DxfXRecord, DxfDataTable, DxfOpaqueObject, XData, XDataRecord, XDataCode, ApplicationRegistry } from '../../node-entry.js';
import { ArgumentException, FormatException, InvalidOperationException, NotSupportedException } from '../../runtime/Errors.js';
import { Run, Check, Equal, Throws, BooleanName } from './TestHarness.js';
import { OleSingle, OleWriteArtifact } from './Ole2FrameTests.js';
import { OwnershipTagValues } from './SunTests.js';
import { SourceReferenceDecoy, SourceReferenceRejectMalformedEntity } from './SourceReferenceIdentityTests.js';
const A=x=>Array.from(x),T=(c,v)=>new DxfTag(c,v),objects=raw=>A(OleSingle(A(raw.Sections).filter(s=>s.Name==='OBJECTS')).Records),children=value=>A(value.DeclaredOwnedObjects);
export function RegisterCompositeTableOwnershipTests(){for(const b of [false,true]){for(const h of ['13DF','13F2'])Run(`composite-table/native/${h}/${BooleanName(b)}`,()=>CompositeTableNative(h,b));Run('composite-table/reversed-order/'+BooleanName(b),()=>CompositeTableOrder(b));for(const v of ['wrong-content','wrong-geometry','wrong-table','null-table','absent-table','wrong-owner','undeclared-child','cycle'])Run(`composite-table/malformed/${v}/${BooleanName(b)}`,()=>CompositeTableMalformed(v,b));for(const v of ['private-marker','reordered-markers','extra-marker','trailing-value','duplicate-owner-slot','missing-cell','unknown-scalar-code','missing-section'])Run(`composite-table/unbound/${v}/${BooleanName(b)}`,()=>CompositeTableUnknown(v,b));for(const d of ['absent','unknown-entity','discarded-underlay','dictionary-entity','ignored-section'])Run(`composite-table/source-identity/${d}/${BooleanName(b)}`,()=>CompositeTableSourceIdentity(d,b));}Run('composite-table/bind-atomicity',CompositeTableBindAtomicity);}
export const CompositeTableRecord=(raw,handle)=>OleSingle(objects(raw).filter(r=>A(r.Tags).some(t=>t.Code===5&&t.Value===handle)));
export function CompositeTablePayload(record){const t=A(record.Tags),start=t.findIndex(t=>t.Code===100),out=[];for(let i=start;i<t.length&&t[i].Code!==1001;i++)out.push(t[i]);return out;}
function readRaw(bytes){const s=new MemoryStream(new Uint8Array(bytes));try{return DxfRawDocument.Load(s);}finally{s.Dispose();}}
export function CompositeTableSource(){const file='sample_AC1018_ascii.dxf',bytes=gunzipSync(fs.readFileSync(path.join(sourceRoot,'tests/fixtures/table-oracle',file+'.gz'))),inventory=JSON.parse(fs.readFileSync(path.join(sourceRoot,'tools/table_oracle/fixtures.json'),'utf8')),expected=OleSingle(inventory.files.filter(v=>v.file===file)).sha256;Equal(expected,createHash('sha256').update(bytes).digest('hex'),'composite source hash');return readRaw(bytes);}
// Exact shared StoredTableContentTests.TableContentSourceBytes fixture selection.
export function TableContentSourceBytes(file){const manifest=JSON.parse(fs.readFileSync(path.join(sourceRoot,'tests/fixtures/table-content/manifest.json'),'utf8')),fixture=OleSingle(manifest.files.filter(f=>f.file===file)),name=path.join(sourceRoot,'tests/fixtures/table-content',fixture.fixture),source=fs.readFileSync(name),bytes=name.endsWith('.gz')?gunzipSync(source):source;Equal(fixture.sha256??fixture.source_sha256,createHash('sha256').update(bytes).digest('hex'),'TABLECONTENT pinned source/carrier hash');return new Uint8Array(bytes);}
export function CompositeTableCarrier(wrapperHandle){const source=CompositeTableSource(),wrapper=CompositeTableRecord(source,wrapperHandle),handles=[wrapperHandle,...CompositeTablePayload(wrapper).filter(t=>t.Code===360||t.Code===361).map(t=>t.Value)],table=CompositeTableRecord(source,handles[3]);handles.push(...CompositeTablePayload(table).filter(t=>t.Code===360).map(t=>t.Value));let raw=readRaw(TableContentSourceBytes('sample_AC1018_ascii.dxf'));const w=CompositeTableRecord(raw,wrapperHandle),t=A(w.Tags),root=t.slice(0,t.findIndex(t=>t.Code===100)).filter(t=>t.Code===330).at(-1).Value,dictionary=CompositeTableRecord(raw,root);raw=raw.WithRecord(dictionary,[...dictionary.Tags,T(3,'NATIVE_COMPOSITE'),T(360,wrapperHandle)]);return {Carrier:raw,Source:source,Root:root,Handles:handles};}
function CompositeTableTryLoad(raw,b){const s=new MemoryStream();try{DxfRawDocument.Create(raw.Tags,b).Save(s);s.Position=0;return DxfDocument.Load(s);}finally{s.Dispose();}}
function CompositeTableLoad(raw,b){const doc=CompositeTableTryLoad(raw,b);Check(doc!==null,'Composite TABLE load failed.');return doc;}
function CompositeTableReject(raw,b){let rejected;try{rejected=CompositeTableTryLoad(raw,b)===null;}catch(e){if(!(e instanceof FormatException))throw e;rejected=true;}Check(rejected,'A malformed composite TABLE ownership graph loaded');}
function CompositeTableNative(h,b){const f=CompositeTableCarrier(h),doc=CompositeTableLoad(f.Carrier,b),wrapper=doc.GetObjectByHandle(h),table=doc.GetObjectByHandle(f.Handles[3]);Check(wrapper instanceof DxfXRecord&&table instanceof DxfDataTable,'Native composite types');Check(wrapper.IsSchemaManaged,'native composite wrapper is unbound');Equal(15,wrapper.Data.Count,'native wrapper tag count');Equal(f.Handles.slice(1,4),children(wrapper).map(c=>c.Handle),'composite direct child order');Equal(h==='13DF'?21:20,table.RowCount,'native DATATABLE row count');Equal(f.Handles.slice(4),children(table).map(c=>c.Handle),'native DATATABLE owned child sequence');for(const handle of f.Handles.slice(1))Equal(f.Handles.slice(1,4).includes(handle)?h:table.Handle,doc.GetObjectByHandle(handle).Owner.Handle,'composite reciprocal owner');Equal(0,doc.Objects.Validate().Count,'composite validation');const seed=doc.NumHandles,count=doc.Objects.Items.Count;for(const change of [()=>wrapper.Data.Add(T(1,'new')),()=>wrapper.Data.set_Item(14,T(360,'FFFFFF')),()=>wrapper.Data.Clear()])Throws(InvalidOperationException,change);Equal(seed,doc.NumHandles,'composite rejected edit reserved handle');Throws(NotSupportedException,()=>doc.Objects.EraseOwnedTree(wrapper));const dest=new DxfDocument(DxfVersion.AutoCad2004),destCount=dest.Objects.Items.Count,destSeed=dest.NumHandles;Throws(NotSupportedException,()=>dest.Objects.Clone(doc.GetObjectByHandle(f.Root),dest.Objects.Root,'COPY'));Equal(destSeed,dest.NumHandles,'opaque descendant clone allocated');Equal(destCount,dest.Objects.Items.Count,'opaque descendant clone registered');Throws(ArgumentException,()=>dest.Objects.Root.Add('FOREIGN',wrapper));Equal(destSeed,dest.NumHandles,'foreign composite adoption allocated');Check(f.Handles.every(h=>!doc.GetObjectByHandle(h).IsErased),'rejected erasure changed descendants');Equal(count,doc.Objects.Items.Count,'rejected erasure changed database count');CompositeTableSave(doc,f.Source,f.Handles,h,b,'native');const data=new XData(new ApplicationRegistry('COMPOSITE_TEST'));data.XDataRecord.Add(new XDataRecord(XDataCode.String,'common metadata only'));wrapper.XData.Add(data);CompositeTableSave(doc,f.Source,f.Handles,h,b,'edited');OleWriteArtifact(`composite-table-${h}-${BooleanName(b)}-map.json`,new TextEncoder().encode(JSON.stringify({source:'sample_AC1018_ascii.dxf',wrapper:h,sourceOwner:h==='13DF'?'13DE':'13F1',carrierOwner:f.Root,content:f.Handles[1],geometry:f.Handles[2],dataTable:f.Handles[3],rowObjects:f.Handles.slice(4)})));}
function CompositeTableSave(doc,source,handles,wrapper,b,phase){const bytes=new MemoryStream();try{Check(doc.Save(bytes,b),'composite output save');OleWriteArtifact(`composite-table-${wrapper}-${BooleanName(b)}-${phase}.dxf`,bytes.ToArray());bytes.Position=0;const raw=DxfRawDocument.Load(bytes);for(const h of handles)Equal(OwnershipTagValues(CompositeTablePayload(CompositeTableRecord(source,h))),OwnershipTagValues(CompositeTablePayload(CompositeTableRecord(raw,h))),'native composite subclass packet differs at '+h);bytes.Position=0;const loaded=DxfDocument.Load(bytes);Check(loaded.GetObjectByHandle(wrapper).IsSchemaManaged,'composite ownership lost on reload');Equal(0,loaded.Objects.Validate().Count,'composite reload validation');}finally{bytes.Dispose();}}
function CompositeTableOrder(b){const f=CompositeTableCarrier('13DF'),raw=f.Carrier,section=OleSingle(A(raw.Sections).filter(s=>s.Name==='OBJECTS')),records=A(section.Records),start=records[0].StartTagIndex,end=section.EndTagIndex-1,native=records.filter(r=>A(r.Tags).some(t=>t.Code===5&&f.Handles.includes(t.Value))),prefix=records.filter(r=>!native.includes(r)),all=A(raw.Tags),reordered=raw.WithTags([...all.slice(0,start),...[...prefix,...native.reverse()].flatMap(r=>A(r.Tags)),...all.slice(end)]),doc=CompositeTableLoad(reordered,b);Check(doc.GetObjectByHandle('13DF').IsSchemaManaged,'composite object order changed binding');Equal(0,doc.Objects.Validate().Count,'reversed composite graph validation');}
function CompositeTableMalformed(v,b){const f=CompositeTableCarrier('13DF');let raw=f.Carrier,wrapper=CompositeTableRecord(raw,'13DF');const t=A(wrapper.Tags),first=t.findIndex(t=>t.Code===102&&t.Value==='ACAD_ROUNDTRIP_2008_TABLE_ENTITY');if(v==='wrong-content')t[first+1]=T(360,'143D');if(v==='wrong-geometry')t[first+9]=T(361,'143D');if(v==='wrong-table')t[first+14]=T(360,'747');if(v==='null-table')t[first+14]=T(360,'0');if(v==='absent-table')t[first+14]=T(360,'FFFFFF');raw=raw.WithRecord(wrapper,t);if(v==='wrong-owner'){const table=CompositeTableRecord(raw,'143D');raw=raw.WithRecord(table,A(table.Tags).map(t=>t.Code===330?T(330,f.Root):t));}if(v==='undeclared-child'){const boundary=OleSingle(A(raw.Sections).filter(s=>s.Name==='OBJECTS')).EndTagIndex-1,all=A(raw.Tags);raw=raw.WithTags([...all.slice(0,boundary),T(0,'XRECORD'),T(5,'FFFFFF'),T(330,'13DF'),T(100,'AcDbXrecord'),T(280,1),T(1,'unlisted'),...all.slice(boundary)]);}if(v==='cycle'){wrapper=CompositeTableRecord(raw,'13DF');raw=raw.WithRecord(wrapper,A(wrapper.Tags).map(t=>t.Code===330?T(330,'143D'):t));}CompositeTableReject(raw,b);}
function CompositeTableUnknown(v,b){const f=CompositeTableCarrier('13DF');let raw=f.Carrier;const wrapper=CompositeTableRecord(raw,'13DF'),t=A(wrapper.Tags),first=t.findIndex(t=>t.Code===102&&t.Value==='ACAD_ROUNDTRIP_2008_TABLE_ENTITY');if(v==='private-marker')t[first+10]=T(102,'PRIVATE_TABLE');if(v==='reordered-markers')[t[first+10],t[first+13]]=[t[first+13],t[first+10]];if(v==='extra-marker')t.push(T(102,'PRIVATE_TAIL'));if(v==='trailing-value')t.push(T(1,'tail'));if(v==='duplicate-owner-slot')t.push(T(360,'143D'));if(v==='missing-cell')t.splice(first+14,1);if(v==='unknown-scalar-code')t[first+11]=T(92,7);if(v==='missing-section')t.splice(first+10,3);raw=raw.WithRecord(wrapper,t);const doc=CompositeTableLoad(raw,b),result=doc.GetObjectByHandle('13DF');Check(!result.IsSchemaManaged,'unknown composite grammar became bound');const bytes=new MemoryStream();try{Check(doc.Save(bytes,b),'unknown composite save');bytes.Position=0;const saved=DxfRawDocument.Load(bytes);Equal(OwnershipTagValues(CompositeTablePayload(CompositeTableRecord(raw,'13DF'))),OwnershipTagValues(CompositeTablePayload(CompositeTableRecord(saved,'13DF'))),'unknown composite payload changed');}finally{bytes.Dispose();}}
function CompositeTableSourceIdentity(decoy,b){const f=CompositeTableCarrier('13DF');let raw=f.Carrier;const missing=OleSingle(A(OleSingle(A(OleSingle(A(raw.Sections).filter(s=>s.Name==='HEADER')).Records).filter(r=>r.Name==='$HANDSEED')).Tags).filter(t=>t.Code===5)).Value,wrapper=CompositeTableRecord(raw,'13DF'),t=A(wrapper.Tags);t[t.findLastIndex(t=>t.Code===360)]=T(360,missing);raw=SourceReferenceDecoy(raw.WithRecord(wrapper,t),missing,decoy);if(['unknown-entity','dictionary-entity'].includes(decoy))SourceReferenceRejectMalformedEntity(raw,b);else CompositeTableReject(raw,b);}
function CompositeTableBindAtomicity(){const wrapper=new DxfXRecord();for(const t of [T(102,'ACAD_ROUNDTRIP_2008_TABLE_ENTITY'),T(360,'0'),T(70,2),T(90,1),T(10,0),T(20,0),T(30,0),T(90,0),T(90,2),T(361,'0'),T(102,'ACAD_ROUNDTRIP_PRE2007_TABLE'),T(90,7),T(91,3),T(102,'ACAD_ROUNDTRIP_PRE2007_TABLECELL'),T(360,'0')])wrapper.Data.Add(t);const content=new DxfOpaqueObject('TABLECONTENT',[T(100,'PrivateOwnershipTableContent'),T(90,0)]),geometry=new DxfOpaqueObject('TABLEGEOMETRY',[T(100,'PrivateOwnershipTableGeometry'),T(90,0)]),data=new DxfDataTable(),foreign=new DxfDocument(DxfVersion.AutoCad2004);foreign.Objects.Root.Add('DATA',data);const seed=foreign.NumHandles;Throws(ArgumentException,()=>wrapper.BindCompositeTableRoundtripChildren(content,geometry,data));Check(!wrapper.IsSchemaManaged&&content.Owner===null&&geometry.Owner===null,'late invalid child partially bound composite graph');Check(data.Owner===foreign.Objects.Root,'rejected binding changed foreign owner');Equal(seed,foreign.NumHandles,'rejected binding allocated handles');}
