// Complete port of pinned GeoDataTests.cs; source vectors are compared by value.
import fs from 'node:fs';
import path from 'node:path';
import { sourceRoot } from '../../tools/dotnet.mjs';
import { DxfDocument, DxfVersion, DxfGeoData, DxfGeoCoordinateType, DxfGeoScaleEstimation, DxfGeoMeshPoint, DxfGeoMeshFace, DxfDictionary, DxfXRecord, DxfOpaqueObject, Block, Vector2, Vector3, DrawingUnits, XData, XDataRecord, XDataCode, ApplicationRegistry, MemoryStream, DxfRawDocument, DxfTag } from '../../node-entry.js';
import { ArgumentException, ArgumentNullException, ArgumentOutOfRangeException, InvalidOperationException, NotSupportedException, IOException, FormatException } from '../../runtime/Errors.js';
import { Run, Check, Equal, Throws, VersionName } from './TestHarness.js';
import { OleSingle, OleRecords, OleWriteArtifact } from './Ole2FrameTests.js';
const T=(c,v)=>new DxfTag(c,v),vector=(a,b,m)=>Check(a.Equals(b),m),load=s=>{const d=DxfDocument.Load(s);Check(d!==null,'GEODATA load failed.');return d;};
export function RegisterGeoDataTests(){
  for(const v of [DxfVersion.AutoCad2010,DxfVersion.AutoCad2013,DxfVersion.AutoCad2018])for(const b of [false,true]){const suffix=`${VersionName(v)}/${b?'True':'False'}`;Run('geodata/authored/'+suffix,()=>GeoDataRoundTrip(v,b));Run('geodata/independent/'+suffix,()=>GeoDataIndependent(v,b));}
  Run('geodata/finite-and-transport-validation',GeoDataInvalidValues);Run('geodata/mesh-update-and-save-atomicity',GeoDataMeshAtomicity);Run('geodata/attachment-policy',GeoDataAttachmentPolicy);Run('geodata/extension-graph-clone',GeoDataClone);
  for(const v of [1,3,99])Run('geodata/opaque-version/'+v,()=>GeoDataOpaque(v,false));Run('geodata/opaque-private-payload',()=>GeoDataOpaque(2,true));
  for(const defect of ['point-count','face-count','negative-count','face-index','missing-coordinate','missing-definition','duplicate-scalar','wrong-host','late-chunk','orphan-host'])Run('geodata/reject-malformed/'+defect,()=>GeoDataMalformed(defect));
  for(const v of [DxfVersion.AutoCad2000,DxfVersion.AutoCad2004,DxfVersion.AutoCad2007])Run('geodata/version-gate/'+VersionName(v),()=>GeoDataVersionGate(v));
}
export const GeoHost=doc=>doc.Blocks.get_Item(Block.DefaultModelSpaceName).Record;
export function MakeGeoData(doc){
  const data=Object.assign(new DxfGeoData(GeoHost(doc)),{CoordinateType:DxfGeoCoordinateType.LocalGrid,DesignPoint:new Vector3(1.25,-2.5,7.75),ReferencePoint:new Vector3(11.5,48.25,100.125),HorizontalUnitScale:0.3048,VerticalUnitScale:0.0254,HorizontalUnits:DrawingUnits.Feet,VerticalUnits:DrawingUnits.Inches,NorthDirection:new Vector2(3,4),UpDirection:new Vector3(2,3,4),ScaleEstimation:DxfGeoScaleEstimation.UserScale,UserScaleFactor:0.9996,SeaLevelCorrection:true,SeaLevelElevation:-17.25,CoordinateProjectionRadius:6378137,CoordinateSystemDefinition:'x'.repeat(252)+'🧪 Żółć\\U+0041\n'+'z'.repeat(600),GeoRssTag:'metadata',ObservationFrom:'origin Żółć',ObservationTo:'target 東京',ObservationCoverage:'survey bounds'});
  data.SetMesh([new DxfGeoMeshPoint(new Vector2(0,0),new Vector2(11,48)),new DxfGeoMeshPoint(new Vector2(1,0),new Vector2(12,48)),new DxfGeoMeshPoint(new Vector2(0,1),new Vector2(11,49))],[new DxfGeoMeshFace(0,1,2)]);doc.Objects.SetGeoData(data);return data;
}
export function GeoDataRoundTrip(v,b){let doc=new DxfDocument(v);const original=MakeGeoData(doc),definition=original.CoordinateSystemDefinition,handle=original.Handle;for(let cycle=0;cycle<3;cycle++){const stream=new MemoryStream();try{
  Check(doc.Save(stream,b),'GEODATA save');if(cycle===0)OleWriteArtifact(`geodata-${VersionName(v)}-${b?'binary':'ascii'}.dxf`,stream.ToArray());stream.Position=0;const raw=DxfRawDocument.Load(stream),record=OleSingle(OleRecords(raw).filter(r=>r.Name==='GEODATA')),chunks=Array.from(record.Tags).filter(t=>t.Code===301||t.Code===303);
  Check(chunks.length>2&&chunks.at(-1).Code===301&&chunks.slice(0,-1).every(t=>t.Code===303),'definition chunk order');Check(chunks.every(t=>t.Value.length<=255),'definition chunk limit');const cls=OleSingle(Array.from(OleSingle(Array.from(raw.Sections).filter(s=>s.Name==='CLASSES')).Records).filter(r=>Array.from(r.Tags).some(t=>t.Code===1&&t.Value==='GEODATA')));Check(Array.from(cls.Tags).some(t=>t.Code===2&&t.Value==='AcDbGeoData')&&Array.from(cls.Tags).some(t=>t.Code===91&&t.Value===1),'required GEODATA class');
  stream.Position=0;doc=load(stream);const data=doc.Objects.GetGeoData(GeoHost(doc));Check(data!==null,'Missing GEODATA.');Equal(handle,data.Handle,'stable GEODATA identity');Equal(definition,data.CoordinateSystemDefinition,'full chunked definition including literal escapes');vector(new Vector2(3,4),data.NorthDirection,'nonunit north');vector(new Vector3(2,3,4),data.UpDirection,'nonunit up');vector(new Vector3(1.25,-2.5,7.75),data.DesignPoint,'design point');vector(new Vector3(11.5,48.25,100.125),data.ReferencePoint,'reference point');Equal(0.3048,data.HorizontalUnitScale,'horizontal scale');Equal(0.0254,data.VerticalUnitScale,'vertical scale');Equal(0.9996,data.UserScaleFactor,'user scale');Equal(DrawingUnits.Feet,data.HorizontalUnits,'horizontal units');Equal(DrawingUnits.Inches,data.VerticalUnits,'vertical units');Check(data.SeaLevelCorrection,'sea level flag');Equal(-17.25,data.SeaLevelElevation,'sea level elevation');Equal(6378137,data.CoordinateProjectionRadius,'radius');Equal(3,data.MeshPoints.Count,'point count');Equal(1,data.MeshFaces.Count,'face count');Equal(2,data.MeshFaces.get_Item(0).Third,'mesh index');Equal('target 東京',data.ObservationTo,'Unicode metadata');Equal(0,doc.Objects.Validate().Count,'loaded graph');Check(data.Owner===GeoHost(doc).ExtensionDictionary,'extension ownership');
}finally{stream.Dispose();}}}
export function GeoDataIndependent(v,b){
  const year=VersionName(v).slice(7),directory=path.join(sourceRoot,'tests','fixtures','geodata'),input=`${directory}/independent-geodata-R${year}.dxf`,manifest=JSON.parse(fs.readFileSync(`${directory}/manifest.json`,'utf8')),expected=OleSingle(manifest.fixtures.filter(f=>f.file===path.basename(input))),doc=DxfDocument.Load(input);Check(doc!==null,'Independent GEODATA load failed.');const data=doc.Objects.GetGeoData(GeoHost(doc));Check(data!==null,'Independent GEODATA was not typed.');Equal(expected.geodata,data.Handle,'source identity');Equal(expected.coordinate_system_definition,data.CoordinateSystemDefinition,'source full XML');Equal(expected.attributes.design_point[0],data.DesignPoint.X,'source precision');Equal(expected.attributes.scale_estimation_method,data.ScaleEstimation,'source scale method');vector(new Vector2(3,4),data.NorthDirection,'source north');vector(new Vector3(2,3,4),data.UpDirection,'source up');Equal(5,data.MeshPoints.Count,'source point count');Equal(4,data.MeshFaces.Count,'source face count');for(let i=0;i<data.MeshPoints.Count;i++){vector(new Vector2(...expected.source_vertices[i]),data.MeshPoints.get_Item(i).Source,'source mesh coordinate');vector(new Vector2(...expected.target_vertices[i]),data.MeshPoints.get_Item(i).Target,'target mesh coordinate');}Equal(0,doc.Objects.Validate().Count,'independent graph');Check(data.XData.Count>0&&data.PersistentReactors.Count>0,'common data lost');
  const stream=new MemoryStream(),second=new MemoryStream();try{Check(doc.Save(stream,b),'independent GEODATA save');OleWriteArtifact(`independent-geodata-R${year}-${b?'binary':'ascii'}.dxf`,stream.ToArray());stream.Position=0;const edited=load(stream),edit=edited.Objects.GetGeoData(GeoHost(edited));edit.SeaLevelElevation=42.125;edit.MeshPoints.set_Item(0,new DxfGeoMeshPoint(new Vector2(9,8),edit.MeshPoints.get_Item(0).Target));Check(edited.Save(second,!b),'edited independent GEODATA save');second.Position=0;const loaded=load(second),result=loaded.Objects.GetGeoData(GeoHost(loaded));Equal(42.125,result.SeaLevelElevation,'edited elevation');vector(new Vector2(9,8),result.MeshPoints.get_Item(0).Source,'edited mesh');Equal(data.CoordinateSystemDefinition,result.CoordinateSystemDefinition,'unmodified XML');}finally{stream.Dispose();second.Dispose();}
}
export function GeoDataInvalidValues(){const doc=new DxfDocument(DxfVersion.AutoCad2018),data=new DxfGeoData(GeoHost(doc));for(const [key,value]of [['HorizontalUnitScale',0],['VerticalUnitScale',NaN],['UserScaleFactor',Infinity],['CoordinateProjectionRadius',-1],['DesignPoint',new Vector3(0,NaN,1)],['UpDirection',Vector3.Zero],['NorthDirection',Vector2.Zero],['CoordinateType',4],['ScaleEstimation',0],['HorizontalUnits',25]])Throws(ArgumentOutOfRangeException,()=>data[key]=value);for(const [key,value]of [['CoordinateSystemDefinition','literal^J'],['CoordinateSystemDefinition','CR\rLF\n'],['CoordinateSystemDefinition','unpaired\uD800'],['ObservationTo','unpaired\uDC00'],['GeoRssTag','line\nline']])Throws(ArgumentException,()=>data[key]=value);Throws(ArgumentNullException,()=>data.MeshPoints.Add(null));Throws(ArgumentOutOfRangeException,()=>new DxfGeoMeshPoint(new Vector2(-Infinity,0),Vector2.Zero));Throws(ArgumentOutOfRangeException,()=>new DxfGeoMeshFace(0,-1,0));}
export function GeoDataMeshAtomicity(){const doc=new DxfDocument(DxfVersion.AutoCad2018),data=MakeGeoData(doc),original=data.MeshPoints.get_Item(0);Throws(ArgumentException,()=>data.SetMesh([original],[new DxfGeoMeshFace(0,1,2)]));Equal(3,data.MeshPoints.Count,'failed SetMesh retained points');function* fail(){yield original;throw new IOException('enumeration failed');}Throws(IOException,()=>data.SetMesh(fail(),[]));Equal(1,data.MeshFaces.Count,'failed enumeration retained faces');data.MeshPoints.RemoveAt(2);Check(doc.Objects.Validate().Count>0,'dangling mesh index accepted');const seed=doc.DrawingVariables.HandleSeed,layouts=doc.Layouts.Count,stream=new MemoryStream(),repaired=new MemoryStream();try{let rejected;try{rejected=!doc.Save(stream);}catch(e){if(!(e instanceof InvalidOperationException))throw e;rejected=true;}Check(rejected&&stream.Length===0,'invalid mesh wrote output');Equal(seed,doc.DrawingVariables.HandleSeed,'invalid save seed');Equal(layouts,doc.Layouts.Count,'invalid save layouts');data.MeshFaces.Clear();Check(doc.Save(repaired),'repaired mesh save');}finally{stream.Dispose();repaired.Dispose();}}
export function GeoDataAttachmentPolicy(){const doc=new DxfDocument(DxfVersion.AutoCad2018);MakeGeoData(doc);const count=doc.Objects.Items.Count,replacement=new DxfGeoData(GeoHost(doc));Throws(InvalidOperationException,()=>doc.Objects.SetGeoData(replacement));Equal(count,doc.Objects.Items.Count,'duplicate attachment registration');Check(replacement.Database===null&&replacement.Owner===null,'duplicate adopted metadata');const other=new DxfDocument(DxfVersion.AutoCad2018);Throws(ArgumentException,()=>other.Objects.SetGeoData(new DxfGeoData(GeoHost(doc))));const block=other.Blocks.Add(new Block('Plain')),ext=new DxfDictionary();ext.Add('APP',new DxfXRecord());other.Objects.SetExtensionDictionary(block.Record,ext);other.Objects.SetGeoData(new DxfGeoData(block.Record));Check(ext.Contains('APP')&&ext.Contains('ACAD_GEOGRAPHICDATA'),'existing extension entry lost');Equal(0,other.Objects.Validate().Count,'generic host attachment');}
export function GeoDataClone(){const source=new DxfDocument(DxfVersion.AutoCad2018),original=MakeGeoData(source),external=new DxfXRecord();source.NamedObjects.Add('EXTERNAL',external);original.PersistentReactors.Add(external);const metadata=new XData(new ApplicationRegistry('GEODATA_CLONE'));metadata.XDataRecord.Add(new XDataRecord(XDataCode.DatabaseHandle,external.Handle));original.XData.Add(metadata);const target=new DxfDocument(DxfVersion.AutoCad2018),initialCount=target.Objects.Items.Count,initialSeed=target.DrawingVariables.HandleSeed;Throws(InvalidOperationException,()=>target.Objects.CloneExtensionDictionary(GeoHost(source),GeoHost(target)));Equal(initialCount,target.Objects.Items.Count,'missing mapping registration atomicity');Equal(initialSeed,target.DrawingVariables.HandleSeed,'missing mapping seed atomicity');const mapped=new DxfXRecord();target.NamedObjects.Add('EXTERNAL',mapped);target.Objects.CloneExtensionDictionary(GeoHost(source),GeoHost(target),new Map([[external,mapped]]));const clone=target.Objects.GetGeoData(GeoHost(target));Check(clone!==null&&clone!==original,'clone identity');Check(clone.HostBlock===GeoHost(target),'clone host mapping');Equal(0,target.Objects.Validate().Count,'cloned graph validity');Check(OleSingle(clone.PersistentReactors)===mapped,'mapped GEODATA reactor');Equal(mapped.Handle,OleSingle(clone.XData.get_Item('GEODATA_CLONE').XDataRecord).Value,'mapped GEODATA XData reference');clone.MeshPoints.RemoveAt(2);Equal(3,original.MeshPoints.Count,'clone mesh independence');clone.MeshFaces.Clear();const second=source.Blocks.Add(new Block('GeographicCopy'));source.Objects.CloneExtensionDictionary(GeoHost(source),second.Record);Check(source.Objects.GetGeoData(second.Record).HostBlock===second.Record,'same-document host remap');const count=source.Objects.Items.Count,seed=source.DrawingVariables.HandleSeed;Throws(InvalidOperationException,()=>source.Objects.Clone(GeoHost(source).ExtensionDictionary,source.NamedObjects,'INVALID_CLONE'));Equal(count,source.Objects.Items.Count,'rejected clone atomicity');Equal(seed,source.DrawingVariables.HandleSeed,'rejected clone seed');const old=new DxfDocument(DxfVersion.AutoCad2007),oldExternal=new DxfXRecord();old.NamedObjects.Add('EXTERNAL',oldExternal);const oldCount=old.Objects.Items.Count;Throws(InvalidOperationException,()=>old.Objects.CloneExtensionDictionary(GeoHost(source),GeoHost(old),new Map([[external,oldExternal]])));Equal(oldCount,old.Objects.Items.Count,'downgrade clone atomicity');}
export function GeoDataRaw(){const doc=new DxfDocument(DxfVersion.AutoCad2018),handle=MakeGeoData(doc).Handle,stream=new MemoryStream();try{Check(doc.Save(stream,true),'GEODATA source save');stream.Position=0;return{raw:DxfRawDocument.Load(stream),handle};}finally{stream.Dispose();}}
function replace(raw,handle,edit){const record=OleSingle(OleRecords(raw).filter(r=>r.Name==='GEODATA'&&Array.from(r.Tags).some(t=>t.Code===5&&t.Value===handle)));return raw.WithRecord(record,edit(Array.from(record.Tags)));}
export function GeoDataOpaque(v,privatePayload){let{raw,handle}=GeoDataRaw();raw=replace(raw,handle,t=>{const i=t.findIndex(x=>x.Code===90);t[i]=T(90,v);if(privatePayload)t.push(T(300,'private schema extension'));return t;});const stream=new MemoryStream(),saved=new MemoryStream();try{raw.Save(stream);stream.Position=0;const doc=load(stream),opaque=doc.GetObjectByHandle(handle);Check(opaque instanceof DxfOpaqueObject&&doc.Objects.GetGeoData(GeoHost(doc))===null,'unsupported GEODATA was typed');const before=Array.from(opaque.Tags);Check(doc.Save(saved,true),'opaque GEODATA save');saved.Position=0;const after=load(saved).GetObjectByHandle(handle);Check(after instanceof DxfOpaqueObject,'Opaque reload type');Equal(before.length,after.Tags.Count,'opaque payload count');for(let i=0;i<before.length;i++){Equal(before[i].Code,after.Tags.get_Item(i).Code,'opaque code');Equal(before[i].Value,after.Tags.get_Item(i).Value,'opaque value');}const count=doc.Objects.Items.Count;Throws(NotSupportedException,()=>doc.Objects.CloneExtensionDictionary(GeoHost(doc),doc.Blocks.Add(new Block('OpaqueClone')).Record));Equal(count,doc.Objects.Items.Count,'opaque clone leaves database unchanged');}finally{stream.Dispose();saved.Dispose();}}
export function GeoDataMalformed(defect){let{raw,handle}=GeoDataRaw();raw=replace(raw,handle,t=>{const change=(c,v)=>{const i=t.findIndex(x=>x.Code===c);Check(i>=0,'Mutation tag exists');t[i]=T(c,v);};switch(defect){case'point-count':change(93,2147483647);break;case'face-count':change(96,2);break;case'negative-count':change(93,-1);break;case'face-index':change(99,3);break;case'missing-coordinate':t.splice(t.findIndex(x=>x.Code===23),1);break;case'missing-definition':t.splice(t.findIndex(x=>x.Code===301),1);break;case'duplicate-scalar':t.splice(t.findIndex(x=>x.Code===93),0,T(40,2));break;case'wrong-host':t[t.findLastIndex(x=>x.Code===330)]=T(330,handle);break;case'late-chunk':t.splice(t.findIndex(x=>x.Code===301)+1,0,T(303,'late'));break;case'orphan-host':t[t.findLastIndex(x=>x.Code===330)]=T(330,'ABCDEF');break;}return t;});for(const b of [false,true]){const stream=new MemoryStream();try{raw.Save(stream,b);stream.Position=0;let rejected;try{rejected=DxfDocument.Load(stream)===null;}catch(e){if(!(e instanceof FormatException))throw e;rejected=true;}Check(rejected,'Malformed GEODATA was accepted: '+defect);}finally{stream.Dispose();}}}
export function GeoDataVersionGate(v){const doc=new DxfDocument(v),before=doc.Objects.Items.Count,data=new DxfGeoData(GeoHost(doc)),seed=doc.DrawingVariables.HandleSeed;Throws(InvalidOperationException,()=>doc.Objects.SetGeoData(data));Equal(before,doc.Objects.Items.Count,'version gate database');Equal(seed,doc.DrawingVariables.HandleSeed,'version gate seed');Check(data.Owner===null&&data.Database===null&&GeoHost(doc).ExtensionDictionary===null,'version gate attached data');}
