// Complete original HATCH pattern list tests; fixtures are encoded independently of production writers.
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { DxfDocument, DxfRawDocument, DxfTag, HatchType, Vector2, Vector3, MemoryStream } from '../../index.js';
import { InvalidDataException, EndOfStreamException, InvalidOperationException } from '../../runtime/Errors.js';
import { GetTypedIOConfiguration } from '../../runtime/TypedDocumentIO.js';
import { HatchDoubleTags } from './HatchDoublePatternTests.js';
import { RawFixtureBytes } from './RawDocumentTests.js';
import { Run, Check, Equal, Throws, SupportedVersions, VersionName, BooleanName } from './TestHarness.js';
const artifactDirectory=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../../artifacts/conformance/fixtures');
const single=items=>{const rows=Array.from(items);Equal(1,rows.length,'Expected one item');return rows[0];};
const defects=['negative-lines','too-many-lines','too-few-lines','huge-lines','duplicate-list','negative-dashes','too-many-dashes','too-few-dashes','huge-dashes','wrong-angle','wrong-x','wrong-y','wrong-dx','wrong-dy','wrong-dash-count','wrong-dash','missing-x','missing-y','missing-dx','missing-dy','missing-dash-count','duplicate-x','duplicate-dash-count'];
export function RegisterHatchPatternValidationTests(){for(const v of SupportedVersions)for(const b of [false,true]){const suffix=VersionName(v)+'/'+BooleanName(b);for(const mode of ['canonical','reordered','empty','no-dashes','comments']){if(b&&mode==='comments')continue;Run(`hatch/pattern-lists/valid/${suffix}/${mode}`,()=>HatchPatternValid(v,b,mode));}for(const defect of defects)Run(`hatch/pattern-lists/invalid/${suffix}/${defect}`,()=>HatchPatternInvalid(v,b,defect));for(let c=0;c<10;c++)Run(`hatch/pattern-lists/eof/${suffix}/${c}`,()=>HatchPatternEof(v,b,c));}}
export function HatchPatternValidationTags(version){const tags=HatchDoubleTags(version,HatchType.Custom,1),start=tags.findIndex(t=>t.Code===78),end=tags.findIndex((t,i)=>i>=start&&t.Code===98);
  tags.splice(start,end-start,...[[78,2],[53,0],[43,1.5],[44,-2.25],[45,.5],[46,2],[79,3],[49,1.25],[49,-.75],[49,0],[53,0],[43,-3],[44,4.5],[45,-.25],[46,.125],[79,1],[49,2]].map(([c,v])=>new DxfTag(c,v)));
  tags.splice(tags.findLastIndex(t=>t.Code===0&&t.Value==='ENDSEC'),0,...[[0,'LINE'],[5,'201'],[100,'AcDbEntity'],[8,'0'],[100,'AcDbLine'],[10,20],[20,30],[30,40],[11,21],[21,31],[31,41]].map(([c,v])=>new DxfTag(c,v)));return tags;
}
export function HatchPatternValid(version,binary,mode){const tags=HatchPatternValidationTags(version),start=tags.findIndex(t=>t.Code===78),end=tags.findIndex((t,i)=>i>=start&&t.Code===98);
  if(mode==='empty'){tags.splice(start+1,end-start-1);tags[start]=new DxfTag(78,0);}else if(mode==='no-dashes'){for(let i=end-1;i>start;i--){if(tags[i].Code===49)tags.splice(i,1);else if(tags[i].Code===79)tags[i]=new DxfTag(79,0);}}
  else if(mode==='reordered'){for(let i=end-1;i>start;i--)if(tags[i].Code===53){const scalars=tags.splice(i+1,4).reverse(),next=tags.findIndex((t,j)=>j>=i+1&&(t.Code===53||t.Code===98));tags.splice(next,0,...scalars);}}
  else if(mode==='comments')for(let i=end;i>start;i--)tags.splice(i,0,new DxfTag(999,'53 79 49 ENDSEC are not tags'));
  const input=new MemoryStream(RawFixtureBytes(tags,binary));try{let doc=DxfDocument.Load(input);if(!doc)throw new InvalidOperationException('Valid HATCH pattern lists rejected.');Check(input.CanRead,'Pattern parser closed caller input.');HatchPatternCheck(doc,mode,1);doc.Entities.Add(single(doc.Entities.Hatches).Clone());
    for(let cycle=0;cycle<2;cycle++){const output=new MemoryStream();try{Check(doc.Save(output,cycle===0?!binary:binary),'Pattern-list fixture save failed.');output.Position=0;const raw=DxfRawDocument.Load(output);for(const record of Array.from(raw.Sections).flatMap(s=>Array.from(s.Records)).filter(r=>r.Name==='HATCH')){const rows=Array.from(record.Tags);Equal(mode==='empty'?0:2,single(rows.filter(t=>t.Code===78)).Value,'Emitted pattern line count');Equal(mode==='empty'?0:2,rows.filter(t=>t.Code===79).length,'Emitted dash count groups');Equal(mode==='empty'||mode==='no-dashes'?0:4,rows.filter(t=>t.Code===49).length,'Emitted dash lengths');}
      if(mode==='canonical'&&cycle===1){fs.mkdirSync(artifactDirectory,{recursive:true});fs.writeFileSync(path.join(artifactDirectory,`hatch-pattern-lists-${VersionName(version)}-${BooleanName(binary)}.dxf`),output.ToArray());}
      output.Position=0;doc=DxfDocument.Load(output);if(!doc)throw new InvalidOperationException('Pattern-list fixture reload failed.');HatchPatternCheck(doc,mode,2);Check(output.CanRead,'Pattern round trip closed caller stream.');
    }finally{output.Dispose();}}
  }finally{input.Dispose();}
}
export function HatchPatternCheck(doc,mode,count){Equal(count,Array.from(doc.Entities.Hatches).length,'Hatch count');for(const hatch of doc.Entities.Hatches){Equal(HatchType.Custom,hatch.Pattern.Type,'Pattern type');Check(hatch.Pattern.IsDouble,'Pattern double flag changed.');Equal(2.5,hatch.Elevation,'Hatch elevation');Equal(1,hatch.BoundaryPaths.Count,'Boundary path count');Check(new Vector2(2,3).Equals(single(hatch.SeedPoints)),'Seed point changed');Equal('after pattern',single(hatch.XData.get_Item('DOUBLE_TEST').XDataRecord).Value,'Following XData');Equal(mode==='empty'?0:2,hatch.Pattern.LineDefinitions.Count,'Pattern line count');if(mode==='empty')continue;
  const first=hatch.Pattern.LineDefinitions.get_Item(0),second=hatch.Pattern.LineDefinitions.get_Item(1);Check(new Vector2(1.5,-2.25).Equals(first.Origin),'First line origin');Check(new Vector2(.5,2).Equals(first.Delta),'First line delta');Check(new Vector2(-3,4.5).Equals(second.Origin),'Second line origin');Check(new Vector2(-.25,.125).Equals(second.Delta),'Second line delta');Equal(mode==='no-dashes'?[]:[1.25,-.75,0],Array.from(first.DashPattern),'First dash list changed.');Equal(mode==='no-dashes'?[]:[2],Array.from(second.DashPattern),'Second dash list changed.');}
  const line=single(doc.Entities.Lines);Check(new Vector3(20,30,40).Equals(line.StartPoint),'Following LINE start');Check(new Vector3(21,31,41).Equals(line.EndPoint),'Following LINE end');
}
export function HatchPatternInvalid(version,binary,defect){const tags=HatchPatternValidationTags(version),lines=tags.findIndex(t=>t.Code===78),dashes=tags.findIndex((t,i)=>i>=lines&&t.Code===79),end=tags.findIndex((t,i)=>i>=lines&&t.Code===98);
  switch(defect){case 'negative-lines':tags[lines]=new DxfTag(78,-1);break;case 'too-many-lines':tags[lines]=new DxfTag(78,3);break;case 'too-few-lines':tags[lines]=new DxfTag(78,1);break;case 'huge-lines':tags[lines]=new DxfTag(78,32767);break;case 'duplicate-list':tags.splice(end,0,new DxfTag(78,0));break;case 'negative-dashes':tags[dashes]=new DxfTag(79,-1);break;case 'too-many-dashes':tags[dashes]=new DxfTag(79,4);break;case 'too-few-dashes':tags[dashes]=new DxfTag(79,2);break;case 'huge-dashes':tags[dashes]=new DxfTag(79,32767);break;
    case 'wrong-angle':tags[lines+1]=new DxfTag(54,0);break;case 'wrong-x':tags[lines+2]=new DxfTag(48,1.5);break;case 'wrong-y':tags[lines+3]=new DxfTag(48,-2.25);break;case 'wrong-dx':tags[lines+4]=new DxfTag(48,.5);break;case 'wrong-dy':tags[lines+5]=new DxfTag(48,2);break;case 'wrong-dash-count':tags[dashes]=new DxfTag(73,3);break;case 'wrong-dash':tags[dashes+1]=new DxfTag(48,1.25);break;
    case 'missing-x':tags.splice(lines+2,1);break;case 'missing-y':tags.splice(lines+3,1);break;case 'missing-dx':tags.splice(lines+4,1);break;case 'missing-dy':tags.splice(lines+5,1);break;case 'missing-dash-count':tags.splice(dashes,1);break;case 'duplicate-x':tags.splice(lines+3,0,new DxfTag(43,5));break;case 'duplicate-dash-count':tags.splice(end,0,new DxfTag(79,0));break;default:throw new InvalidOperationException('Unknown defect.');}
  const input=new MemoryStream(RawFixtureBytes(tags,binary));try{if(GetTypedIOConfiguration()==='Debug'){try{DxfDocument.Load(input);throw new InvalidOperationException('Invalid HATCH pattern list accepted.');}catch(error){Check(error instanceof InvalidDataException,'Expected InvalidDataException');Check(error.message.includes('HATCH pattern'),'Missing pattern context: '+error.message);Check(error.message.includes('group code'),'Missing group-code context.');}}else Check(DxfDocument.Load(input)===null,'Invalid HATCH pattern list accepted.');Check(input.CanRead,'Rejected pattern list closed caller input.');}finally{input.Dispose();}
}
export function HatchPatternEof(version,binary,component){const tags=HatchPatternValidationTags(version),start=tags.findIndex(t=>t.Code===78),input=new MemoryStream(RawFixtureBytes(tags.slice(0,start+component+1),binary));try{if(GetTypedIOConfiguration()==='Debug')Throws(EndOfStreamException,()=>DxfDocument.Load(input));else Check(DxfDocument.Load(input)===null,'Truncated pattern list accepted.');Check(input.CanRead,'Truncated pattern input was closed.');}finally{input.Dispose();}}
