// Port of the pinned C# conformance module; original case identities and assertions retained.
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { Run, Check, Equal, Throws, SupportedVersions, VersionName, BooleanName } from './TestHarness.js';
const single=items=>{const a=Array.from(items);Equal(1,a.length,'Expected one item');return a[0];};
const artifacts=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../../artifacts/conformance/fixtures');
const saveFixture=(name,bytes)=>{fs.mkdirSync(artifacts,{recursive:true});fs.writeFileSync(path.join(artifacts,name),bytes);};
import { DxfDocument, DxfTag, HatchType, Vector2, Vector3, MemoryStream } from '../../index.js';
import { InvalidDataException, EndOfStreamException } from '../../runtime/Errors.js';
import { GetTypedIOConfiguration } from '../../runtime/TypedDocumentIO.js';
import { HatchDoubleTags } from './HatchDoublePatternTests.js';
import { ClosureEdge } from './HatchPolylineClosureTests.js';
import { EqualHatchSeeds } from './HatchSeedPointTests.js';
import { RawFixtureBytes } from './RawDocumentTests.js';
export function RegisterHatchPolylineInputTests(){for(const v of SupportedVersions)for(const b of [false,true]){const suffix=`${VersionName(v)}/${BooleanName(b)}`;
  for(const mask of [0,1,5,15])Run(`hatch/polyline-input/sparse/${suffix}/${mask}`,()=>HatchPolylineSparse(v,b,mask,false));
  if(!b)Run(`hatch/polyline-input/comments/${VersionName(v)}`,()=>HatchPolylineSparse(v,false,15,true));
  for(let scenario=0;scenario<24;scenario++)Run(`hatch/polyline-input/malformed/${suffix}/${scenario}`,()=>HatchPolylineMalformed(v,b,scenario));
  Run(`hatch/polyline-input/zero-flag-bulges/${suffix}`,()=>HatchPolylineZeroFlag(v,b));Run(`hatch/polyline-input/empty/${suffix}`,()=>HatchPolylineEmpty(v,b));Run(`hatch/polyline-input/source-reference/${suffix}`,()=>HatchPolylineReference(v,b));Run(`hatch/polyline-input/multiple-paths/${suffix}`,()=>HatchPolylineMultiple(v,b));
  // 24 forged-count cases remain unregistered: their native allocation assertion
  // is not replaced by a JS heap delta or by a functional failure check.
  for(let at=0;at<3;at++)Run(`hatch/polyline-input/physical-eof/${suffix}/${at}`,()=>HatchPolylinePhysicalEof(v,b,at));
}}
export function HatchPolylineInputTags(version,mask,comments=false){const tags=HatchDoubleTags(version,HatchType.UserDefined,0);tags[tags.findIndex(t=>t.Code===72)]=new DxfTag(72,1);const start=tags.findIndex(t=>t.Code===93)+1;let index=0;
  for(let at=start;tags[at].Code!==97;at++){if(tags[at].Code!==20)continue;if(mask&(1<<index))tags.splice(++at,0,new DxfTag(42,index%2===0?.5:-.25));index++;}
  if(comments){const end=tags.findIndex(t=>t.Code===75);for(let at=end;at>tags.findIndex(t=>t.Code===92);at--)tags.splice(at,0,new DxfTag(999,'ENDSEC 97 42 comment'));}return tags;
}
export function HatchPolylineSparse(version,binary,mask,comments){const tags=HatchPolylineInputTags(version,mask,comments),input=new MemoryStream(RawFixtureBytes(tags,binary));try{let doc=DxfDocument.Load(input);Check(doc!==null,'Valid sparse polyline input rejected.');let hatch=single(doc.Entities.Hatches);const expected=[new Vector3(0,0,0),new Vector3(10,0,0),new Vector3(10,10,0),new Vector3(0,10,0)];for(let i=0;i<expected.length;i++)if(mask&(1<<i))expected[i].Z=i%2===0?.5:-.25;
  for(let cycle=0;cycle<3;cycle++){const poly=ClosureEdge(hatch);Check(poly.IsClosed,'Sparse bulges lost closure.');Equal(expected,poly.Vertexes,'Omitted bulges misaligned vertex data.');EqualHatchSeeds([new Vector2(2,3)],hatch.SeedPoints);Equal('after pattern',single(hatch.XData.get_Item('DOUBLE_TEST').XDataRecord).Value,'Boundary consumed following XData');const output=new MemoryStream(),transport=cycle===1?binary:!binary;try{Check(doc.Save(output,transport),'Sparse-bulge save failed.');if(cycle===0&&mask===5&&!comments)saveFixture(`hatch-sparse-bulges-${VersionName(version)}-${BooleanName(transport)}.dxf`,output.ToArray());output.Position=0;doc=DxfDocument.Load(output);Check(doc!==null,'Sparse-bulge reload failed.');hatch=single(doc.Entities.Hatches);}finally{output.Dispose();}}
  Check(input.CanRead,'Polyline parser closed caller input.');
}finally{input.Dispose();}}
export function ExpectPolylineInvalid(tags,binary){const input=new MemoryStream(RawFixtureBytes(tags,binary));try{if(GetTypedIOConfiguration()==='Debug'){let failure;try{DxfDocument.Load(input);}catch(error){failure=error;}Check(failure instanceof InvalidDataException,'Malformed polyline was accepted or wrong exception type.');Check(failure.message.includes('HATCH polyline boundary'),'Missing polyline context.');Check(failure.message.includes('group code')&&failure.message.includes('position'),'Missing tag/position diagnostic.');}else Check(DxfDocument.Load(input)===null,'Malformed polyline was accepted.');Check(input.CanRead,'Malformed polyline closed caller input.');}finally{input.Dispose();}}
export function HatchPolylineMalformed(version,binary,scenario){const tags=HatchPolylineInputTags(version,5),flag=tags.findIndex(t=>t.Code===72),closed=flag+1,count=tags.findIndex(t=>t.Code===93),vertex=count+1,refs=tags.findIndex(t=>t.Code===97);
  switch(scenario){case 0:tags.splice(flag,1);break;case 1:tags[flag]=new DxfTag(74,1);break;case 2:tags[flag]=new DxfTag(72,-1);break;case 3:tags[flag]=new DxfTag(72,2);break;case 4:tags.splice(closed,1);break;case 5:tags[closed]=new DxfTag(73,-1);break;case 6:tags[closed]=new DxfTag(73,2);break;case 7:tags[count]=new DxfTag(94,4);break;case 8:tags[count]=new DxfTag(93,-1);break;case 9:tags[count]=new DxfTag(93,3);break;case 10:tags[count]=new DxfTag(93,5);break;case 11:tags[vertex]=new DxfTag(11,0);break;case 12:tags[vertex+1]=new DxfTag(21,0);break;case 13:tags.splice(vertex+3,0,new DxfTag(42,.25));break;case 14:tags.splice(refs,1);break;case 15:tags[refs]=new DxfTag(96,0);break;case 16:tags[refs]=new DxfTag(97,-1);break;case 17:tags[refs]=new DxfTag(97,1);break;case 18:tags[refs]=new DxfTag(97,1);tags.splice(refs+1,0,new DxfTag(340,'201'));break;case 19:tags.splice(refs+1,0,new DxfTag(330,'201'));break;case 20:tags.splice(refs+1,0,new DxfTag(10,123));break;case 21:tags.splice(refs+1,0,new DxfTag(97,0));break;case 22:tags[vertex]=new DxfTag(0,'ENDSEC');break;case 23:tags[refs]=new DxfTag(97,2);tags.splice(refs+1,0,new DxfTag(330,'201'));break;}
  ExpectPolylineInvalid(tags,binary);
}
export function HatchPolylineZeroFlag(version,binary){const tags=HatchPolylineInputTags(version,5);tags[tags.findIndex(t=>t.Code===72)]=new DxfTag(72,0);const input=new MemoryStream(RawFixtureBytes(tags,binary));try{const doc=DxfDocument.Load(input);Check(doc!==null,'Contradictory flag lost valid bulges.');const vertices=ClosureEdge(single(doc.Entities.Hatches)).Vertexes;Equal(.5,vertices[0].Z,'Actual bulge discarded under zero flag');Equal(0,vertices[1].Z,'Missing bulge did not default to zero');Equal(.5,vertices[2].Z,'Sparse bulge misalignment');const output=new MemoryStream();try{Check(doc.Save(output,!binary),'Tolerant bulge output failed.');output.Position=0;const loaded=DxfDocument.Load(output);Check(loaded!==null,'Tolerant output failed to reload.');Equal(vertices,ClosureEdge(single(loaded.Entities.Hatches)).Vertexes,'Output lost retained bulges.');}finally{output.Dispose();}}finally{input.Dispose();}}
export function HatchPolylineEmpty(version,binary){const tags=HatchPolylineInputTags(version,0),start=tags.findIndex(t=>t.Code===93),end=tags.findIndex(t=>t.Code===97);tags[start]=new DxfTag(93,0);tags.splice(start+1,end-start-1);const input=new MemoryStream(RawFixtureBytes(tags,binary));try{const doc=DxfDocument.Load(input);Check(doc!==null,'Zero-sized polyline list rejected.');Equal(0,ClosureEdge(single(doc.Entities.Hatches)).Vertexes.length,'Empty list invented vertices');const output=new MemoryStream();try{Check(doc.Save(output,!binary),'Empty polyline list save failed.');output.Position=0;const loaded=DxfDocument.Load(output);Check(loaded!==null,'Empty polyline list reload failed.');Equal(0,ClosureEdge(single(loaded.Entities.Hatches)).Vertexes.length,'Empty-list output changed');}finally{output.Dispose();}}finally{input.Dispose();}}
export function HatchPolylineReference(version,binary){const tags=HatchPolylineInputTags(version,0);tags[tags.findIndex(t=>t.Code===71)]=new DxfTag(71,1);const refs=tags.findIndex(t=>t.Code===97);tags[refs]=new DxfTag(97,1);tags.splice(refs+1,0,new DxfTag(330,'201'));tags.splice(tags.findLastIndex(t=>t.Code===0&&t.Value==='ENDSEC'),0,...[[0,'LWPOLYLINE'],[5,'201'],[100,'AcDbEntity'],[8,'0'],[100,'AcDbPolyline'],[90,4],[70,1],[38,2.5],[10,0],[20,0],[10,10],[20,0],[10,10],[20,10],[10,0],[20,10]].map(([c,v])=>new DxfTag(c,v)));
  const input=new MemoryStream(RawFixtureBytes(tags,binary));try{let doc=DxfDocument.Load(input);Check(doc!==null,'Referenced polyline failed to load.');for(let cycle=0;cycle<2;cycle++){const hatch=single(doc.Entities.Hatches);Check(hatch.Associative,'Associativity changed.');const contour=single(single(hatch.BoundaryPaths).Entities);Check(doc.GetObjectByHandle('201')===contour,'Boundary reference not resolved to source entity.');const output=new MemoryStream();try{Check(doc.Save(output,!binary),'Referenced boundary save failed.');output.Position=0;doc=DxfDocument.Load(output);Check(doc!==null,'Referenced boundary reload failed.');}finally{output.Dispose();}}}finally{input.Dispose();}}
export function HatchPolylineMultiple(version,binary){const tags=HatchPolylineInputTags(version,5),start=tags.findIndex(t=>t.Code===92),end=tags.findIndex(t=>t.Code===75);tags.splice(end,0,...tags.slice(start,end));tags[tags.findIndex(t=>t.Code===91)]=new DxfTag(91,2);const input=new MemoryStream(RawFixtureBytes(tags,binary));try{const doc=DxfDocument.Load(input);Check(doc!==null,'Adjacent polyline boundaries rejected.');const paths=single(doc.Entities.Hatches).BoundaryPaths;Equal(2,paths.Count,'Polyline parser consumed the following path');for(const path of paths){const poly=single(path.Edges);Equal(4,poly.Vertexes.length,'Following path vertex count');Equal(.5,poly.Vertexes[2].Z,'Following path bulge');}}finally{input.Dispose();}}
export function HatchPolylinePhysicalEof(version,binary,at){const tags=HatchPolylineInputTags(version,5),count=tags.findIndex(t=>t.Code===93),refs=tags.findIndex(t=>t.Code===97);if(at===2)tags[refs]=new DxfTag(97,1);const length=at===0?count+1:at===1?count+2:refs+1,input=new MemoryStream(RawFixtureBytes(tags.slice(0,length),binary));try{if(GetTypedIOConfiguration()==='Debug')Throws(EndOfStreamException,()=>DxfDocument.Load(input));else Check(DxfDocument.Load(input)===null,'Truncated polyline input was accepted.');Check(input.CanRead,'Truncated input closed caller stream.');}finally{input.Dispose();}}
