// Port of the pinned C# conformance module; original case identities and assertions retained.
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { Run, Check, Equal, Throws, SameDoubleBits, SupportedVersions, VersionName, BooleanName } from './TestHarness.js';
const single=items=>{const a=Array.from(items);Equal(1,a.length,'Expected one item');return a[0];};
const artifacts=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../../artifacts/conformance/fixtures');
const saveFixture=(name,bytes)=>{fs.mkdirSync(artifacts,{recursive:true});fs.writeFileSync(path.join(artifacts,name),bytes);};
import { DxfDocument, DxfVersion, DxfTag, HatchType, HatchPattern, HatchGradientPattern, HatchGradientPatternType, AciColor, Vector2, MemoryStream, XData, XDataCode, XDataRecord, ApplicationRegistry } from '../../index.js';
import { IOException } from '../../runtime/Errors.js';
import { GetTypedIOConfiguration } from '../../runtime/TypedDocumentIO.js';
import { HatchDoubleTags } from './HatchDoublePatternTests.js';
import { HatchSeedTags } from './HatchSeedPointTests.js';
import { RawFixtureBytes } from './RawDocumentTests.js';
export function RegisterHatchXDataPreservationTests(){for(const v of SupportedVersions)for(const b of [false,true]){const suffix=`${VersionName(v)}/${BooleanName(b)}`;
  for(let scenario=0;scenario<5;scenario++){Run(`hatch/xdata/origin-context/${suffix}/${scenario}`,()=>HatchXDataRead(v,b,scenario));Run(`hatch/xdata/preservation/${suffix}/${scenario}`,()=>HatchXDataSave(v,b,scenario));}
  Run(`hatch/xdata/absent-source/${suffix}`,()=>HatchXDataAbsent(v,b));Run(`hatch/xdata/failed-save/${suffix}`,()=>HatchXDataFailedSave(v,b));Run(`hatch/xdata/mixed-case-color-prefix/${suffix}`,()=>HatchXDataColorPrefix(v,b));
}}
// Same shared NewSeedHatch body as the pinned HatchSeedPointApiTests partial Program.
function NewSeedHatch(){const input=new MemoryStream(RawFixtureBytes(HatchSeedTags(DxfVersion.AutoCad2018,3,0,false),false));try{const doc=DxfDocument.Load(input);Check(doc!==null,'Seed API fixture failed.');return single(doc.Entities.Hatches);}finally{input.Dispose();}}
export function OriginRecords(x,y){return [new XDataRecord(XDataCode.RealX,x),new XDataRecord(XDataCode.RealY,y),new XDataRecord(XDataCode.RealZ,0)];}
export function HatchAcadRecords(scenario){const nested=[new XDataRecord(XDataCode.String,'NESTED'),XDataRecord.OpenControlString,...OriginRecords(99,88),XDataRecord.CloseControlString],records=[];let originAt=-1;
  if(scenario===0||scenario===3){originAt=0;records.push(...OriginRecords(7,8));}records.push(...nested);
  if(scenario===1){originAt=records.length;records.push(...OriginRecords(7,8));}if(scenario===3)records.push(...OriginRecords(55,66));if(scenario===4)records.push(new XDataRecord(XDataCode.RealX,123));
  records.push(new XDataRecord(XDataCode.String,'unrelated tail'),new XDataRecord(XDataCode.Int16,17),new XDataRecord(XDataCode.BinaryData,Uint8Array.of(0,255,128,127)));return {records,originAt};
}
export function SameXData(expected,actual){const a=Array.from(expected),b=Array.from(actual);Equal(a.length,b.length,'XData record count');for(let i=0;i<a.length;i++){Equal(a[i].Code,b[i].Code,'XData code/order');if(a[i].Value instanceof Uint8Array)Equal(a[i].Value,b[i].Value,'Opaque XData bytes changed.');else if(typeof a[i].Value==='number'&&a[i].Code!==1070&&a[i].Code!==1071)SameDoubleBits(a[i].Value,b[i].Value,'XData real bits');else Equal(a[i].Value,b[i].Value,'XData value');}}
export function HatchXDataRead(version,binary,scenario){const {records,originAt}=HatchAcadRecords(scenario),tags=HatchDoubleTags(version,HatchType.UserDefined,1);tags.splice(tags.findLastIndex(t=>t.Code===0&&t.Value==='ENDSEC'),0,new DxfTag(1001,'ACAD'),...records.map(r=>new DxfTag(r.Code,r.Value)));const input=new MemoryStream(RawFixtureBytes(tags,binary));try{const doc=DxfDocument.Load(input);Check(doc!==null,'ACAD XData input failed.');const hatch=single(doc.Entities.Hatches);Equal(originAt>=0?new Vector2(7,8):Vector2.Zero,hatch.Pattern.Origin,'Nested/later/incomplete point overrode hatch origin');SameXData(records,hatch.XData.get_Item('ACAD').XDataRecord);Check(input.CanRead,'ACAD XData load closed input.');}finally{input.Dispose();}}
export function HatchXDataSave(version,binary,scenario){for(const fill of [0,1,2]){
  let hatch=NewSeedHatch().Clone();hatch.Pattern=fill===0?HatchPattern.Line:fill===1?HatchPattern.Solid:new HatchGradientPattern(new AciColor(1),new AciColor(5),HatchGradientPatternType.Linear);hatch.Pattern.Origin=new Vector2(21,34);hatch.XData.Remove('ACAD');
  const {records:originalRecords,originAt}=HatchAcadRecords(scenario),acad=new XData(new ApplicationRegistry('ACAD'));acad.XDataRecord.AddRange(originalRecords);hatch.XData.Add(acad);
  for(const app of ['GradientColor1ACI','GradientColor2ACI']){hatch.XData.Remove(app);const data=new XData(new ApplicationRegistry(app));data.XDataRecord.Add(new XDataRecord(XDataCode.Int16,9));data.XDataRecord.Add(new XDataRecord(XDataCode.String,'gradient tail'));hatch.XData.Add(data);}
  const expected=originalRecords.slice();if(originAt>=0)expected.splice(originAt,3,...OriginRecords(21,34));else expected.unshift(...OriginRecords(21,34));let doc=new DxfDocument(version);doc.Entities.Add(hatch);
  for(let cycle=0;cycle<3;cycle++){const snapshots=new Map(Array.from(hatch.XData.Values,d=>[d.ApplicationRegistry.Name,d.Clone()])),identities=new Map(Array.from(hatch.XData.Values,d=>[d.ApplicationRegistry.Name,Array.from(d.XDataRecord)])),output=new MemoryStream();try{
    Check(doc.Save(output,cycle===1?!binary:binary),'XData preservation save failed.');Equal(snapshots.size,hatch.XData.Count,'Save added source XData applications');
    for(const [key,snapshot]of snapshots){const actual=Array.from(hatch.XData.get_Item(key).XDataRecord);SameXData(snapshot.XDataRecord,actual);Check(identities.get(key).length===actual.length&&identities.get(key).every((r,i)=>r===actual[i]),'Save replaced source XData record objects.');}
    if(cycle===0&&scenario===0&&fill===2)saveFixture(`hatch-xdata-${VersionName(version)}-${BooleanName(binary)}.dxf`,output.ToArray());output.Position=0;doc=DxfDocument.Load(output);Check(doc!==null,'XData preservation reload failed.');hatch=single(doc.Entities.Hatches);SameXData(expected,hatch.XData.get_Item('ACAD').XDataRecord);Equal(new Vector2(21,34),hatch.Pattern.Origin,'Origin did not survive nested metadata');
    for(const app of ['GradientColor1ACI','GradientColor2ACI']){const data=hatch.XData.get_Item(app).XDataRecord;Equal(2,data.Count,'Gradient XData suffix was discarded');Equal('gradient tail',data.get_Item(1).Value,'Gradient suffix value changed');Equal(fill===2?(app.endsWith('1ACI')?1:5):9,data.get_Item(0).Value,'Gradient managed value incorrect');}
    Check(output.CanRead,'XData save closed caller output.');
  }finally{output.Dispose();}}
}}
export function HatchXDataAbsent(version,binary){const hatch=NewSeedHatch().Clone();hatch.XData.Clear();hatch.Pattern=new HatchGradientPattern();hatch.Pattern.Origin=new Vector2(21,34);const doc=new DxfDocument(version);doc.Entities.Add(hatch);const output=new MemoryStream();try{Check(doc.Save(output,binary),'Absent XData save failed.');Equal(0,hatch.XData.Count,"Save injected managed data into the caller's hatch");output.Position=0;const loaded=DxfDocument.Load(output);Check(loaded!==null,'Generated XData reload failed.');Equal(new Vector2(21,34),single(loaded.Entities.Hatches).Pattern.Origin,'Generated origin missing');Equal(3,single(loaded.Entities.Hatches).XData.Count,'Managed output applications missing');}finally{output.Dispose();}}
class HatchLateFailStream extends MemoryStream{constructor(limit){super();this.limit=limit;}Guard(count){if(this.Position+count>this.limit)throw new IOException('Injected late HATCH save failure.');}Write(buffer,offset=0,count=buffer.length-offset){this.Guard(count);super.Write(buffer,offset,count);}WriteByte(value){this.Guard(1);super.WriteByte(value);}}
export function HatchXDataFailedSave(version,binary){const hatch=NewSeedHatch().Clone();hatch.XData.Remove('ACAD');const data=new XData(new ApplicationRegistry('ACAD'));data.XDataRecord.AddRange(HatchAcadRecords(0).records);hatch.XData.Add(data);hatch.Pattern.Origin=new Vector2(21,34);const doc=new DxfDocument(version);doc.Entities.Add(hatch);const probe=new MemoryStream();try{Check(doc.Save(probe,binary),'Failure test output probe failed.');const identity=Array.from(data.XDataRecord),snapshot=data.Clone(),output=new HatchLateFailStream(probe.Length-1);try{
  if(GetTypedIOConfiguration()==='Debug')Throws(IOException,()=>doc.Save(output,binary));else Check(!doc.Save(output,binary),'Injected output failure was not reported.');SameXData(snapshot.XDataRecord,data.XDataRecord);const actual=Array.from(data.XDataRecord);Check(identity.length===actual.length&&identity.every((r,i)=>r===actual[i]),'Failed output replaced caller XData records.');Check(output.CanWrite,'Failed save closed caller output.');
}finally{output.Dispose();}}finally{probe.Dispose();}}
export function HatchXDataColorPrefix(version,binary){const hatch=NewSeedHatch().Clone();hatch.XData.Clear();hatch.Pattern=new HatchGradientPattern(new AciColor(1),new AciColor(5),HatchGradientPatternType.Linear);for(const app of ['acad','gradientcolor1aci','gradientcolor2aci']){const data=new XData(new ApplicationRegistry(app));data.XDataRecord.Add(new XDataRecord(XDataCode.String,'prefix'));hatch.XData.Add(data);}const doc=new DxfDocument(version);doc.Entities.Add(hatch);const output=new MemoryStream();try{
  Check(doc.Save(output,binary),'Mixed-case XData save failed.');for(const data of hatch.XData.Values)Equal(1,data.XDataRecord.Count,'Projection inserted source records');output.Position=0;const loaded=DxfDocument.Load(output);Check(loaded!==null,'Mixed-case XData load failed.');const restored=single(loaded.Entities.Hatches);Equal(3,restored.XData.Count,'Case-insensitive APPID duplicated');Equal(4,restored.XData.get_Item('ACAD').XDataRecord.Count,'ACAD prefix not preserved');Equal('prefix',restored.XData.get_Item('ACAD').XDataRecord.get_Item(3).Value,'ACAD prefix overwritten');for(const app of ['GradientColor1ACI','GradientColor2ACI']){Equal(2,restored.XData.get_Item(app).XDataRecord.Count,'Color prefix not preserved');Equal('prefix',restored.XData.get_Item(app).XDataRecord.get_Item(1).Value,'Color prefix overwritten');}
}finally{output.Dispose();}}
