// Port of pinned LightListTests.cs. Original identities and all assertions retained.
import { DxfDocument, DxfRawDocument, DxfTag, DxfVersion, MemoryStream, Light, LightType, Line, Vector3, Layer, DxfDictionary, DxfLightList, DxfLightListEntry, DxfXRecord, DxfOpaqueObject, DxfClass, XData, XDataRecord, XDataCode, ApplicationRegistry } from '../../index.js';
import { ArgumentException, ArgumentNullException, InvalidOperationException, InvalidDataException, FormatException } from '../../runtime/Errors.js';
import { Run, Check, Equal, Throws, VersionName, BooleanName } from './TestHarness.js';
import { OleWriteArtifact, OleSingle, OleRecords } from './Ole2FrameTests.js';
import { RawFixtureBytes } from './RawDocumentTests.js';
import fs from 'node:fs';
import path from 'node:path';
import { sourceRoot } from '../../tools/dotnet.mjs';
const versions=[DxfVersion.AutoCad2007,DxfVersion.AutoCad2010,DxfVersion.AutoCad2013,DxfVersion.AutoCad2018];
const tag=(code,value)=>new DxfTag(code,value),main=doc=>doc.NamedObjects.get_Item('QA_LIGHTLISTS').get_Item('MAIN');
const load=stream=>{const doc=DxfDocument.Load(stream);Check(doc!==null,'LIGHTLIST load failed');return doc;};
export function RegisterLightListTests(){
  for(const v of versions)for(const b of [false,true]){
    const id=`${VersionName(v)}/${BooleanName(b)}`;
    Run(`lightlist/authored/${id}`,()=>LightListAuthored(v,b));Run(`lightlist/mapped-clone/${id}`,()=>LightListClone(v,b));
    for(const sb of [false,true])Run(`lightlist/independent/${VersionName(v)}/${BooleanName(sb)}/${BooleanName(b)}`,()=>LightListIndependent(v,sb,b));
    for(const defect of ['missing-version','missing-count','negative-count','huge-count','wrong-count','extra-version','missing-handle','missing-name','pair-order','duplicate-marker','wrong-target','missing-target','null-target','late-pair','invalid-name'])Run(`lightlist/malformed/${id}/${defect}`,()=>LightListMalformed(v,b,defect));
    for(const extension of ['private-field','private-subclass','private-marker'])Run(`lightlist/opaque/${id}/${extension}`,()=>LightListOpaque(v,b,extension));
    Run(`lightlist/class-contract/${id}`,()=>LightListClassContract(v,b));
  }
  Run('lightlist/entry-validation-and-atomicity',LightListEntryValidation);
  for(const v of [DxfVersion.AutoCad2000,DxfVersion.AutoCad2004])for(const b of [false,true])Run(`lightlist/older-profile/${VersionName(v)}/${BooleanName(b)}`,()=>LightListOlderProfile(v,b));
}
export function LightListDocument(v){
  const doc=new DxfDocument(v),a=Object.assign(new Light(),{Name:'Actual A',Position:new Vector3(1.25,-2.5,4),Target:new Vector3(5,7,-1),LightType:LightType.Point}),b=Object.assign(new Light(),{Name:'Actual B',Position:new Vector3(-8,9,2),Target:new Vector3(2,4,6),LightType:LightType.Spot});
  doc.Entities.Add(a);doc.Entities.Add(b);doc.Entities.Add(new Line(new Vector3(21,22,23),new Vector3(31,32,33)));
  const dictionary=new DxfDictionary(),list=new DxfLightList(42);
  list.Entries.Add(new DxfLightListEntry(a,'Stored alias 青'));list.Entries.Add(new DxfLightListEntry(b,''));list.Entries.Add(new DxfLightListEntry(a,'Literal\\U+0041 🧪'));
  dictionary.Add('MAIN',list,true);dictionary.Add('ALIAS',list,false);dictionary.Add('EMPTY',new DxfLightList(-2147483648),true);doc.NamedObjects.Add('QA_LIGHTLISTS',dictionary,true);list.PersistentReactors.Add(dictionary);
  const ext=new DxfDictionary(),payload=new DxfXRecord();payload.Data.Add(tag(1,'extension payload'));payload.Data.Add(tag(90,1701));payload.Data.Add(tag(310,Uint8Array.of(0,1,255,0)));ext.Add('PAYLOAD',payload,true);doc.Objects.SetExtensionDictionary(list,ext);
  const data=new XData(new ApplicationRegistry('QA_LIGHTLIST'));data.XDataRecord.Add(new XDataRecord(XDataCode.String,'list metadata'));data.XDataRecord.Add(new XDataRecord(XDataCode.DatabaseHandle,a.Handle));list.XData.Add(data);return doc;
}
export function LightListAssert(doc,expectedHandle=null){
  const dictionary=doc.NamedObjects.get_Item('QA_LIGHTLISTS'),list=dictionary.get_Item('MAIN'),entries=Array.from(list.Entries);
  Equal(42,list.StoredVersion,'explicit raw version');Equal(3,list.Entries.Count,'entry count');if(expectedHandle!==null)Equal(expectedHandle,list.Handle,'object identity differs from repeated payload handles');
  Check(list===dictionary.get_Item('ALIAS'),'dictionary alias identity');Equal(-2147483648,dictionary.get_Item('EMPTY').StoredVersion,'signed version retained');Equal(0,dictionary.get_Item('EMPTY').Entries.Count,'empty list count');
  Equal('Stored alias 青',entries[0].Name,'stored name independent of Light.Name');Equal('',entries[1].Name,'empty name');Equal('Literal\\U+0041 🧪',entries[2].Name,'literal escape and supplementary Unicode');
  Check(entries[0].Light===entries[2].Light,'duplicate target identity');Check(entries.every(e=>doc.GetObjectByHandle(e.Light.Handle)===e.Light),'canonical registered LIGHT identities');
  Equal('Actual A',entries[0].Light.Name,'referenced entity independent name');Equal('Actual B',entries[1].Light.Name,'second referenced entity name');Check(list.Owner===dictionary&&OleSingle(list.PersistentReactors)===dictionary,'owner/reactor graph');
  Check(list.ExtensionDictionary!==null&&list.ExtensionDictionary.Owner===list,'extension owner graph');Equal(1701,list.ExtensionDictionary.get_Item('PAYLOAD').Data.get_Item(1).Value,'extension payload');Equal(entries[0].Light.Handle,list.XData.get_Item('QA_LIGHTLIST').XDataRecord.get_Item(1).Value,'XData target identity');Equal(0,doc.Objects.Validate().Count,'valid database graph');
}
export function LightListAuthored(v,b){let doc=LightListDocument(v);const handle=main(doc).Handle;for(let cycle=0;cycle<3;cycle++){const stream=new MemoryStream();try{Check(doc.Save(stream,cycle===1?!b:b),'LIGHTLIST save');if(cycle===2)OleWriteArtifact(`lightlist-${VersionName(v)}-${BooleanName(b)}.dxf`,stream.ToArray());stream.Position=0;doc=load(stream);LightListAssert(doc,handle);}finally{stream.Dispose();}}}
export function LightListIndependent(v,sb,b){
  const stem=`independent-lightlist-R${VersionName(v).slice(7)}-${sb?'binary':'ascii'}`,directory=path.join(sourceRoot,'tests','fixtures','lightlist'),fixtures=JSON.parse(fs.readFileSync(`${directory}/manifest.json`,'utf8')).fixtures;Equal(8,fixtures.length,'mandatory independent fixture inventory');const expected=OleSingle(fixtures.filter(f=>f.file===stem+'.dxf'));let doc=DxfDocument.Load(`${directory}/${stem}.dxf`);Check(doc!==null,'Independent LIGHTLIST load failed.');
  for(let cycle=0;cycle<2;cycle++){
    const dictionary=doc.NamedObjects.get_Item('QA_LIGHTLISTS');Equal(5,dictionary.Entries.Count,'independent list inventory');
    for(const record of expected.lists){const list=doc.GetObjectByHandle(record.handle);Check(list instanceof DxfLightList,'Independent LIGHTLIST was not typed.');Equal(record.stored_version,list.StoredVersion,'independent signed version');Equal(record.entries.length,list.Entries.Count,'independent count');for(let i=0;i<record.entries.length;i++){Equal(record.entries[i].light,list.Entries.get_Item(i).Light.Handle,'independent actual LIGHT reference');Equal(record.entries[i].name,list.Entries.get_Item(i).Name,'independent exact stored name');}Check(list.Owner===dictionary&&OleSingle(list.PersistentReactors)===dictionary,'independent owner/reactor');Equal('1D',list.XData.get_Item('QA_LIGHTLIST').XDataRecord.get_Item(1).Value,'independent XData');if(record.extension!==null)Equal('500',list.ExtensionDictionary.Handle,'independent extension');}
    Equal(0,doc.Objects.Validate().Count,'independent graph validity');const stream=new MemoryStream();try{Check(doc.Save(stream,b),'independent LIGHTLIST save');if(cycle===0)OleWriteArtifact(`${stem}-roundtrip-${b?'binary':'ascii'}.dxf`,stream.ToArray());stream.Position=0;doc=load(stream);}finally{stream.Dispose();}
  }
}
export function LightListClone(v,b){
  const source=LightListDocument(v),dictionary=source.NamedObjects.get_Item('QA_LIGHTLISTS'),target=new DxfDocument(v);for(let i=0;i<40;i++)target.Layers.Add(new Layer('Offset'+i));const map=new Map();for(const light of source.Entities.Lights){const copy=light.Clone();target.Entities.Add(copy);map.set(light,copy);Check(light.Handle!==copy.Handle,'mapped LIGHT handles actually differ');}target.Entities.Add(OleSingle(source.Entities.Lines).Clone());
  const before=target.Objects.Items.Count,seed=target.DrawingVariables.HandleSeed;Throws(InvalidOperationException,()=>target.Objects.Clone(dictionary,target.NamedObjects,'QA_LIGHTLISTS'));Equal(before,target.Objects.Items.Count,'missing mapping inventory atomicity');Equal(seed,target.DrawingVariables.HandleSeed,'missing mapping seed atomicity');
  const first=Array.from(source.Entities.Lights)[0],wrong=new Map(map);wrong.set(first,OleSingle(target.Entities.Lines));Throws(ArgumentException,()=>target.Objects.Clone(dictionary,target.NamedObjects,'QA_LIGHTLISTS',wrong));Equal(before,target.Objects.Items.Count,'wrong type mapping inventory atomicity');Equal(seed,target.DrawingVariables.HandleSeed,'wrong type mapping seed atomicity');
  target.Objects.Clone(dictionary,target.NamedObjects,'QA_LIGHTLISTS',map);LightListAssert(target);Check(main(target).Handle!==dictionary.get_Item('MAIN').Handle,'mapped list identity differs');const stream=new MemoryStream();try{Check(target.Save(stream,b),'cloned LIGHTLIST save');OleWriteArtifact(`lightlist-clone-${VersionName(v)}-${BooleanName(b)}.dxf`,stream.ToArray());stream.Position=0;LightListAssert(load(stream));}finally{stream.Dispose();}
  const local=source.Objects.Clone(dictionary,source.NamedObjects,'LOCAL');Check(local.get_Item('MAIN').Entries.get_Item(0).Light===first,'same-document clone keeps exact existing LIGHT');local.get_Item('MAIN').Entries.Clear();Equal(3,dictionary.get_Item('MAIN').Entries.Count,'clone collection independence');
}
export function LightListRaw(v){const doc=LightListDocument(v),handle=main(doc).Handle,stream=new MemoryStream();try{Check(doc.Save(stream,true),'raw LIGHTLIST source');stream.Position=0;return{raw:DxfRawDocument.Load(stream),handle};}finally{stream.Dispose();}}
function replace(raw,handle,mutate){const record=OleSingle(OleRecords(raw).filter(r=>Array.from(r.Tags).some(t=>t.Code===5&&t.Value===handle)&&r.Name==='LIGHTLIST'));return raw.WithRecord(record,mutate(Array.from(record.Tags)));}
export function LightListMalformed(v,b,defect){let{raw,handle}=LightListRaw(v);raw=replace(raw,handle,t=>{const marker=t.findIndex(t=>t.Code===100&&t.Value==='AcDbLightList'),pair=marker+3;switch(defect){case'missing-version':t.splice(marker+1,1);break;case'missing-count':t.splice(marker+2,1);break;case'negative-count':t[marker+2]=tag(90,-1);break;case'huge-count':t[marker+2]=tag(90,2147483647);break;case'wrong-count':t[marker+2]=tag(90,2);break;case'extra-version':t.splice(marker+2,0,tag(90,7));break;case'missing-handle':t.splice(pair,1);break;case'missing-name':t.splice(pair+1,1);break;case'pair-order':[t[pair],t[pair+1]]=[t[pair+1],t[pair]];break;case'duplicate-marker':t.splice(marker+1,0,tag(100,'AcDbLightList'));break;case'wrong-target':t[pair]=tag(5,handle);break;case'missing-target':t[pair]=tag(5,'FFABC');break;case'null-target':t[pair]=tag(5,'0');break;case'late-pair':t.push(tag(5,'FFABC'),tag(1,'late'));break;case'invalid-name':t[pair+1]=tag(1,'encoded\\U+000Aname');break;}return t;});const stream=new MemoryStream();try{raw.Save(stream,b);stream.Position=0;let rejected;try{rejected=DxfDocument.Load(stream)===null;}catch(e){if(!(e instanceof FormatException))throw e;rejected=true;}Check(rejected,'Recognized malformed LIGHTLIST accepted: '+defect);}finally{stream.Dispose();}}
export function LightListOpaque(v,b,extension){let{raw,handle}=LightListRaw(v);raw=replace(raw,handle,t=>{const marker=t.findIndex(t=>t.Code===100&&t.Value==='AcDbLightList');if(extension==='private-marker')t[marker]=tag(100,'PrivateLightList');else t.splice(t.findIndex(t=>t.Code===1001),0,extension==='private-field'?tag(300,'private data'):tag(100,'PrivateExtension'));return t;});const stream=new MemoryStream(),saved=new MemoryStream();try{raw.Save(stream,b);stream.Position=0;const doc=load(stream),opaque=doc.GetObjectByHandle(handle);Check(opaque instanceof DxfOpaqueObject,'Private LIGHTLIST was promoted.');const before=Array.from(opaque.Tags);Check(doc.Save(saved,!b),'opaque LIGHTLIST save');saved.Position=0;const after=load(saved).GetObjectByHandle(handle);Check(after instanceof DxfOpaqueObject,'Opaque reload type');Equal(before.length,after.Tags.Count,'opaque full payload length including terminal XData');for(let i=0;i<before.length;i++){Equal(before[i].Code,after.Tags.get_Item(i).Code,'opaque code');Equal(before[i].Value,after.Tags.get_Item(i).Value,'opaque value');}}finally{stream.Dispose();saved.Dispose();}}
export function LightListEntryValidation(){
  const light=new Light(),list=new DxfLightList(-2147483648);list.StoredVersion=2147483647;Throws(ArgumentNullException,()=>new DxfLightListEntry(null,'name'));Throws(ArgumentNullException,()=>new DxfLightListEntry(light,null));for(const name of ['a\0b','a\rb','a\nb','\uD800','\uDC00'])Throws(ArgumentException,()=>new DxfLightListEntry(light,name));Throws(ArgumentNullException,()=>list.Entries.Add(null));list.Entries.Add(new DxfLightListEntry(light,''));const doc=new DxfDocument(DxfVersion.AutoCad2018),count=doc.Objects.Items.Count,seed=doc.DrawingVariables.HandleSeed;Throws(ArgumentException,()=>doc.NamedObjects.Add('INVALID',list));Equal(count,doc.Objects.Items.Count,'unregistered target did not allocate');Equal(seed,doc.DrawingVariables.HandleSeed,'unregistered target seed');doc.Entities.Add(light);doc.NamedObjects.Add('VALID',list);
  const foreign=new DxfDocument(DxfVersion.AutoCad2018),other=new Light();foreign.Entities.Add(other);Throws(ArgumentException,()=>list.Entries.Add(new DxfLightListEntry(other,'foreign')));Throws(ArgumentException,()=>list.Entries.set_Item(0,new DxfLightListEntry(other,'foreign')));Equal(1,list.Entries.Count,'failed insert count');Check(light===list.Entries.get_Item(0).Light,'failed replace target');light.Name='renamed actual light';Equal('',list.Entries.get_Item(0).Name,'rename must not overwrite independently stored name');
}
export function LightListClassContract(v,b){
  const doc=LightListDocument(v);doc.Classes.Add(Object.assign(new DxfClass('LIGHTLIST','AcDbLightList','Independent Application'),{ProxyFlags:17,InstanceCount:987,IsEntity:false}));const stream=new MemoryStream();try{Check(doc.Save(stream,b),'compatible class save');stream.Position=0;const loaded=load(stream);Equal('Independent Application',loaded.Classes.get_Item('LIGHTLIST').ApplicationName,'existing class app retained');Equal(17,loaded.Classes.get_Item('LIGHTLIST').ProxyFlags,'existing class flags retained');Equal(2,loaded.Classes.get_Item('LIGHTLIST').InstanceCount,'actual instance count');}finally{stream.Dispose();}
  const bad=LightListDocument(v);bad.Classes.Add(new DxfClass('LIGHTLIST','PrivateClass','PrivateApp'));const rejectedStream=new MemoryStream();try{let rejected;try{rejected=!bad.Save(rejectedStream,b);}catch(e){if(!(e instanceof InvalidDataException))throw e;rejected=true;}Check(rejected&&rejectedStream.Length===0,'conflicting typed class wrote bytes');}finally{rejectedStream.Dispose();}
  const emptied=new DxfDocument(v);emptied.Classes.Add(Object.assign(new DxfClass('LIGHTLIST','AcDbLightList','SCENEOE'),{InstanceCount:1,ProxyFlags:1025}));const emptyStream=new MemoryStream();try{Check(emptied.Save(emptyStream,b),'class after last instance removed');emptyStream.Position=0;Equal(0,load(emptyStream).Classes.get_Item('LIGHTLIST').InstanceCount,'compatible class count must reach zero');}finally{emptyStream.Dispose();}
  const plain=new DxfDocument(v);plain.Classes.Add(Object.assign(new DxfClass('LIGHTLIST','PrivateClass','PrivateApp'),{InstanceCount:17,ProxyFlags:7}));const preserved=new MemoryStream();try{Check(plain.Save(preserved,b),'no typed instances preserve unrelated CLASS');preserved.Position=0;const restored=load(preserved);Equal('PrivateClass',restored.Classes.get_Item('LIGHTLIST').CppClassName,'no typed class enforcement');Equal(17,restored.Classes.get_Item('LIGHTLIST').InstanceCount,'no typed count rewrite');}finally{preserved.Dispose();}
}
export function LightListOlderProfile(v,b){
  const doc=new DxfDocument(v);doc.NamedObjects.Add('EMPTY_LIGHTLIST',new DxfLightList(-7));const stream=new MemoryStream();try{let rejected;try{rejected=!doc.Save(stream,b);}catch(e){if(!(e instanceof InvalidOperationException))throw e;rejected=true;}Check(rejected&&stream.Length===0,'unsupported typed profile emitted output');}finally{stream.Dispose();}
  const modern=new DxfDocument(DxfVersion.AutoCad2007);modern.NamedObjects.Add('EMPTY_LIGHTLIST',new DxfLightList(-7));const original=new MemoryStream();try{Check(modern.Save(original,false),'modern empty source');original.Position=0;const raw=DxfRawDocument.Load(original),tags=Array.from(raw.Tags),at=tags.findIndex(t=>t.Code===9&&t.Value==='$ACADVER');tags[at+1]=tag(1,v===DxfVersion.AutoCad2000?'AC1015':'AC1018');const oldStream=new MemoryStream(RawFixtureBytes(tags,false)),saved=new MemoryStream();try{const older=load(oldStream);Check(older.NamedObjects.get_Item('EMPTY_LIGHTLIST') instanceof DxfOpaqueObject,'older LIGHTLIST must remain opaque');Check(older.Save(saved,b),'older opaque save');}finally{oldStream.Dispose();saved.Dispose();}}finally{original.Dispose();}
}
