// Complete port of pinned LightTests.cs; original registration identities and assertions.
import { DxfDocument, DxfRawDocument, DxfTag, DxfVersion, MemoryStream, Light, LightShadowType, Vector3, Matrix3, Block, Insert, Layout } from '../../index.js';
import { ArgumentException, ArgumentNullException, ArgumentOutOfRangeException, InvalidDataException, NotSupportedException } from '../../runtime/Errors.js';
import { GetTypedIOConfiguration } from '../../runtime/TypedDocumentIO.js';
import { Run, Check, Equal, Near, SameDoubleBits, Throws, SupportedVersions, VersionName, HeaderVersion, BooleanName } from './TestHarness.js';
import { RawFixtureBytes } from './RawDocumentTests.js';
import { OleWriteArtifact } from './Ole2FrameTests.js';
const single=values=>{const a=Array.from(values);Equal(1,a.length,'Single');return a[0];};
const vectorEqual=(expected,actual,message)=>Check(expected.Equals(actual),message);
export function RegisterLightTests(){for(const version of SupportedVersions)for(const binary of [false,true]){
  const id=`${VersionName(version)}/${BooleanName(binary)}`;
  for(const kind of [1,2,3])for(const reverse of [false,true])Run(`light/wire/${id}/${kind}/${BooleanName(reverse)}`,()=>LightWire(version,binary,kind,reverse));
  for(let placement=0;placement<4;placement++)Run(`light/placement/${id}/${placement}`,()=>LightPlacement(version,binary,placement));
  for(let failure=0;failure<10;failure++)Run(`light/invalid/${id}/${failure}`,()=>LightInvalid(version,binary,failure));
}Run('light/api/validation-and-clone',LightApi);for(let operation=0;operation<7;operation++)Run(`light/transform/${operation}`,()=>LightTransform(operation));}
export function LightTags(version,kind,reverse){
  const t=(c,v)=>new DxfTag(c,v),tags=[[0,'SECTION'],[2,'HEADER'],[9,'$ACADVER'],[1,HeaderVersion(version)],[9,'$DWGCODEPAGE'],[3,'ANSI_1252'],[0,'ENDSEC'],[0,'SECTION'],[2,'ENTITIES'],[0,'LIGHT'],[5,'200'],[100,'AcDbEntity'],[8,'0'],[62,3],[100,'AcDbLight']].map(([c,v])=>t(c,v));
  const packet=[[90,0],[1,'Lamp \\U+017B\\U+00F3\\U+0142\\U+0107'],[70,kind],[290,false],[291,true],[40,1.2500000000000002],[10,2],[20,-3],[30,5],[11,-7],[21,11],[31,13],[72,kind-1],[292,true],[41,.125],[42,2048],[50,37.5],[51,62.75],[293,false],[73,1],[91,1024],[280,7]].map(([c,v])=>t(c,v));if(reverse)packet.reverse();tags.push(...packet,...[[1001,'LIGHT_TEST'],[1000,'retained light data'],[0,'LINE'],[5,'201'],[100,'AcDbEntity'],[8,'0'],[100,'AcDbLine'],[10,20],[20,30],[30,40],[11,50],[21,60],[31,70],[0,'ENDSEC'],[0,'EOF']].map(([c,v])=>t(c,v)));return tags;
}
export function LoadTestLight(){const input=new MemoryStream(RawFixtureBytes(LightTags(DxfVersion.AutoCad2018,3,false),false));try{const doc=DxfDocument.Load(input);Check(doc!==null,'LIGHT rejected.');return single(doc.Entities.Lights);}finally{input.Dispose();}}
export function AssertLight(light,kind){Equal(kind,light.LightType,'Light kind');Equal('Lamp Żółć',light.Name,'Unicode light name');Equal(0,light.VersionNumber,'Light schema version');vectorEqual(new Vector3(2,-3,5),light.Position,'WCS position');vectorEqual(new Vector3(-7,11,13),light.Target,'WCS target');SameDoubleBits(1.2500000000000002,light.Intensity,'Authored intensity');Equal(kind-1,light.AttenuationType,'Attenuation kind');Equal(.125,light.AttenuationStartLimit,'Attenuation start');Equal(2048,light.AttenuationEndLimit,'Attenuation end');Equal(37.5,light.HotspotAngle,'Hotspot degrees');Equal(62.75,light.FalloffAngle,'Falloff degrees');Check(!light.IsOn&&light.PlotGlyph&&light.UseAttenuationLimits&&!light.CastShadows,'Light flags changed.');Equal(LightShadowType.ShadowMap,light.ShadowType,'Shadow type');Equal(1024,light.ShadowMapSize,'Shadow map size');Equal(7,light.ShadowMapSoftness,'Softness');Equal(3,light.Color.Index,'Common entity color collided with light parameters');Equal('retained light data',single(light.XData.get_Item('LIGHT_TEST').XDataRecord).Value,'XData');}
function payload(tags){const a=Array.from(tags),start=a.findIndex(t=>t.Code===100&&t.Value==='AcDbLight')+1;let end=start;while(end<a.length&&a[end].Code!==1001&&a[end].Code!==0)end++;return a.slice(start,end);}
export function LightWire(version,binary,kind,reverse){const tags=LightTags(version,kind,reverse);if(reverse&&!binary){const end=tags.findIndex(t=>t.Code===1001),marker=tags.findIndex(t=>t.Code===100&&t.Value==='AcDbLight');for(let i=end;i>marker;i--)tags.splice(i,0,new DxfTag(999,'LIGHT 0 ENDSEC 1001'));}const input=new MemoryStream(RawFixtureBytes(tags,binary));try{
  let doc=DxfDocument.Load(input);Check(doc!==null,'LIGHT input rejected.');const source=single(doc.Entities.Lights);AssertLight(source,kind);doc.Entities.Add(source.Clone());
  for(let cycle=0;cycle<3;cycle++){const output=new MemoryStream();try{if(version<DxfVersion.AutoCad2007){if(GetTypedIOConfiguration()==='Debug')Throws(NotSupportedException,()=>doc.Save(output,binary));else Check(!doc.Save(output,binary),'Unsupported LIGHT export accepted.');Equal(0,output.Length,'Version preflight wrote data');return;}
    const transport=cycle%2===0?binary:!binary;Check(doc.Save(output,transport),'LIGHT save failed.');output.Position=0;const raw=DxfRawDocument.Load(output);
    for(const record of raw.Sections.flatMap(s=>s.Records).filter(r=>r.Name==='LIGHT')){const packet=payload(record.Tags);for(const expected of payload(LightTags(version,kind,false)))if(expected.Code!==1)Equal(expected.Value,single(packet.filter(t=>t.Code===expected.Code)).Value,'Exact LIGHT wire field');}
    if(cycle===0&&!reverse)OleWriteArtifact(`light-${VersionName(version)}-${BooleanName(binary)}-${kind}.dxf`,output.ToArray());output.Position=0;doc=DxfDocument.Load(output);Check(doc!==null,'LIGHT reload failed.');Equal(2,Array.from(doc.Entities.Lights).length,'LIGHT clone count');for(const light of doc.Entities.Lights)AssertLight(light,kind);vectorEqual(new Vector3(20,30,40),single(doc.Entities.Lines).StartPoint,'Following entity');
  }finally{output.Dispose();}}Check(input.CanRead,'Caller stream was closed.');
}finally{input.Dispose();}}
export function LightPlacement(version,binary,placement){const doc=new DxfDocument(version),light=LoadTestLight().Clone();switch(placement){case 0:doc.Entities.Add(light);break;case 1:doc.Layouts.Add(new Layout('Lighting'));doc.Entities.ActiveLayout='Lighting';doc.Entities.Add(light);doc.Entities.ActiveLayout='Model';break;case 2:{const inner=new Block('InnerLight');inner.Entities.Add(light);const outer=new Block('OuterLight');outer.Entities.Add(new Insert(inner));doc.Entities.Add(new Insert(outer));break;}default:{const unused=new Block('UnusedLight');unused.Entities.Add(light);doc.Blocks.Add(unused);}}
  const output=new MemoryStream();try{output.Write(Uint8Array.of(19,23,47));output.Position=1;const handle=light.Handle,seed=doc.DrawingVariables.HandleSeed;
    if(version<DxfVersion.AutoCad2007){if(GetTypedIOConfiguration()==='Debug')Throws(NotSupportedException,()=>doc.Save(output,binary));else Check(!doc.Save(output,binary),'Legacy LIGHT admitted.');Equal(Uint8Array.of(19,23,47),output.ToArray(),'Preflight modified existing bytes.');Equal(1,output.Position,'Preflight moved stream');Equal(seed,doc.DrawingVariables.HandleSeed,'Preflight allocated handles');Equal(handle,light.Handle,'Preflight changed identity');}
    else{output.SetLength(0);output.Position=0;Check(doc.Save(output,binary),'Placed LIGHT save failed.');output.Position=0;const copy=DxfDocument.Load(output);Check(copy!==null,'Placed LIGHT reload failed.');AssertLight(single(Array.from(copy.Blocks).flatMap(b=>Array.from(b.Entities)).filter(e=>e instanceof Light)),3);}
  }finally{output.Dispose();}
}
export function LightInvalid(version,binary,failure){const tags=LightTags(version,2,false),at=tags.findIndex(t=>t.Code===100&&t.Value==='AcDbLight'),set=(c,v)=>{tags[tags.findIndex(t=>t.Code===c)]=new DxfTag(c,v);};switch(failure){case 0:tags.splice(at+1,0,new DxfTag(40,2));break;case 1:set(70,4);break;case 2:set(72,-1);break;case 3:tags.splice(tags.findIndex(t=>t.Code===31),1);break;case 4:set(40,-1);break;case 5:set(91,-1);break;case 6:tags[at]=new DxfTag(100,'AcDbPoint');break;case 7:tags.splice(at+1,0,new DxfTag(100,'AcDbLight'));break;case 8:tags.splice(at+1,0,new DxfTag(101,'Embedded Object'));break;default:set(73,2);}
  const input=new MemoryStream(RawFixtureBytes(tags,binary));try{if(GetTypedIOConfiguration()==='Debug')Throws(InvalidDataException,()=>DxfDocument.Load(input));else Check(DxfDocument.Load(input)===null,'Malformed LIGHT accepted.');Check(input.CanRead,'Rejected LIGHT closed caller stream.');}finally{input.Dispose();}
}
export function LightApi(){const light=LoadTestLight();let copy=light.Clone();AssertLight(copy,3);Check(copy.Handle===null&&copy.Owner===null,'Clone copied identity/owner.');Check(copy.XData.get_Item('LIGHT_TEST')!==light.XData.get_Item('LIGHT_TEST'),'Clone shares XData.');Check(copy.Color!==light.Color&&copy.Layer!==light.Layer,'Clone shares tables/color.');
  for(const bad of [NaN,-Infinity,Infinity,-1])for(const key of ['Intensity','AttenuationStartLimit','AttenuationEndLimit','HotspotAngle','FalloffAngle'])Throws(ArgumentOutOfRangeException,()=>{light[key]=bad;});
  Throws(ArgumentOutOfRangeException,()=>{light.Position=new Vector3(NaN,0,0);});Throws(ArgumentOutOfRangeException,()=>{light.Target=new Vector3(0,Infinity,0);});Throws(ArgumentOutOfRangeException,()=>{light.ShadowMapSoftness=-1;});Throws(ArgumentNullException,()=>{light.Name=null;});AssertLight(light,3);
  const block=new Block('ClonedLight');block.Entities.Add(copy);const insert=new Insert(block,new Vector3(10,20,30));insert.Scale=new Vector3(2,2,2);const clonedInsert=insert.Clone(),clonedLight=single(Array.from(clonedInsert.Block.Entities).filter(e=>e instanceof Light));clonedLight.Name='changed';Equal('Lamp Żółć',copy.Name,'INSERT clone aliased light');
  const exploded=single(Array.from(insert.Explode()).filter(e=>e instanceof Light));vectorEqual(new Vector3(14,14,40),exploded.Position,'INSERT explosion position');Equal(4096,exploded.AttenuationEndLimit,'INSERT explosion attenuation');copy=light.Clone();const doc=new DxfDocument();doc.Entities.Add(copy);Check(doc.Entities.Remove(copy),'LIGHT removal failed.');Check(!Array.from(doc.Entities.Lights).length,'LIGHT remained after removal.');
}
export function LightTransform(operation){const light=LoadTestLight(),oldPosition=light.Position,oldTarget=light.Target;
  const matrix=operation===0?Matrix3.Identity:operation===1?Matrix3.Multiply(Matrix3.RotationX(.3),Matrix3.RotationZ(-.6)):operation===2?Matrix3.Multiply(Matrix3.Reflection(Vector3.UnitX),Matrix3.Scale(3)):operation===3?Matrix3.Scale(1,2,3):operation===4?new Matrix3(1,.2,0,0,1,0,0,0,1):operation===5?Matrix3.Scale(0):Matrix3.Scale(Number.MAX_VALUE),translation=new Vector3(17,-23,31);
  if(operation>=3){Throws(ArgumentException,()=>light.TransformBy(matrix,translation));AssertLight(light,3);return;}
  light.TransformBy(matrix,translation);vectorEqual(Vector3.Add(Matrix3.Multiply(matrix,oldPosition),translation),light.Position,'Transformed light position');vectorEqual(Vector3.Add(Matrix3.Multiply(matrix,oldTarget),translation),light.Target,'Transformed light target');Near(operation===2?6144:2048,light.AttenuationEndLimit,'Attenuation distance scaling');Equal(37.5,light.HotspotAngle,'Transform changed angle');Equal(1.2500000000000002,light.Intensity,'Transform changed authored intensity');
}
