// Port of pinned LwPolylineIntegrityTests.cs. Native allocation assertions remain unregistered.
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { DxfDocument, DxfTag, MemoryStream, Polyline2D, Polyline2DVertex, Vector2, Vector3 } from '../../index.js';
import { InvalidDataException } from '../../runtime/Errors.js';
import { GetTypedIOConfiguration } from '../../runtime/TypedDocumentIO.js';
import { RawFixtureBytes } from './RawDocumentTests.js';
import { Run, Check, Equal, SupportedVersions, VersionName, HeaderVersion, BooleanName } from './TestHarness.js';
const single=items=>{const a=Array.from(items);Equal(1,a.length,'Expected one item');return a[0];};
const artifacts=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../../artifacts/conformance/fixtures');
function artifact(name,bytes){fs.mkdirSync(artifacts,{recursive:true});fs.writeFileSync(path.join(artifacts,name),bytes);}
export function RegisterLwPolylineIntegrityTests(){for(const v of SupportedVersions)for(const b of [false,true]){const suffix=`${VersionName(v)}/${BooleanName(b)}`;
  for(let o=0;o<8;o++)Run(`lwpolyline/vertex-packet/${suffix}/${o}`,()=>LwPolylinePacket(v,b,o));for(let m=0;m<14;m++)Run(`lwpolyline/malformed/${suffix}/${m}`,()=>LwPolylineMalformed(v,b,m));
  // The twelve declared-count-allocation identities require their native allocation assertion.
  Run(`lwpolyline/empty-count/${suffix}`,()=>LwPolylineEmpty(v,b));for(const c of [false,true])Run(`lwpolyline/reverse-taper/${suffix}/${BooleanName(c)}`,()=>LwPolylineReverse(v,b,c));
}}
export function LwPolylineIntegrityTags(version,order){const tags=[[0,'SECTION'],[2,'HEADER'],[9,'$ACADVER'],[1,HeaderVersion(version)],[9,'$DWGCODEPAGE'],[3,'ANSI_1252'],[0,'ENDSEC'],[0,'SECTION'],[2,'ENTITIES'],[0,'LWPOLYLINE'],[5,'200'],[100,'AcDbEntity'],[8,'0'],[100,'AcDbPolyline'],[90,3],[70,1],[38,2.5],[39,-.75]].map(([c,v])=>new DxfTag(c,v));
  for(let i=0;i<3;i++){tags.push(new DxfTag(10,i*3-.125));const optional=[new DxfTag(40,i+.25),new DxfTag(41,i+1.5),new DxfTag(42,(i-1)*.5)];for(let j=0;j<3;j++)if(order&(1<<j))tags.push(optional[j]);tags.push(new DxfTag(20,i*i+.375));for(let j=2;j>=0;j--)if(!(order&(1<<j)))tags.push(optional[j]);}
  tags.push(...[[210,0],[220,0],[230,1],[1001,'LW_PACKET'],[1000,'after vertices'],[1070,73],[0,'LINE'],[5,'201'],[100,'AcDbEntity'],[8,'0'],[100,'AcDbLine'],[10,91],[20,-37],[30,0],[11,12],[21,14],[31,0],[0,'ENDSEC'],[0,'EOF']].map(([c,v])=>new DxfTag(c,v)));return tags;
}
function verifyPacket(doc){const p=single(doc.Entities.Polylines2D);Equal(3,p.Vertexes.Count,'LWPOLYLINE vertex count');Check(p.IsClosed,'LWPOLYLINE closed flag lost');Equal(2.5,p.Elevation,'LWPOLYLINE elevation');Equal(-.75,p.Thickness,'LWPOLYLINE thickness');for(let i=0;i<3;i++){const v=p.Vertexes.get_Item(i);Equal(new Vector2(i*3-.125,i*i+.375),v.Position,'Packet point');Equal(i+.25,v.StartWidth,'Packet start width');Equal(i+1.5,v.EndWidth,'Packet end width');Equal((i-1)*.5,v.Bulge,'Packet bulge');}Equal('after vertices',p.XData.get_Item('LW_PACKET').XDataRecord.get_Item(0).Value,'Following XData string');Equal(73,p.XData.get_Item('LW_PACKET').XDataRecord.get_Item(1).Value,'Following XData integer');Equal(new Vector3(91,-37,0),single(doc.Entities.Lines).StartPoint,'Following entity was consumed');}
export function LwPolylinePacket(version,binary,order){const tags=LwPolylineIntegrityTags(version,order);if(!binary){const first=tags.findIndex(t=>t.Code===10),last=tags.findIndex(t=>t.Code===1001);for(let i=last;i>first;i--)tags.splice(i,0,new DxfTag(999,'10 20 90 ENDSEC'));}
  const input=new MemoryStream(RawFixtureBytes(tags,binary));try{let doc=DxfDocument.Load(input);Check(doc!==null,'LWPOLYLINE packet rejected');for(let cycle=0;cycle<2;cycle++){verifyPacket(doc);const original=single(doc.Entities.Polylines2D),clone=original.Clone();Equal(original.Vertexes.get_Item(0).StartWidth,clone.Vertexes.get_Item(0).StartWidth,'Clone taper');clone.Vertexes.get_Item(0).StartWidth+=10;Equal(.25,original.Vertexes.get_Item(0).StartWidth,'Clone aliases vertex data');const output=new MemoryStream();try{Check(doc.Save(output,binary),'LWPOLYLINE packet save failed');if(cycle===0)artifact(`lwpolyline-packet-${VersionName(version)}-${BooleanName(binary)}-${order}.dxf`,output.ToArray());output.Position=0;doc=DxfDocument.Load(output);Check(doc!==null,'LWPOLYLINE packet reload failed');}finally{output.Dispose();}}Check(input.CanRead,'LWPOLYLINE reader closed input');}finally{input.Dispose();}}
export function LwPolylineReject(tags,binary){const input=new MemoryStream(RawFixtureBytes(tags,binary));try{if(GetTypedIOConfiguration()==='Debug'){let failure;try{DxfDocument.Load(input);}catch(error){failure=error;}Check(failure instanceof InvalidDataException,'Malformed LWPOLYLINE accepted or wrong failure type');Check(failure.message.includes('LWPOLYLINE'),'Missing LWPOLYLINE diagnostic');}else Check(DxfDocument.Load(input)===null,'Malformed LWPOLYLINE accepted');Check(input.CanRead,'Rejected LWPOLYLINE closed input');}finally{input.Dispose();}}
export function LwPolylineMalformed(version,binary,malformed){const tags=LwPolylineIntegrityTags(version,0),count=tags.findIndex(t=>t.Code===90),x=tags.findIndex(t=>t.Code===10),y=x+1,next=tags.findIndex((t,i)=>i>x&&t.Code===10),finalY=tags.findIndex((t,i)=>i>next&&t.Code===10)+1;
  switch(malformed){case 0:tags.splice(count,1);break;case 1:tags[count]=new DxfTag(90,-1);break;case 2:tags[count]=new DxfTag(90,2);break;case 3:tags[count]=new DxfTag(90,4);break;case 4:tags.splice(count+1,0,new DxfTag(90,3));break;case 5:tags.splice(x,1);break;case 6:tags.splice(y,1);break;case 7:tags.splice(y+1,0,new DxfTag(20,123));break;case 8:tags.splice(x,0,new DxfTag(40,1));break;case 9:tags.splice(x,0,new DxfTag(41,1));break;case 10:tags.splice(x,0,new DxfTag(42,.5));break;case 11:tags.splice(finalY,1);break;case 12:tags.splice(y,0,new DxfTag(10,123));break;case 13:tags[count]=new DxfTag(90,0);break;}LwPolylineReject(tags,binary);
}
export function LwPolylineEmpty(version,binary){const tags=LwPolylineIntegrityTags(version,0);tags[tags.findIndex(t=>t.Code===90)]=new DxfTag(90,0);const start=tags.findIndex(t=>t.Code===10),end=tags.findIndex(t=>t.Code===210);tags.splice(start,end-start);const input=new MemoryStream(RawFixtureBytes(tags,binary));try{const doc=DxfDocument.Load(input);Check(doc!==null,'Exact zero vertex count rejected');Equal(0,single(doc.Entities.Polylines2D).Vertexes.Count,'Empty vertex count');Equal(1,Array.from(doc.Entities.Lines).length,'Empty vertex entity consumed following line');}finally{input.Dispose();}}
function edgePoint(a,b,f){const p=a.Position,q=b.Position,dx=q.X-p.X,dy=q.Y-p.Y;if(a.Bulge===0)return new Vector2(p.X+dx*f,p.Y+dy*f);const scale=(1-a.Bulge*a.Bulge)/(4*a.Bulge),cx=(p.X+q.X)*.5-dy*scale,cy=(p.Y+q.Y)*.5+dx*scale,ox=p.X-cx,oy=p.Y-cy,angle=4*Math.atan(a.Bulge)*f;return new Vector2(cx+ox*Math.cos(angle)-oy*Math.sin(angle),cy+ox*Math.sin(angle)+oy*Math.cos(angle));}
function verifyReverse(original,reversed){const count=original.Vertexes.Count,edges=original.IsClosed?count:count-1;for(let i=0;i<edges;i++){const a=reversed.Vertexes.get_Item(i),b=reversed.Vertexes.get_Item((i+1)%count),source=single(Array.from({length:edges},(_,j)=>j).filter(j=>original.Vertexes.get_Item(j).Position.Equals(b.Position)&&original.Vertexes.get_Item((j+1)%count).Position.Equals(a.Position))),oldA=original.Vertexes.get_Item(source),oldB=original.Vertexes.get_Item((source+1)%count);Equal(oldA.EndWidth,a.StartWidth,'Reversed taper start');Equal(oldA.StartWidth,a.EndWidth,'Reversed taper end');for(let sample=0;sample<=8;sample++){const t=sample/8;Check(Vector2.Distance(edgePoint(oldA,oldB,1-t),edgePoint(a,b,t))<1e-11,'Reversal changed edge locus');const oldWidth=oldA.StartWidth*t+oldA.EndWidth*(1-t),newWidth=a.StartWidth*(1-t)+a.EndWidth*t;Check(Math.abs(oldWidth-newWidth)<1e-12,'Reversal changed taper geometry');}}}
export function LwPolylineReverse(version,binary,closed){const vertices=[[-3,2,1,2,0],[1,-1,3,5,.25],[6,4,.5,1.5,-.5],[9,-2,7,9,.75]].map(([x,y,start,end,bulge])=>{const v=new Polyline2DVertex(x,y);v.StartWidth=start;v.EndWidth=end;v.Bulge=bulge;return v;});const original=new Polyline2D(vertices,closed);original.Elevation=2.5;const reversed=original.Clone();reversed.Reverse();Equal(1,original.Vertexes.get_Item(0).StartWidth,'Reverse clone changed source');verifyReverse(original,reversed);const twice=reversed.Clone();twice.Reverse();for(let i=0;i<original.Vertexes.Count;i++){const a=original.Vertexes.get_Item(i),b=twice.Vertexes.get_Item(i);for(const [property,label]of [['Position','position'],['StartWidth','start width'],['EndWidth','end width'],['Bulge','bulge']]){if(property==='Bulge'&&a[property]===0&&b[property]===0)continue;Equal(a[property],b[property],'Double reverse '+label);}}
  const doc=new DxfDocument(version);doc.Entities.Add(original);doc.Entities.Add(reversed);const output=new MemoryStream();try{Check(doc.Save(output,binary),'Reversal save failed');artifact(`lwpolyline-reverse-${VersionName(version)}-${BooleanName(binary)}-${BooleanName(closed)}.dxf`,output.ToArray());output.Position=0;const loaded=DxfDocument.Load(output);Check(loaded!==null,'Reversal reload failed');const pair=Array.from(loaded.Entities.Polylines2D);verifyReverse(pair[0],pair[1]);}finally{output.Dispose();}}
