// Complete port of pinned SectionManagerMembershipTests.cs; source assertions retained.
import { DxfDocument, DxfVersion, Section, DxfStoredSectionManager, DxfTag, DxfDictionary, DxfXRecord, XData, XDataRecord, XDataCode, ApplicationRegistry, MemoryStream, DxfRawDocument } from '../../node-entry.js';
import { ArgumentException, InvalidOperationException, NotSupportedException } from '../../runtime/Errors.js';
import { Run, Check, Equal, Throws, SupportedVersions, VersionName, BooleanName } from './TestHarness.js';
import { OleSingle } from './Ole2FrameTests.js';
import { SectionExample } from './SectionTests.js';
import { SectionManagerFixture, SectionManagerLoad, SectionManagerSave, SectionManagerNativeBytes } from './SectionManagerTests.js';
import { OwnershipTagValues } from './SunTests.js';
const A=x=>Array.from(x),same=(x,y)=>{x=A(x);y=A(y);return x.length===y.length&&x.every((v,i)=>v===y[i]);};
export const SectionMembershipManager=doc=>OleSingle(A(doc.Objects.Items).filter(x=>x instanceof DxfStoredSectionManager));
export function RegisterSectionManagerMembershipTests(){
 for(const v of SupportedVersions.filter(v=>v>=DxfVersion.AutoCad2007))for(const s of ['SECTION_MANAGER','SECTIONMANAGER'])for(const b of [false,true]){const suffix=`${VersionName(v)}/${s}/${BooleanName(b)}`;Run('section-membership/edit/'+suffix,()=>SectionMembershipEdit(v,s,b));Run('section-membership/mapping/'+suffix,()=>SectionMembershipMap(v,s,b));Run('section-membership/metadata/'+suffix,()=>SectionMembershipMetadata(v,s,b));}
 for(const b of [false,true]){for(const d of ['null-list','null-entry','detached','foreign','erased','excessive','enumerator-throws','dispose-throws','reentry','enumerator-root','enumerator-target','profile','reactors','root'])Run(`section-membership/rejected/${BooleanName(b)}/${d}`,()=>SectionMembershipRejected(b,d));Run('section-membership/maximum/'+BooleanName(b),()=>SectionMembershipMaximum(b));Run('section-membership/caught-reentry/'+BooleanName(b),()=>SectionMembershipCaughtReentry(b));}
 for(const i of [false,true])for(const o of [false,true])Run(`section-membership/native/${BooleanName(i)}/${BooleanName(o)}`,()=>SectionMembershipNative(i,o));
}
function SectionMembershipEdit(v,s,b){const doc=SectionManagerLoad(SectionManagerFixture(v,s),b),m=SectionMembershipManager(doc),first=m.Sections.get_Item(0),second=m.Sections.get_Item(1),oldSections=m.Sections,oldTags=m.Tags,third=SectionExample('SECTIONOBJECT');third.Name='Manager third';doc.Entities.Add(third);const handle=m.Handle,owner=m.Owner.Handle,seed=doc.NumHandles;
 m.ReplaceSections([second,third,second],false);Check(!m.RequiresFullUpdate&&same(m.Sections,[second,third,second]),'Explicit membership order/flag changed');Check(same(oldSections,[first,second,first])&&oldTags.get_Item(1).Value===1,'Previously returned membership/packet snapshot mutated');Equal(seed,doc.NumHandles,'Membership edit assigned handles');Equal(handle,m.Handle,'Manager identity changed');Equal(owner,m.Owner.Handle,'Manager owner changed');Throws(NotSupportedException,()=>m.Sections.Clear());Throws(NotSupportedException,()=>m.Tags.Clear());Check(doc.Entities.Remove(first),'Released original section remained referenced');Check(!doc.Entities.Remove(second)&&!doc.Entities.Remove(third),'New manager target was removable');Throws(InvalidOperationException,()=>doc.Objects.EraseSection(second));
 const again=SectionMembershipManager(SectionManagerSave(doc,b,`section-membership-edited-${VersionName(v)}-${s}-${BooleanName(b)}.dxf`));Equal(['Manager second','Manager third','Manager second'],A(again.Sections).map(s=>s.Name),'Edited packet reload changed order');Check(!again.RequiresFullUpdate,'Independent update flag changed');m.ReplaceSections([],true);Check(m.RequiresFullUpdate&&m.Sections.Count===0,'Explicit empty/update-true combination changed');Check(doc.Entities.Remove(second)&&doc.Entities.Remove(third),'Cleared manager retained incoming dependencies');SectionManagerSave(doc,b,`section-membership-empty-${VersionName(v)}-${s}-${BooleanName(b)}.dxf`);Throws(NotSupportedException,()=>doc.Objects.CloneObject(m,doc.Objects.Root,'MANAGER_COPY'));Throws(NotSupportedException,()=>doc.Objects.EraseOwnedTree(m));Equal(0,doc.Objects.Validate().Count,'Edited manager graph validation');
}
function SectionMembershipMap(v,s,b){const source=SectionManagerLoad(SectionManagerFixture(v,s),b),dest=SectionManagerLoad(SectionManagerFixture(v,s),b),original=SectionMembershipManager(source),target=SectionMembershipManager(dest),before=OwnershipTagValues(target.Tags),seed=dest.NumHandles;Throws(ArgumentException,()=>target.ReplaceSections(original.Sections,false));Equal(before,OwnershipTagValues(target.Tags),'Foreign identities changed manager packet');Equal(seed,dest.NumHandles,'Foreign membership attempt allocated handles');const map=new Map([[original.Sections.get_Item(0),target.Sections.get_Item(0)],[original.Sections.get_Item(1),target.Sections.get_Item(1)]]),requested=[original.Sections.get_Item(1),original.Sections.get_Item(0),original.Sections.get_Item(1)];target.ReplaceSections(requested.map(x=>map.get(x)),true);Check(A(target.Sections).every(s=>!A(original.Sections).includes(s)),'Mapped membership retained foreign section objects');Equal(['Manager first','Manager second','Manager first'],A(original.Sections).map(s=>s.Name),'Mapped membership edited source');SectionManagerSave(dest,b,`section-membership-mapped-${VersionName(v)}-${s}-${BooleanName(b)}.dxf`);Throws(NotSupportedException,()=>dest.Objects.CloneObject(original,dest.Objects.Root,'MANAGER_COPY'));}
function SectionMembershipMetadata(v,s,b){const doc=SectionManagerLoad(SectionManagerFixture(v,s),b),m=SectionMembershipManager(doc),first=m.Sections.get_Item(0),second=m.Sections.get_Item(1),data=new XData(new ApplicationRegistry('MEMBERSHIP_METADATA'));data.XDataRecord.Add(new XDataRecord(XDataCode.String,'Keep metadata'));data.XDataRecord.Add(new XDataRecord(XDataCode.DatabaseHandle,first.Handle));m.XData.Add(data);const extension=new DxfDictionary();doc.Objects.SetExtensionDictionary(m,extension);const entry=new DxfXRecord();entry.Data.Add(new DxfTag(1,'Keep extension'));extension.Add('ANNOTATION',entry,true);const packet=OwnershipTagValues(m.Tags),reactors=A(m.PersistentReactors),stored=m.XData.get_Item('MEMBERSHIP_METADATA');m.ReplaceSections([second],false);Check(m.ExtensionDictionary===extension&&extension.get_Item('ANNOTATION')===entry,'Membership edit changed extension graph');Check(same(m.PersistentReactors,reactors)&&m.XData.get_Item('MEMBERSHIP_METADATA')===stored,'Membership edit changed common metadata');Check(!doc.Entities.Remove(first),'Independent retained XData dependency was released with membership');m.XData.Remove('MEMBERSHIP_METADATA');Check(doc.Entities.Remove(first),'Cleared independent XData dependency remained');const again=SectionMembershipManager(SectionManagerSave(doc,b));Equal('Keep extension',again.ExtensionDictionary.get_Item('ANNOTATION').Data.get_Item(0).Value,'Extension payload changed on edited-manager save');Check(JSON.stringify(packet)!==JSON.stringify(OwnershipTagValues(m.Tags)),'Membership did not change public packet');}
export class SectionMembershipDisposingEnumerable {constructor(section){this.section=section;}GetEnumerator(){const section=this.section;let moved=false;return {get Current(){return section;},MoveNext(){if(moved)return false;moved=true;return true;},Reset(){throw new NotSupportedException();},Dispose(){throw new InvalidOperationException('Caller disposal failed');}};}}
function SectionMembershipRejected(b,d){const doc=SectionManagerLoad(SectionManagerFixture(DxfVersion.AutoCad2018),b),m=SectionMembershipManager(doc),first=m.Sections.get_Item(0),before=A(m.Sections),packet=OwnershipTagValues(m.Tags),flag=m.RequiresFullUpdate,foreignDoc=new DxfDocument(DxfVersion.AutoCad2018),foreign=SectionExample('SECTIONOBJECT');foreignDoc.Entities.Add(foreign);const erased=SectionExample('SECTIONOBJECT');doc.Entities.Add(erased);doc.Objects.EraseSection(erased);const candidate=SectionExample('SECTIONOBJECT');doc.Entities.Add(candidate);const seed=doc.NumHandles;
 function* throwing(){yield first;throw new InvalidOperationException('Caller enumeration failed');}function* reentry(){yield first;m.ReplaceSections([],false);}function* root(){yield first;doc.Objects.Root.Remove('ACAD_SECTION_MANAGER');yield first;}function* remove(){yield candidate;Check(doc.Entities.Remove(candidate),'Caller target removal failed');}
 let members=[first];if(d==='null-list')members=null;else if(d==='null-entry')members=[first,null];else if(d==='detached')members=[new Section()];else if(d==='foreign')members=[foreign];else if(d==='erased')members=[erased];else if(d==='excessive')members=Array(65537).fill(first);else if(d==='enumerator-throws')members=throwing();else if(d==='dispose-throws')members=new SectionMembershipDisposingEnumerable(first);else if(d==='reentry')members=reentry();else if(d==='enumerator-root')members=root();else if(d==='enumerator-target')members=remove();else if(d==='profile')doc.DrawingVariables.AcadVer=DxfVersion.AutoCad2013;else if(d==='reactors')m.PersistentReactors.Add(doc.Objects.Root);else if(d==='root')doc.Objects.Root.Remove('ACAD_SECTION_MANAGER');let rejected=false;try{m.ReplaceSections(members,false);}catch(e){if(!(e instanceof ArgumentException||e instanceof InvalidOperationException))throw e;rejected=true;}Check(rejected,'Invalid manager membership request was accepted');Check(same(before,m.Sections)&&JSON.stringify(packet)===JSON.stringify(OwnershipTagValues(m.Tags))&&flag===m.RequiresFullUpdate,'Rejected membership request partially changed manager');Equal(seed,doc.NumHandles,'Rejected membership request allocated handles');if(['null-list','null-entry','detached','foreign','erased','excessive','enumerator-throws','dispose-throws','reentry','enumerator-target'].includes(d)){m.ReplaceSections([first],false);Check(m.Sections.Count===1&&!m.RequiresFullUpdate,'Failed edit left the manager locked');}}
function SectionMembershipCaughtReentry(b){const doc=SectionManagerLoad(SectionManagerFixture(DxfVersion.AutoCad2018),b),m=SectionMembershipManager(doc),first=m.Sections.get_Item(0),second=m.Sections.get_Item(1),old=m.Tags;let caught=false;function* members(){yield second;try{m.ReplaceSections([],true);}catch(e){if(!(e instanceof InvalidOperationException))throw e;caught=true;}Check(old===m.Tags,'Rejected nested edit mutated manager');yield first;}m.ReplaceSections(members(),false);Check(caught&&same(m.Sections,[second,first])&&!m.RequiresFullUpdate,'Caught nested edit prevented valid outer replacement');const again=SectionMembershipManager(SectionManagerSave(doc,b));Equal(['Manager second','Manager first'],A(again.Sections).map(s=>s.Name),'Outer replacement did not survive save');Check(!again.RequiresFullUpdate,'Outer replacement flag changed');}
function SectionMembershipMaximum(b){const doc=SectionManagerLoad(SectionManagerFixture(DxfVersion.AutoCad2018),b),m=SectionMembershipManager(doc),first=m.Sections.get_Item(0);m.ReplaceSections(Array(65536).fill(first),false);Equal(65536,m.Sections.Count,'Maximum membership rejected');Equal(65539,m.Tags.Count,'Maximum packet count');const again=SectionMembershipManager(SectionManagerSave(doc,b));Check(again.Sections.Count===65536&&A(again.Sections).every(s=>s===again.Sections.get_Item(0))&&!again.RequiresFullUpdate,'Maximum list collapsed repeated identities');}
function SectionMembershipNative(input,b){const bytes=SectionManagerNativeBytes(),s=new MemoryStream(bytes);try{const raw=DxfRawDocument.Load(s);s.Position=0;const doc=input?SectionManagerLoad(raw,true):DxfDocument.Load(s),m=SectionMembershipManager(doc),section=OleSingle(m.Sections),old=m.Tags,handle=m.Handle,owner=m.Owner,reactors=A(m.PersistentReactors),seed=doc.NumHandles;m.ReplaceSections([section,section],true);Equal(seed,doc.NumHandles,'Native membership edit allocated handles');Equal(handle,m.Handle,'Native manager identity changed');Check(owner===m.Owner&&same(reactors,m.PersistentReactors),'Native manager common ownership/reactors changed');Check(old.Count===4&&old.get_Item(1).Value===0,'Native original packet snapshot mutated');const again=SectionMembershipManager(SectionManagerSave(doc,b,`section-membership-native-${BooleanName(input)}-${BooleanName(b)}.dxf`));Check(again.RequiresFullUpdate&&again.Sections.Count===2&&again.Sections.get_Item(0)===again.Sections.get_Item(1),'Native edit reload lost repeated identity');Equal('228',again.Sections.get_Item(0).Handle,'Native target identity changed');Equal('229',again.Handle,'Native manager identity changed on output');}finally{s.Dispose();}}
