// Complete port of pinned SectionManagerLifecycleTests.cs. Internal reflection
// used solely to read/write NumHandles maps to the existing JavaScript adapter.
import { DxfDocument, DxfVersion, Section, DxfStoredSectionManager, DxfXRecord, DxfDictionary, DxfDictionaryWithDefault, DxfTag, DxfClass, DictionaryCloningFlags, Line, Vector3, Block, AttributeDefinition, Insert, XData, XDataRecord, XDataCode, ApplicationRegistry, DxfSectionSettings, DxfSectionTypeSettings, HeaderVariable, DxfRawDocument, MemoryStream } from '../../node-entry.js';
import { ArgumentException, InvalidOperationException, NotSupportedException } from '../../runtime/Errors.js';
import { Run, Check, Equal, Throws, SupportedVersions, VersionName, BooleanName } from './TestHarness.js';
import { OleSingle } from './Ole2FrameTests.js';
import { SectionExample, SectionBytes } from './SectionTests.js';
import { SectionManagerFixture, SectionManagerRecord, SectionManagerLoad, SectionManagerSave, SectionManagerNativeBytes } from './SectionManagerTests.js';
import { SectionMembershipManager, SectionMembershipDisposingEnumerable } from './SectionManagerMembershipTests.js';
const A=x=>Array.from(x),same=(x,y)=>{x=A(x);y=A(y);return x.length===y.length&&x.every((v,i)=>v===y[i]);},T=(c,v)=>new DxfTag(c,v),longMax=9223372036854775807n;
export function RegisterSectionManagerLifecycleTests(){
 for(const v of SupportedVersions.filter(v=>v>=DxfVersion.AutoCad2007))for(const b of [false,true]){Run(`manager-lifecycle/created/${VersionName(v)}/${BooleanName(b)}`,()=>ManagerLifecycleCreated(v,b));Run(`manager-lifecycle/empty/${VersionName(v)}/${BooleanName(b)}`,()=>ManagerLifecycleEmpty(v,b));}
 for(const b of [false,true]){
  for(const f of ['null-list','null-entry','detached','foreign','erased','excessive','move-throws','get-throws','dispose-throws','reentry','caught-reentry','anchor','lower-anchor','existing','orphan','opaque','class','profile','seed','get-anchor','dispose-anchor','dispose-class','dispose-profile','dispose-target','dispose-seed'])Run(`manager-lifecycle/create-reject/${BooleanName(b)}/${f}`,()=>ManagerLifecycleCreateRejected(b,f));
  for(const f of ['xrecord330','xrecord340','xdata','reactor','default','settings','header','attribute-xdata','owned-incoming'])Run(`manager-lifecycle/incoming/${BooleanName(b)}/${f}`,()=>ManagerLifecycleIncoming(b,f));
  for(const f of ['foreign','erased','null','profile','root','reactors','opaque-owned'])Run(`manager-lifecycle/erase-reject/${BooleanName(b)}/${f}`,()=>ManagerLifecycleEraseRejected(b,f));
  for(const d of ['absent','count-absent','stale','edited'])Run(`manager-lifecycle/class/${BooleanName(b)}/${d}`,()=>ManagerLifecycleClass(b,d));
  for(const f of ['section-reactor','root-reactor','section-xdata','root-xdata','unrelated-line'])Run(`manager-lifecycle/required-metadata/${BooleanName(b)}/${f}`,()=>ManagerLifecycleRequiredMetadata(b,f));
  for(const [name,fn] of [['maximum',ManagerLifecycleMaximum],['retained-allocation',ManagerLifecycleRetainedAllocation],['owned-aliases',ManagerLifecycleOwnedAliases],['profile-save',ManagerLifecycleProfileSave]])Run(`manager-lifecycle/${name}/${BooleanName(b)}`,()=>fn(b));
 }
 for(const i of [false,true])for(const o of [false,true])Run(`manager-lifecycle/native/${BooleanName(i)}/${BooleanName(o)}`,()=>ManagerLifecycleNative(i,o));
}
function ManagerLifecycleDocument(version=DxfVersion.AutoCad2018){const doc=new DxfDocument(version),first=SectionExample('SECTIONOBJECT'),second=SectionExample('SECTIONOBJECT');first.Name='Lifecycle first';second.Name='Lifecycle second';doc.Entities.Add(first);doc.Entities.Add(second);return {doc,first,second};}
function ManagerLifecycleClassDefinition(count){const d=new DxfClass('SECTION_MANAGER','AcDbSectionManager','ObjectDBX Classes');d.ProxyFlags=1024;d.InstanceCount=count;return d;}
function ManagerLifecycleReject(action){let rejected=false;try{action();}catch(e){if(!(e instanceof ArgumentException||e instanceof InvalidOperationException||e instanceof NotSupportedException))throw e;rejected=true;}Check(rejected,'Invalid manager lifecycle operation was accepted');}
function ManagerLifecycleCreated(v,b){const {doc,first,second}=ManagerLifecycleDocument(v),root=doc.Objects.Root;root.IsHardOwner=false;root.Cloning=DictionaryCloningFlags.UseClone;const marker=new DxfXRecord();marker.Data.Add(T(1,'unrelated root entry'));root.Add('LIFECYCLE_KEEP',marker,true);const requested=[first,second,first],seed=doc.NumHandles,m=doc.Objects.CreateSectionManager(requested,false);requested.length=0;
 Check(same(m.Sections,[first,second,first])&&!m.RequiresFullUpdate,'Creation lost ordered actual repeated identities or flag');Equal(seed+1n,doc.NumHandles,'Creation allocated more than manager handle');Check(m.Owner===root&&same(m.PersistentReactors,[root]),'Canonical owner/reactor mismatch');Check(root.get_Item('ACAD_SECTION_MANAGER')===m&&!OleSingle(A(root.Entries).filter(e=>e.Name==='ACAD_SECTION_MANAGER')).IsHardOwner,'Canonical soft root entry mismatch');Check(!root.IsHardOwner&&root.Cloning===DictionaryCloningFlags.UseClone&&root.get_Item('LIFECYCLE_KEEP')===marker,'Creation rewrote existing root metadata');Check(!doc.Entities.Remove(first)&&!doc.Entities.Remove(second),'Created manager does not guard targets');Throws(NotSupportedException,()=>doc.Objects.EraseOwnedTree(m));Throws(NotSupportedException,()=>doc.Objects.CloneObject(m,root,'COPY'));
 const loaded=SectionManagerSave(doc,b);SectionManagerSave(loaded,b,`manager-lifecycle-created-${VersionName(v)}-${BooleanName(b)}.dxf`);const again=SectionMembershipManager(loaded),oldHandle=again.Handle,oldSections=again.Sections,oldTags=again.Tags,survivors=A(loaded.Entities.Sections),keep=loaded.Objects.Root.get_Item('LIFECYCLE_KEEP');again.ReplaceSections([again.Sections.get_Item(1)],true);Check(oldSections.Count===3&&oldTags.Count===6,'Explicit edit mutated prior creation snapshots');loaded.Objects.EraseSectionManager(again);Check(again.IsErased&&again.Database===null&&again.Owner===null&&again.Handle===oldHandle,'Erasure did not preserve terminal inspection identity');Check(again.Sections.Count===1&&again.RequiresFullUpdate&&oldSections.Count===3,'Erasure changed stored inspection snapshots');Check(survivors.every(s=>loaded.GetObjectByHandle(s.Handle)===s),'Manager erasure cascaded into members');Check(loaded.Objects.Root.get_Item('LIFECYCLE_KEEP')===keep&&!loaded.Objects.Root.Contains('ACAD_SECTION_MANAGER'),'Manager erasure changed unrelated root entries');Equal(0,loaded.Classes.get_Item('SECTION_MANAGER').InstanceCount,'Erasure left stale class count');SectionManagerSave(loaded,b,`manager-lifecycle-erased-${VersionName(v)}-${BooleanName(b)}.dxf`);ManagerLifecycleReject(()=>loaded.Objects.Root.Add('REVIVE',again));const replacement=loaded.Objects.CreateSectionManager([survivors[1],survivors[0],survivors[1]],true);Check(replacement.Handle!==oldHandle&&replacement!==again,'Explicit recreation reused terminal identity');Equal(1,loaded.Classes.get_Item('SECTION_MANAGER').InstanceCount,'Recreation did not update class count');SectionManagerSave(loaded,b,`manager-lifecycle-recreated-${VersionName(v)}-${BooleanName(b)}.dxf`);Equal(0,loaded.Objects.Validate().Count,'Recreated graph validation');
}
function ManagerLifecycleEmpty(v,b){const doc=new DxfDocument(v),m=doc.Objects.CreateSectionManager([],true);Check(m.RequiresFullUpdate&&m.Sections.Count===0&&m.Tags.Count===3,'Explicit empty manager packet changed');Check(!doc.Classes.Contains('SECTION_MANAGER'),'Creation synthesized class before output');doc.AnalyzeVersionCompatibility(v);Check(!doc.Classes.Contains('SECTION_MANAGER'),'Analysis synthesized class');const loaded=SectionManagerSave(doc,b,`manager-lifecycle-empty-${VersionName(v)}-${BooleanName(b)}.dxf`);Check(SectionMembershipManager(loaded).Sections.Count===0,'Empty manager did not reload');doc.Objects.EraseSectionManager(m);Check(!doc.Classes.Contains('SECTION_MANAGER'),'Erasure synthesized absent class');}
class ManagerLifecycleEnumerable{constructor(section,get=null,dispose=null){this.section=section;this.get=get;this.dispose=dispose;}GetEnumerator(){this.get?.();const {section,dispose}=this;let moved=false;return {get Current(){return section;},MoveNext(){if(moved)return false;moved=true;return true;},Reset(){throw new NotSupportedException();},Dispose(){dispose?.();}};}}
function ManagerLifecycleCreateRejected(b,fault){let {doc,first}=ManagerLifecycleDocument();const {first:foreign}=ManagerLifecycleDocument();Equal(first.Handle,foreign.Handle,'Foreign probe must have coinciding handle');const erased=SectionExample();doc.Entities.Add(erased);doc.Objects.EraseSection(erased);let members=[first],repair=null;
 function* throwing(){yield first;throw new InvalidOperationException('MoveNext failed');}function* reentry(caught){yield first;if(caught)ManagerLifecycleReject(()=>doc.Objects.CreateSectionManager([],false));else doc.Objects.CreateSectionManager([],false);}const anchor=()=>doc.Objects.Root.Add('ACAD_SECTION_MANAGER',new DxfXRecord());
 if(fault==='null-list')members=null;else if(fault==='null-entry')members=[first,null];else if(fault==='detached')members=[new Section()];else if(fault==='foreign')members=[foreign];else if(fault==='erased')members=[erased];else if(fault==='excessive')members=Array(65537).fill(first);else if(fault==='move-throws')members=throwing();else if(fault==='get-throws')members=new ManagerLifecycleEnumerable(first,()=>{throw new InvalidOperationException('GetEnumerator failed');});else if(fault==='dispose-throws')members=new SectionMembershipDisposingEnumerable(first);else if(fault==='reentry'||fault==='caught-reentry')members=reentry(fault==='caught-reentry');else if(fault==='anchor')anchor();else if(fault==='lower-anchor')doc.Objects.Root.Add('acad_section_manager',new DxfXRecord());else if(fault==='existing'||fault==='orphan'){doc.Objects.CreateSectionManager([],false);if(fault==='orphan')doc.Objects.Root.Remove('ACAD_SECTION_MANAGER');}else if(fault==='opaque'){const raw=SectionManagerFixture(DxfVersion.AutoCad2018),record=SectionManagerRecord(raw);doc=SectionManagerLoad(raw.WithRecord(record,[...record.Tags,T(1,'private')]),b);members=[A(doc.Entities.Sections)[0]];}else if(fault==='class')doc.Classes.Add(new DxfClass('SECTION_MANAGER','WrongClass','ObjectDBX Classes'));else if(fault==='profile')doc.DrawingVariables.AcadVer=DxfVersion.AutoCad2004;else if(fault==='seed')doc.NumHandles=longMax;else if(fault==='get-anchor')members=new ManagerLifecycleEnumerable(first,anchor);else if(fault==='dispose-anchor')members=new ManagerLifecycleEnumerable(first,null,anchor);else if(fault==='dispose-class')members=new ManagerLifecycleEnumerable(first,null,()=>doc.Classes.Add(new DxfClass('SECTION_MANAGER','WrongClass','ObjectDBX Classes')));else if(fault==='dispose-profile')members=new ManagerLifecycleEnumerable(first,null,()=>{doc.DrawingVariables.AcadVer=DxfVersion.AutoCad2004;});else if(fault==='dispose-target')members=new ManagerLifecycleEnumerable(first,null,()=>{Check(doc.Entities.Remove(first),'Caller removal failed');repair=()=>doc.Entities.Add(first);});else if(fault==='dispose-seed')members=new ManagerLifecycleEnumerable(first,null,()=>{doc.NumHandles=longMax;});
 const seed=doc.NumHandles,count=doc.Objects.Items.Count,old=A(doc.Objects.Items).filter(o=>['SECTION_MANAGER','SECTIONMANAGER'].includes(o.CodeName));ManagerLifecycleReject(()=>doc.Objects.CreateSectionManager(members,true));Check(same(old,A(doc.Objects.Items).filter(o=>['SECTION_MANAGER','SECTIONMANAGER'].includes(o.CodeName))),'Rejected creation registered partial manager');const added=['get-anchor','dispose-anchor'].includes(fault)?1:0;Equal(count+added,doc.Objects.Items.Count,'Rejected creation mutated object registration beyond caller changes');if(fault!=='dispose-seed')Equal(seed+BigInt(added),doc.NumHandles,'Rejected creation allocated beyond caller changes');else Equal(longMax,doc.NumHandles,'Caller seed mutation rolled back or advanced');if(['existing','orphan','opaque'].includes(fault))return;
 if(doc.Objects.Root.Contains('ACAD_SECTION_MANAGER'))doc.Objects.EraseOwnedTree(doc.Objects.Root.get_Item('ACAD_SECTION_MANAGER'));doc.Classes.Remove('SECTION_MANAGER');doc.DrawingVariables.AcadVer=DxfVersion.AutoCad2018;if(['seed','dispose-seed'].includes(fault))doc.NumHandles=4096n;repair?.();const recovery=doc.Objects.CreateSectionManager([first],false);Check(OleSingle(recovery.Sections)===first,'Rejected creation left database creation lock held');SectionManagerSave(doc,b);
}
function ManagerLifecycleIncoming(b,field){const {doc,first}=ManagerLifecycleDocument(),m=doc.Objects.CreateSectionManager([first],false),line=new Line(Vector3.Zero,Vector3.UnitX);doc.Entities.Add(line);let release;
 if(['xrecord330','xrecord340'].includes(field)){const r=new DxfXRecord();r.Data.Add(T(field==='xrecord330'?330:340,m.Handle));doc.Objects.Root.Add('BLOCKER',r);release=()=>r.Data.Clear();}else if(['xdata','attribute-xdata'].includes(field)){let carrier=line;if(field==='attribute-xdata'){const block=new Block('LIFECYCLE_ATTRIBUTE');block.AttributeDefinitions.Add(new AttributeDefinition('TAG'));const insert=new Insert(block);doc.Entities.Add(insert);carrier=OleSingle(insert.Attributes);}const d=new XData(new ApplicationRegistry('MANAGER_INCOMING'));d.XDataRecord.Add(new XDataRecord(XDataCode.DatabaseHandle,m.Handle));carrier.XData.Add(d);release=()=>carrier.XData.Remove('MANAGER_INCOMING');}else if(field==='reactor'){line.PersistentReactors.Add(m);release=()=>line.PersistentReactors.Remove(m);}else if(field==='default'){const d=new DxfDictionaryWithDefault();doc.Objects.Root.Add('DEFAULT',d);d.Default=m;release=()=>{d.Default=null;};}else if(field==='settings'){const settings=new DxfSectionSettings();settings.SetTypeSettings([new DxfSectionTypeSettings(1,0,[m],null,'',[])]);doc.Objects.SetSectionSettings(first,settings);release=()=>settings.SetTypeSettings([]);}else if(field==='header'){doc.DrawingVariables.AddCustomVariable(new HeaderVariable('$MANAGER_REF',330,m.Handle));release=()=>doc.DrawingVariables.RemoveCustomVariable('$MANAGER_REF');}else{const ext=new DxfDictionary(),note=new DxfXRecord();ext.Add('NOTE',note);doc.Objects.SetExtensionDictionary(m,ext);const record=new DxfXRecord();record.Data.Add(T(330,note.Handle));doc.Objects.Root.Add('BLOCKER',record);release=()=>record.Data.Clear();}
 const seed=doc.NumHandles,objects=A(doc.Objects.Items),sections=m.Sections,tags=m.Tags;Throws(InvalidOperationException,()=>doc.Objects.EraseSectionManager(m));Check(same(objects,doc.Objects.Items)&&!m.IsErased&&same(m.Sections,sections)&&m.Tags===tags,'Blocked erasure partially mutated graph or snapshots');Equal(seed,doc.NumHandles,'Blocked erasure allocated handles');release();doc.Objects.EraseSectionManager(m);Check(doc.GetObjectByHandle(first.Handle)===first,'Released erasure removed referenced section');SectionManagerSave(doc,b);
}
function ManagerLifecycleEraseRejected(b,fault){let {doc,first}=ManagerLifecycleDocument(),m=doc.Objects.CreateSectionManager([first],false),repair=null,selected=m;
 if(fault==='foreign')selected=new DxfDocument(DxfVersion.AutoCad2018).Objects.CreateSectionManager([],false);else if(fault==='null')selected=null;else if(fault==='erased')doc.Objects.EraseSectionManager(m);else if(fault==='profile'){doc.DrawingVariables.AcadVer=DxfVersion.AutoCad2013;repair=()=>{doc.DrawingVariables.AcadVer=DxfVersion.AutoCad2018;};}else if(fault==='root'){doc.Objects.Root.Remove('ACAD_SECTION_MANAGER');repair=()=>doc.Objects.Root.Add('ACAD_SECTION_MANAGER',m,false);}else if(fault==='reactors'){m.PersistentReactors.Add(first);repair=()=>m.PersistentReactors.Remove(first);}else if(fault==='opaque-owned'){const ext=new DxfDictionary(),note=new DxfXRecord();ext.Add('OPAQUE',note);doc.Objects.SetExtensionDictionary(m,ext);const stream=new MemoryStream(SectionBytes(doc,false));try{const raw=DxfRawDocument.Load(stream),row=OleSingle(A(raw.Sections).flatMap(s=>A(s.Records)).filter(r=>A(r.Tags).some(t=>t.Code===5&&t.Value===note.Handle))),t=A(row.Tags),start=t.findIndex(t=>t.Code===100);doc=SectionManagerLoad(raw.WithRecord(row,[...t.slice(0,start).map(t=>t.Code===0?T(0,'PRIVATE_MANAGER_NOTE'):t),T(100,'AcDbPrivateManagerNote'),T(1,'opaque')]),b);m=SectionMembershipManager(doc);selected=m;}finally{stream.Dispose();}}
 const objects=A(doc.Objects.Items),seed=doc.NumHandles,erased=m.IsErased;ManagerLifecycleReject(()=>doc.Objects.EraseSectionManager(selected));Check(same(objects,doc.Objects.Items)&&m.IsErased===erased,'Rejected erasure mutated registration');Equal(seed,doc.NumHandles,'Rejected erasure changed seed');repair?.();if(!['erased','opaque-owned'].includes(fault)){doc.Objects.EraseSectionManager(m);SectionManagerSave(doc,b);}
}
function ManagerLifecycleClass(b,declaration){const doc=new DxfDocument(DxfVersion.AutoCad2018);let definition=null;if(declaration!=='absent'){definition=ManagerLifecycleClassDefinition(declaration==='count-absent'?null:37);doc.Classes.Add(definition);}const m=doc.Objects.CreateSectionManager([],true);Check(definition===null?!doc.Classes.Contains('SECTION_MANAGER'):doc.Classes.get_Item('SECTION_MANAGER')===definition&&definition.InstanceCount===(declaration==='count-absent'?null:1),'Creation changed CLASS identity or absent/present count policy');if(declaration==='edited')Object.assign(definition,{ApplicationName:'Inspection metadata',ProxyFlags:123,WasProxy:true,IsEntity:true,InstanceCount:37});doc.AnalyzeVersionCompatibility(DxfVersion.AutoCad2013);Check(definition===null?!doc.Classes.Contains('SECTION_MANAGER'):definition.InstanceCount===(declaration==='count-absent'?null:declaration==='edited'?37:1),'Analysis mutated CLASS declaration');doc.Objects.EraseSectionManager(m);Check(definition===null?!doc.Classes.Contains('SECTION_MANAGER'):doc.Classes.get_Item('SECTION_MANAGER')===definition&&definition.InstanceCount===(declaration==='count-absent'?null:0),'Erasure changed CLASS identity or count absence');if(declaration==='edited')Check(definition.ApplicationName==='Inspection metadata'&&definition.ProxyFlags===123&&definition.WasProxy&&definition.IsEntity,'Erasure rewrote unrelated CLASS metadata');SectionManagerSave(doc,b);}
function ManagerLifecycleRequiredMetadata(b,fault){const {doc,first}=ManagerLifecycleDocument(),line=new Line(Vector3.Zero,Vector3.UnitX);doc.Entities.Add(line);const carrier=fault.startsWith('section')?first:fault.startsWith('root')?doc.Objects.Root:line;let callbackSeed=-1n,callbackObjects=null;const members=new ManagerLifecycleEnumerable(first,null,()=>{if(fault.endsWith('xdata')){const data=new XData(new ApplicationRegistry('MANAGER_REQUIRED_METADATA'));data.XDataRecord.Add(new XDataRecord(XDataCode.DatabaseHandle,'ABCDEF'));carrier.XData.Add(data);}else carrier.PersistentReactors.Add(new DxfXRecord());callbackSeed=doc.NumHandles;callbackObjects=A(doc.Objects.Items);});
 if(fault==='unrelated-line'){const m=doc.Objects.CreateSectionManager(members,false);Check(OleSingle(m.Sections)===first&&line.PersistentReactors.Count===1,'Creation validated unrelated metadata or rolled back caller changes');Equal(callbackSeed+1n,doc.NumHandles,'Creation with unrelated invalid metadata allocated unexpected handles');line.PersistentReactors.Clear();SectionManagerSave(doc,b);return;}
 Throws(InvalidOperationException,()=>doc.Objects.CreateSectionManager(members,false));Check(callbackObjects!==null&&same(callbackObjects,doc.Objects.Items)&&!doc.Objects.Root.Contains('ACAD_SECTION_MANAGER'),'Required metadata rejection partially installed manager');Equal(callbackSeed,doc.NumHandles,'Required metadata rejection allocated after caller callback');if(fault.endsWith('xdata'))carrier.XData.Remove('MANAGER_REQUIRED_METADATA');else carrier.PersistentReactors.Clear();Check(OleSingle(doc.Objects.CreateSectionManager([first],false).Sections)===first,'Required metadata rejection left creation locked');SectionManagerSave(doc,b);
}
function ManagerLifecycleMaximum(b){const {doc,first}=ManagerLifecycleDocument(),m=doc.Objects.CreateSectionManager(Array(65536).fill(first),false);Equal(65536,m.Sections.Count,'Maximum creation count rejected');const again=SectionMembershipManager(SectionManagerSave(doc,b));Check(again.Sections.Count===65536&&A(again.Sections).every(s=>s===again.Sections.get_Item(0)),'Maximum creation collapsed repeated identities');}
function ManagerLifecycleRetainedAllocation(b){const {doc}=ManagerLifecycleDocument(),block=new Block('MANAGER_HANDLE_RESERVATION');block.AttributeDefinitions.Add(new AttributeDefinition('TAG'));doc.Entities.Add(new Insert(block));const loaded=SectionManagerSave(doc,b),attribute=OleSingle(OleSingle(loaded.Entities.Inserts).Attributes);Check(loaded.GetObjectByHandle(attribute.Handle)===null,'Retained allocation probe must use owner-held identity');const stream=new MemoryStream(SectionBytes(loaded,false));try{const raw=DxfRawDocument.Load(stream),handles=new Set(A(raw.Sections).filter(s=>s.Name!=='HEADER').flatMap(s=>A(s.Records)).flatMap(r=>A(r.Tags).filter(t=>t.Code===5).map(t=>t.Value.toUpperCase()))),normalSeed=loaded.NumHandles;loaded.NumHandles=BigInt('0x'+attribute.Handle);const m=loaded.Objects.CreateSectionManager(loaded.Entities.Sections,false);Check(!handles.has(m.Handle.toUpperCase())&&attribute.Owner!==null,'Manager allocation captured live retained ATTRIB/ENDBLK identity');loaded.NumHandles=normalSeed>loaded.NumHandles?normalSeed:loaded.NumHandles;SectionManagerSave(loaded,b);}finally{stream.Dispose();}}
function ManagerLifecycleOwnedAliases(b){const {doc,first}=ManagerLifecycleDocument(),m=doc.Objects.CreateSectionManager([first],false);doc.Objects.Root.Add('MANAGER_ALIAS',m,true);const ext=new DxfDictionary(),note=new DxfXRecord();note.Data.Add(T(1,'owned note'));ext.Add('NOTE',note);ext.Add('ALIAS',note);doc.Objects.SetExtensionDictionary(m,ext);const arbitrary=new DxfXRecord();arbitrary.Data.Add(T(320,m.Handle));doc.Objects.Root.Add('ARBITRARY',arbitrary);const handles=[m.Handle,ext.Handle,note.Handle],seed=doc.NumHandles;doc.Objects.EraseSectionManager(m);Check(handles.every(h=>doc.GetObjectByHandle(h)===null)&&ext.IsErased&&note.IsErased,'Explicit erase left typed owned metadata registered');Check(!doc.Objects.Root.Contains('MANAGER_ALIAS')&&!doc.Objects.Root.Contains('ACAD_SECTION_MANAGER')&&doc.Objects.Root.get_Item('ARBITRARY')===arbitrary,'Alias erasure or arbitrary handle policy changed');Equal(seed,doc.NumHandles,'Erasure allocated handles');Check(doc.Entities.Remove(first),'Erasure retained outgoing dependency');SectionManagerSave(doc,b);}
function ManagerLifecycleProfileSave(b){const {doc,first}=ManagerLifecycleDocument(),m=doc.Objects.CreateSectionManager([first],false),seed=doc.NumHandles;doc.DrawingVariables.AcadVer=DxfVersion.AutoCad2013;const bytes=new MemoryStream();try{let rejected=false;try{rejected=!doc.Save(bytes,b);}catch(e){if(!(e instanceof InvalidOperationException||e instanceof NotSupportedException))throw e;rejected=true;}Check(rejected,'Profile conversion was accepted');Equal(0,bytes.Length,'Profile rejection emitted partial output');Equal(seed,doc.NumHandles,'Profile rejection allocated handles');doc.DrawingVariables.AcadVer=DxfVersion.AutoCad2018;SectionManagerSave(doc,b);doc.Objects.EraseSectionManager(m);doc.DrawingVariables.AcadVer=DxfVersion.AutoCad2013;SectionManagerSave(doc,b);}finally{bytes.Dispose();}}
function ManagerLifecycleNative(input,b){const bytes=SectionManagerNativeBytes(),stream=new MemoryStream(bytes);try{const raw=DxfRawDocument.Load(stream);stream.Position=0;const doc=input?SectionManagerLoad(raw,true):DxfDocument.Load(stream),m=SectionMembershipManager(doc),section=OleSingle(m.Sections),settings=section.GeometrySettings,root=doc.Objects.Root,entries=A(root.Entries).filter(e=>e.Target!==m).map(e=>[e.Name,e.Target,e.IsHardOwner]),hard=root.IsHardOwner,cloning=root.Cloning,definition=doc.Classes.get_Item(m.CodeName),metadata=[definition.ApplicationName,definition.ProxyFlags,definition.WasProxy,definition.IsEntity];SectionManagerSave(doc,b,`manager-lifecycle-native-before-${BooleanName(input)}-${BooleanName(b)}.dxf`);doc.Objects.EraseSectionManager(m);Check(doc.GetObjectByHandle('228')===section&&doc.GetObjectByHandle('22A')===settings,'Native erase removed or replaced SECTION/settings identities');const after=A(root.Entries);Check(entries.length===after.length&&entries.every((e,i)=>e[0]===after[i].Name&&e[1]===after[i].Target&&e[2]===after[i].IsHardOwner)&&root.IsHardOwner===hard&&root.Cloning===cloning,'Native erase changed root flags or unrelated entries');Equal(metadata,[definition.ApplicationName,definition.ProxyFlags,definition.WasProxy,definition.IsEntity],'Native erase changed CLASS metadata');Equal(0,definition.InstanceCount,'Native erase retained stale CLASS count');const loaded=SectionManagerSave(doc,b,`manager-lifecycle-native-erased-${BooleanName(input)}-${BooleanName(b)}.dxf`);Check(!A(loaded.Objects.Items).some(x=>x instanceof DxfStoredSectionManager)&&loaded.GetObjectByHandle('229')===null&&loaded.GetObjectByHandle('228') instanceof Section,'Native output resynthesized manager or removed SECTION');}finally{stream.Dispose();}}
