// Complete port of pinned SectionProducerTests.cs.
import path from 'node:path';
import { sourceRoot } from '../../tools/dotnet.mjs';
import { DxfDocument, DxfVersion, Vector3, EntityShadowMode, MemoryStream } from '../../node-entry.js';
import { Run, Check, Equal, SupportedVersions, VersionName, BooleanName } from './TestHarness.js';
import { SectionBytes } from './SectionTests.js';
import { OleSingle, OleWriteArtifact } from './Ole2FrameTests.js';
export function RegisterSectionProducerTests(){for(const v of SupportedVersions.filter(v=>v>=DxfVersion.AutoCad2007))for(const s of [false,true])for(const b of [false,true])Run(`section/producer/${VersionName(v)}/${BooleanName(s)}/${BooleanName(b)}`,()=>SectionProducer(v,s,b));}
function SectionProducer(v,sourceBinary,binary){const year=VersionName(v).replace('AutoCad',''),file=path.join(sourceRoot,'tests/fixtures/section-producer/extracted',`extracted-section-R${year}-${sourceBinary?'binary':'ascii'}.dxf`),doc=DxfDocument.Load(file);Check(doc!==null,'Independent SECTION packet load');const section=OleSingle(doc.Entities.Sections);Equal('SECTION',section.CodeName,'Independent producer spelling');Equal('F1000',section.Handle,'Declared extraction handle map');Equal(7,section.State,'Producer state');Equal(17,section.Flags,'Producer flags');Equal('Producer section',section.Name,'Producer name');Equal(new Vector3(.25,-.5,2),section.VerticalDirection,'Producer independent vertical vector');Equal(17.125,section.TopHeight,'Producer top height');Equal(-2.75,section.BottomHeight,'Producer bottom height');Equal(37,section.IndicatorTransparency,'Producer transparency');Equal(5,section.StoredIndicatorColor,'Producer documented indicator63');Check(section.StoredNativeIndicatorColor===null&&section.IndicatorColorName==='ProducerColor','Producer optional indicator fields');Check(!section.HasStoredGeometrySettings&&section.GeometrySettings===null,'Producer absent360 was materialized');Equal([new Vector3(1.125,2.25,3.5),new Vector3(-4.75,5.125,-6.25),new Vector3(7.5,-8.75,9.125)],[...section.Vertices],'Producer ordered vertices');Equal([new Vector3(10.25,-11.5,12.75),new Vector3(-13.125,14.25,-15.5)],[...section.BackLineVertices],'Producer ordered back-line vertices');Equal(0x02000000,section.Transparency.StoredAlphaValue,'Producer exact common440');Equal('',section.ColorName,'Producer explicit empty common430');Equal(EntityShadowMode.CastAndReceive,section.ShadowMode,'Producer explicit common284');Equal(0,section.Lineweight,'Producer common370');const bytes=SectionBytes(doc,binary);OleWriteArtifact(`section-producer-${VersionName(v)}-${BooleanName(sourceBinary)}-${BooleanName(binary)}.dxf`,bytes);const input=new MemoryStream(bytes);try{const loaded=OleSingle(DxfDocument.Load(input).Entities.Sections);Check(!loaded.HasStoredGeometrySettings&&loaded.StoredNativeIndicatorColor===null,'Producer round-trip inserted absent fields');const clone=loaded.Clone();Check(!clone.HasStoredGeometrySettings&&clone.CodeName==='SECTION','Producer clone changed stored presence or spelling');}finally{input.Dispose();}}
