// Pinned SectionManagerTests.cs. The 32 schema cases also require native
// constructor-reflection metadata; they remain unregistered, not weakened.
import fs from 'node:fs';
import path from 'node:path';
import { gunzipSync } from 'node:zlib';
import { createHash } from 'node:crypto';
import { sourceRoot } from '../../tools/dotnet.mjs';
import { DxfDocument, DxfVersion, DxfXRecord, DxfRawDocument, DxfTag, MemoryStream, DxfStoredSectionManager, DxfOpaqueObject, Section, DxfClass, XData, XDataRecord, XDataCode, ApplicationRegistry } from '../../node-entry.js';
import { FormatException, InvalidOperationException, InvalidDataException, NotSupportedException } from '../../runtime/Errors.js';
import { Run, Check, Equal, BooleanName } from './TestHarness.js';
import { OleSingle, OleWriteArtifact } from './Ole2FrameTests.js';
import { SectionExample, SectionBytes } from './SectionTests.js';
import { OwnershipTagValues } from './SunTests.js';
const A=x=>Array.from(x),T=(c,v)=>new DxfTag(c,v),manager=doc=>OleSingle(A(doc.Objects.Items).filter(x=>x instanceof DxfStoredSectionManager));
export function RegisterSectionManagerTests(){
  for(const input of [false,true])for(const output of [false,true])Run(`section-manager/native/${BooleanName(input)}/${BooleanName(output)}`,()=>SectionManagerNative(input,output));
  for(const b of [false,true]){
    for(let f=0;f<17;f++)Run(`section-manager/malformed/${BooleanName(b)}/${f}`,()=>SectionManagerMalformed(b,f));
    for(let v=0;v<8;v++)Run(`section-manager/opaque/${BooleanName(b)}/${v}`,()=>SectionManagerOpaque(b,v));
    for(let o=0;o<10;o++)Run(`section-manager/lifecycle/${BooleanName(b)}/${o}`,()=>SectionManagerLifecycle(b,o));
    Run(`section-manager/numeric-identities/${BooleanName(b)}`,()=>SectionManagerNumericIdentities(b));Run(`section-manager/xdata/${BooleanName(b)}`,()=>SectionManagerXData(b));
  }
}
export function SectionManagerNativeBytes(){const manifest=JSON.parse(fs.readFileSync(path.join(sourceRoot,'tests/fixtures/section/manifest.json'),'utf8')),bytes=new Uint8Array(gunzipSync(fs.readFileSync(path.join(sourceRoot,'tests/fixtures/section/LiveSection1.dxf.gz'))));Equal(manifest.source_sha256,createHash('sha256').update(bytes).digest('hex'),'Pinned native section source hash');return bytes;}
export function SectionManagerRecord(raw){return OleSingle(A(OleSingle(A(raw.Sections).filter(s=>s.Name==='OBJECTS')).Records).filter(r=>r.Name==='SECTION_MANAGER'||r.Name==='SECTIONMANAGER'));}
export function SectionManagerLoad(raw,binary){const bytes=new MemoryStream();try{raw.WithTags(A(raw.Tags).filter(t=>t.Code!==999)).Save(bytes,binary);bytes.Position=0;const doc=DxfDocument.Load(bytes);if(doc===null)throw new FormatException('Section-manager input was rejected');return doc;}finally{bytes.Dispose();}}
export function SectionManagerSave(doc,binary,name=null){const bytes=new MemoryStream();try{Check(doc.Save(bytes,binary),'Section-manager save rejected');if(name!==null)OleWriteArtifact(name,bytes.ToArray());bytes.Position=0;const loaded=DxfDocument.Load(bytes);if(loaded===null)throw new FormatException('Section-manager reload was rejected');return loaded;}finally{bytes.Dispose();}}
export function SectionManagerFixture(version,spelling='SECTION_MANAGER',count=3){
 const doc=new DxfDocument(version),pointer=new DxfXRecord();doc.Objects.Root.Add('ACAD_SECTION_MANAGER',pointer,false);const targets=[];
 if(version>=DxfVersion.AutoCad2007){const first=SectionExample('SECTIONOBJECT'),second=SectionExample('SECTIONOBJECT');first.Name='Manager first';second.Name='Manager second';doc.Entities.Add(first);doc.Entities.Add(second);targets.push(first.Handle,second.Handle,first.Handle);}else count=0;
 const stream=new MemoryStream(SectionBytes(doc,false));try{const raw=DxfRawDocument.Load(stream),record=OleSingle(A(OleSingle(A(raw.Sections).filter(s=>s.Name==='OBJECTS')).Records).filter(r=>A(r.Tags).some(t=>t.Code===5&&t.Value===pointer.Handle))),tags=A(record.Tags),start=tags.findIndex(t=>t.Code===100);return raw.WithRecord(record,[...tags.slice(0,start).map(t=>t.Code===0?T(0,spelling):t),T(100,'AcDbSectionManager'),T(70,count===0?0:1),T(90,count),...targets.slice(0,count).map(h=>T(330,h))]);}finally{stream.Dispose();}
}
export function SectionManagerNative(input,binary){
 const original=SectionManagerNativeBytes(),s=new MemoryStream(original);try{const raw=DxfRawDocument.Load(s);s.Position=0;const doc=input?SectionManagerLoad(raw,true):DxfDocument.Load(s);Check(doc!==null,'Unchanged native section-manager input rejected');const m=doc.GetObjectByHandle('229'),section=doc.GetObjectByHandle('228');Check(m instanceof DxfStoredSectionManager&&section instanceof Section,'Native typed identity');Equal('SECTION_MANAGER',m.CodeName,'Native manager spelling');Check(!m.RequiresFullUpdate,'Native stored update flag');Check(m.Sections.Count===1&&m.Sections.get_Item(0)===section,'Native exact section identity');Check(m.Owner===doc.Objects.Root&&doc.Objects.Root.get_Item('ACAD_SECTION_MANAGER')===m,'Native reciprocal root entry');const tags=A(SectionManagerRecord(raw).Tags),expected=OwnershipTagValues(tags.slice(tags.findIndex(t=>t.Code===100)));Equal(expected,OwnershipTagValues(m.Tags),'Native manager payload changed on load');const loaded=SectionManagerSave(doc,binary,`section-manager-native-${BooleanName(input)}-${BooleanName(binary)}.dxf`),again=loaded.GetObjectByHandle('229');Equal(expected,OwnershipTagValues(again.Tags),'Native manager packet changed on reload');Check(OleSingle(again.Sections)===loaded.GetObjectByHandle('228'),'Native manager reference changed on reload');Equal(0,loaded.Objects.Validate().Count,'Native manager graph validation');}finally{s.Dispose();}
}
export function SectionManagerMalformed(binary,fault){
 let raw=SectionManagerFixture(DxfVersion.AutoCad2018),record=SectionManagerRecord(raw);const t=A(record.Tags),start=t.findIndex(t=>t.Code===100);
 if(fault===0)t.splice(start,1);else if(fault===1)t.splice(start,0,T(100,'AcDbSectionManager'));else if(fault===2)t.splice(start+1,1);else if(fault===3)t.splice(start+1,0,T(70,0));else if(fault===4)t.splice(start+2,1);else if(fault===5)t.splice(start+2,0,T(90,3));else if(fault===6)t[start+2]=T(90,-1);else if(fault===7)t[start+2]=T(90,65537);else if(fault===8)t[start+2]=T(90,2);else if(fault===9)t[start+2]=T(90,4);else if(fault===10)t[t.length-1]=T(330,'0000');else if(fault===11)t[t.length-1]=T(330,t.slice(0,start).filter(t=>t.Code===330).at(-1).Value);else if(fault===12)t[t.length-1]=T(330,'FFFFFFFF');else if(fault===13)t.splice(start+1,0,T(1000,'stray public data'));else if(fault===14)t[t.findIndex(t=>t.Code===330)]=T(330,t.find(t=>t.Code===5).Value);else if(fault===15)t.splice(start,0,T(5,'FFFF'));else{const root=A(OleSingle(A(raw.Sections).filter(s=>s.Name==='OBJECTS')).Records).find(r=>r.Name==='DICTIONARY');raw=raw.WithRecord(root,A(root.Tags).map(t=>t.Code===3&&t.Value==='ACAD_SECTION_MANAGER'?T(3,'PRIVATE_MANAGER'):t));record=SectionManagerRecord(raw);}
 raw=raw.WithRecord(record,t);let rejected=false;try{SectionManagerLoad(raw,binary);}catch(e){if(!(e instanceof FormatException))throw e;rejected=true;}Check(rejected,'Malformed public manager was accepted or made opaque');
}
export function SectionManagerOpaque(binary,variant){let raw=SectionManagerFixture(variant===5?DxfVersion.AutoCad2004:DxfVersion.AutoCad2018);const r=SectionManagerRecord(raw),t=A(r.Tags),start=t.findIndex(t=>t.Code===100);if(variant===0)t[start]=T(100,'PrivateSectionManager');else if(variant===1)t.push(T(100,'PrivateManagerTail'));else if(variant===2)t.splice(start,0,T(300,'private common value'));else if(variant===3)t.push(T(300,'private payload'));else if(variant===4)t[start+1]=T(70,2);else if(variant===6)t.push(T(102,'{PRIVATE'),T(1000,'private data'),T(102,'}'));else if(variant===7)t.push(T(100,'PrivateManagerTail'),T(340,'EEEEEEEE'));const doc=SectionManagerLoad(raw.WithRecord(r,t),binary),m=OleSingle(A(doc.Objects.Items).filter(x=>x instanceof DxfOpaqueObject&&x.CodeName==='SECTION_MANAGER')),before=OwnershipTagValues(m.Tags),loaded=SectionManagerSave(doc,binary,`section-manager-opaque-${variant}-${BooleanName(binary)}.dxf`);Equal(before,OwnershipTagValues(OleSingle(A(loaded.Objects.Items).filter(x=>x instanceof DxfOpaqueObject&&x.CodeName==='SECTION_MANAGER')).Tags),'Whole opaque manager packet changed');}
export function SectionManagerLifecycle(binary,operation){
 const doc=SectionManagerLoad(SectionManagerFixture(DxfVersion.AutoCad2018),binary),m=manager(doc),section=m.Sections.get_Item(0),seed=doc.NumHandles,objects=doc.Objects.Items.Count,entities=A(doc.Entities.All).length;
 const rejects=(type,f)=>{let error;try{f();}catch(e){error=e;}Check(error instanceof type,`Expected ${type.name}`);};
 if(operation===0)rejects(NotSupportedException,()=>doc.Objects.CloneObject(m,doc.Objects.Root,'COPY'));else if(operation===1){const dest=new DxfDocument(),root=dest.Objects.Root,before=dest.NumHandles;rejects(NotSupportedException,()=>dest.Objects.CloneObject(m,root,'COPY'));Equal(before,dest.NumHandles,'Foreign manager clone allocated handles');}else if(operation===2)rejects(NotSupportedException,()=>doc.Objects.EraseOwnedTree(m));else if(operation===3)Check(!doc.Entities.Remove(section),'Manager target removed');else if(operation===4)rejects(InvalidOperationException,()=>doc.Objects.EraseSection(section));else if(operation===5){doc.DrawingVariables.AcadVer=DxfVersion.AutoCad2013;SectionManagerSaveRejected(doc,binary);}else if(operation===6){doc.Classes.Remove('SECTION_MANAGER');const loaded=SectionManagerSave(doc,binary);Equal(1024,loaded.Classes.get_Item('SECTION_MANAGER').ProxyFlags,'Native manager CLASS flags');Equal(1,loaded.Classes.get_Item('SECTION_MANAGER').InstanceCount,'Manager CLASS instance count');}else{if(operation===7){doc.Classes.Remove('SECTION_MANAGER');doc.Classes.Add(new DxfClass('SECTION_MANAGER','PrivateClass','Private'));}if(operation===8)doc.Objects.Root.Remove('ACAD_SECTION_MANAGER');if(operation===9)m.PersistentReactors.Add(doc.Objects.Root);SectionManagerSaveRejected(doc,binary);}
 if(operation!==6)Equal(seed,doc.NumHandles,'Rejected manager operation allocated handles');Equal(objects,doc.Objects.Items.Count,'Manager lifecycle changed membership');Equal(entities,A(doc.Entities.All).length,'Manager lifecycle changed entities');
}
export function SectionManagerSaveRejected(doc,binary){const sentinel=new Uint8Array([71,29,3,4,5]),output=new MemoryStream();try{output.Write(sentinel,0,sentinel.length);output.Position=2;let rejected=false;try{rejected=!doc.Save(output,binary);}catch(e){if(!(e instanceof InvalidOperationException||e instanceof InvalidDataException||e instanceof NotSupportedException))throw e;rejected=true;}Check(rejected,'Invalid manager preflight accepted');Equal(sentinel,output.ToArray(),'Manager preflight changed existing stream bytes');Equal(2,output.Position,'Manager preflight moved the caller stream position');}finally{output.Dispose();}}
function SectionManagerNumericIdentities(binary){let raw=SectionManagerFixture(DxfVersion.AutoCad2018),record=SectionManagerRecord(raw),t=A(record.Tags),start=t.findIndex(t=>t.Code===100);raw=raw.WithRecord(record,t.map((tag,i)=>i>start&&tag.Code===330?T(330,'000'+tag.Value.toLowerCase()):tag));const root=A(OleSingle(A(raw.Sections).filter(s=>s.Name==='OBJECTS')).Records).find(r=>r.Name==='DICTIONARY');raw=raw.WithRecord(root,A(root.Tags).map(t=>t.Code===3&&t.Value==='ACAD_SECTION_MANAGER'?T(3,'AcAd_sEcTiOn_MaNaGeR'):t));const doc=SectionManagerLoad(raw,binary),m=manager(doc);Check(m.Sections.get_Item(0)===m.Sections.get_Item(2),'Numeric aliases lost source identity');const before=OwnershipTagValues(m.Tags),again=manager(SectionManagerSave(doc,binary));Equal(before,OwnershipTagValues(again.Tags),'Numeric source-handle spelling changed');Equal('AcAd_sEcTiOn_MaNaGeR',OleSingle(A(again.Owner.Entries).filter(e=>e.Target===again)).Name,'Source manager dictionary-name spelling changed');}
function SectionManagerXData(binary){const doc=SectionManagerLoad(SectionManagerFixture(DxfVersion.AutoCad2018),binary),m=manager(doc),data=new XData(new ApplicationRegistry('MANAGER_APP'));data.XDataRecord.Add(new XDataRecord(XDataCode.String,'Stored manager annotation'));data.XDataRecord.Add(new XDataRecord(XDataCode.DatabaseHandle,m.Sections.get_Item(0).Handle));m.XData.Add(data);const loaded=SectionManagerSave(doc,binary),again=manager(loaded);Equal('Stored manager annotation',again.XData.get_Item('MANAGER_APP').XDataRecord.get_Item(0).Value,'Real manager XData string changed');Check(loaded.GetObjectByHandle(again.XData.get_Item('MANAGER_APP').XDataRecord.get_Item(1).Value)===again.Sections.get_Item(0),'Real manager XData target changed');Check(!loaded.ApplicationRegistries.Remove('MANAGER_APP'),'Manager XData APPID dependency was removable');}
