// Port of pinned SourceAmbiguityTests.cs; native-byte helper matches SectionManagerTests.cs.
import { DxfDocument, DxfRawDocument, DxfTag, DxfVersion, MemoryStream, DxfDictionaryVariable } from '../../index.js';
import { FormatException, InvalidDataException } from '../../runtime/Errors.js';
import { Run, Check, Equal, BooleanName } from './TestHarness.js';
import { SourceReferenceRecord } from './SourceReferenceIdentityTests.js';
import fs from 'node:fs';
import { gunzipSync } from 'node:zlib';
import { createHash } from 'node:crypto';
const single=values=>{const a=Array.from(values);Equal(1,a.length,'Single');return a[0];};
const tagsOf=pairs=>pairs.map(([c,v])=>new DxfTag(c,v));
export function RegisterSourceAmbiguityTests(){for(const binary of [false,true]){
  for(const placement of ['native','before','after','private'])Run(`source-ambiguity/section-manager/${placement}/${BooleanName(binary)}`,()=>SourceAmbiguityManager(placement,binary));
  for(const placement of ['native','duplicate-entity','private','nested-private','nested-standard-lookalikes','unbalanced-private'])Run(`source-ambiguity/consumed-layer-dictionary/${placement}/${BooleanName(binary)}`,()=>SourceAmbiguityLayerDictionary(placement,binary));
}}
export function SectionManagerNativeBytes(){const manifest=JSON.parse(fs.readFileSync('tests/fixtures/section/manifest.json','utf8')),bytes=gunzipSync(fs.readFileSync('tests/fixtures/section/LiveSection1.dxf.gz'));Equal(manifest.source_sha256,createHash('sha256').update(bytes).digest('hex'),'Pinned native section source hash');return bytes;}
export function SourceAmbiguityDecoy(handle){return tagsOf([[0,'FUTURE_SOURCE_ENTITY'],[5,handle.toLowerCase().padStart(12,'0')],[100,'AcDbEntity'],[8,'0'],[100,'AcDbFutureSourceEntity']]);}
export function SourceAmbiguityPrivateHandle(raw,record,handle,nested){const tags=Array.from(record.Tags),control=tagsOf([[102,'{PRIVATE_SOURCE']]);if(nested)control.push(...tagsOf([[102,'{NESTED'],[102,'}']]));control.push(...tagsOf([[5,handle],[102,'}']]));tags.splice(tags.findIndex(t=>t.Code===100),0,...control);return raw.WithRecord(record,tags);}
export function SourceAmbiguityLoad(raw,binary,reject){const input=new MemoryStream();try{raw.Save(input,binary);input.Position=0;let loaded=null,rejected=false;try{loaded=DxfDocument.Load(input);rejected=loaded===null;}catch(e){if(!reject||!(e instanceof FormatException||e instanceof InvalidDataException))throw e;rejected=true;}Check(input.CanRead,'Source ambiguity handling closed the caller stream');Equal(reject,rejected,'Ambiguous physical source declarations must reject; private handle fields must not');return loaded;}finally{input.Dispose();}}
export function SourceAmbiguityManager(placement,binary){const source=new MemoryStream(SectionManagerNativeBytes());let raw;try{raw=DxfRawDocument.Load(source);}finally{source.Dispose();}const section=SourceReferenceRecord(raw,'228');if(placement==='before'||placement==='after'){const tags=Array.from(raw.Tags),index=section.StartTagIndex+(placement==='after'?section.Tags.Count:0);tags.splice(index,0,...SourceAmbiguityDecoy('228'));raw=DxfRawDocument.Create(tags);}else if(placement==='private')raw=SourceAmbiguityPrivateHandle(raw,section,'228',true);const doc=SourceAmbiguityLoad(raw,binary,placement==='before'||placement==='after');if(doc===null)return;const manager=doc.GetObjectByHandle('229');Check(single(manager.Sections)===doc.GetObjectByHandle('228'),'Manager lost its actual physical section identity');Equal(0,doc.Objects.Validate().Count,'Unambiguous manager graph validation');const output=new MemoryStream();try{Check(doc.Save(output,!binary),'Unambiguous manager cross-transport save');output.Position=0;const again=DxfDocument.Load(output);Check(again!==null,'Unambiguous manager reload rejected');Check(single(again.GetObjectByHandle('229').Sections)===again.GetObjectByHandle('228'),'Manager target identity changed after cross-transport save');}finally{output.Dispose();}}
export function SourceAmbiguityLayerDictionary(placement,binary){const seed=new DxfDocument(DxfVersion.AutoCad2018);seed.Layers.StateManager.AddNew('AMBIGUITY_SNAPSHOT');const variable=new DxfDictionaryVariable();variable.Value='retained alongside layer-state conversion';seed.NamedObjects.Add('AMBIGUITY_APP',variable);const bytes=new MemoryStream();let raw;try{Check(seed.Save(bytes,binary),'Layer-state source seed save');bytes.Position=0;raw=DxfRawDocument.Load(bytes);}finally{bytes.Dispose();}const table=single(single(raw.Sections.filter(s=>s.Name==='TABLES')).Records.filter(r=>r.Name==='TABLE'&&Array.from(r.Tags).some(t=>t.Code===2&&t.Value==='LAYER'))),extension=single(Array.from(table.Tags).filter(t=>t.Code===360)).Value,dictionary=SourceReferenceRecord(raw,extension);Equal('DICTIONARY',dictionary.Name,'Consumed layer extension has a physical dictionary declaration');
  if(placement==='duplicate-entity'){const tags=Array.from(raw.Tags),index=single(raw.Sections.filter(s=>s.Name==='ENTITIES')).ContentStartTagIndex;tags.splice(index,0,...SourceAmbiguityDecoy(extension));raw=DxfRawDocument.Create(tags);}
  else if(placement==='private'||placement==='nested-private')raw=SourceAmbiguityPrivateHandle(raw,dictionary,extension,placement==='nested-private');
  else if(placement==='nested-standard-lookalikes'||placement==='unbalanced-private'){const tags=Array.from(dictionary.Tags),control=tagsOf([[102,'{PRIVATE_SOURCE'],[5,extension]]);if(placement==='nested-standard-lookalikes')control.push(...tagsOf([[102,'{ACAD_REACTORS'],[330,'ABCDEF'],[102,'}'],[102,'{ACAD_XDICTIONARY'],[360,'ABCDE0'],[102,'}'],[102,'}']]));tags.splice(tags.findIndex(t=>t.Code===100),0,...control);raw=raw.WithRecord(dictionary,tags);}
  const doc=SourceAmbiguityLoad(raw,binary,placement==='duplicate-entity'||placement==='unbalanced-private');if(doc===null)return;Check(doc.Layers.StateManager.Contains('AMBIGUITY_SNAPSHOT'),'Accepted consumed dictionary lost its layer snapshot');Equal('retained alongside layer-state conversion',doc.NamedObjects.get_Item('AMBIGUITY_APP').Value,'Consumed layer-state mapping changed ordinary source objects');Equal(0,doc.Objects.Validate().Count,'Unambiguous consumed dictionary graph validation');const output=new MemoryStream();try{Check(doc.Save(output,!binary),'Consumed layer-state cross-transport save');output.Position=0;const again=DxfDocument.Load(output);Check(again!==null,'Consumed layer-state reload rejected');Check(again.Layers.StateManager.Contains('AMBIGUITY_SNAPSHOT'),'Consumed dictionary mapping lost after cross-transport save');}finally{output.Dispose();}
}
