// Port of pinned SunTests.cs, retaining original identities, assertions and fixture checks.
import { DxfDocument, DxfRawDocument, DxfTag, DxfVersion, MemoryStream, View, VPort, Viewport, Layout, DxfSun, DxfSunShadowType, DxfDictionary, DxfXRecord, DxfIdBuffer, DxfPlaceholder, DxfOpaqueObject, XData, XDataRecord, XDataCode, ApplicationRegistry } from '../../index.js';
import { ArgumentException, ArgumentOutOfRangeException, InvalidOperationException, InvalidDataException, NotSupportedException, FormatException } from '../../runtime/Errors.js';
import { Run, Check, Equal, Throws, SupportedVersions, VersionName, BooleanName } from './TestHarness.js';
import { OleWriteArtifact, OleSingle, OleRecords } from './Ole2FrameTests.js';
import fs from 'node:fs';
import path from 'node:path';
import { sourceRoot } from '../../tools/dotnet.mjs';
import { gunzipSync } from 'node:zlib';
import { createHash } from 'node:crypto';
const tag=(c,v)=>new DxfTag(c,v),tags=r=>Array.from(r.Tags),has=(r,c,v)=>tags(r).some(t=>t.Code===c&&(v===undefined||t.Value===v));
const records=(raw,section)=>Array.from(OleSingle(Array.from(raw.Sections).filter(s=>s.Name===section)).Records);
const value=(r,c)=>OleSingle(tags(r).filter(t=>t.Code===c)).Value;
const sunRecord=raw=>OleSingle(records(raw,'OBJECTS').filter(r=>r.Name==='SUN'));
const dbl=n=>{const b=Buffer.alloc(8);b.writeDoubleLE(n);return b;};
// Matches the original OwnershipTagValues helper, including signed zero and binary bytes.
export function OwnershipTagValues(values){return Array.from(values,t=>[t.Code,t.Value instanceof Uint8Array?Buffer.from(t.Value).toString('hex').toUpperCase():typeof t.Value==='number'&&((t.Code>=10&&t.Code<=59)||(t.Code>=110&&t.Code<=149)||(t.Code>=210&&t.Code<=239)||(t.Code>=460&&t.Code<=469)||(t.Code>=1010&&t.Code<=1059))?dbl(t.Value).readBigUInt64LE().toString(16).toUpperCase():typeof t.Value==='boolean'?BooleanName(t.Value):String(t.Value)]);}
// Original empty mapping enumerator invokes the callback when enumeration starts.
const mappings=callback=>({*[Symbol.iterator](){callback();}});
class MetadataCallbackRegistry extends ApplicationRegistry {Callback=null;Clone(...args){if(args.length===0)this.Callback?.();return super.Clone(...args);}}
export function RegisterSunTests(){
  for(const v of SupportedVersions.filter(v=>v>=DxfVersion.AutoCad2007))for(const b of [false,true]){
    const id=`${VersionName(v)}/${BooleanName(b)}`;
    for(const kind of v<DxfVersion.AutoCad2010?['VPORT','VIEWPORT']:['VPORT','VIEW','VIEWPORT']){Run(`sun/values/${id}/${kind}`,()=>SunValues(v,b,kind));Run(`sun/lifecycle/${id}/${kind}`,()=>SunLifecycle(v,b,kind));Run(`sun/host-private-context/${id}/${kind}`,()=>SunHostPrivateContext(v,b,kind));}
    for(const defect of ['missing-version','duplicate-version','duplicate-marker','nonfinite','missing-time','duplicate-intensity','color-low','color-high','rgb-low','rgb-high','shadow-low','shadow-high','map-small','map-nonpower','map-large','softness-low','softness-high','owner-missing','owner-wrong','slot-missing','slot-wrong-kind','slot-missing-target','slot-duplicate'])Run(`sun/malformed/${id}/${defect}`,()=>SunMalformed(v,b,defect));
    for(const variant of ['version','field','subclass','header'])Run(`sun/opaque/${id}/${variant}`,()=>SunOpaque(v,b,variant));Run(`sun/null-and-normalized/${id}`,()=>SunNullIdentity(v,b));
  }
  for(const b of [false,true])for(const file of ['acad_table_simple.dxf','acad_table_with_blk_ref.dxf'])Run(`sun/native/${file}/${BooleanName(b)}`,()=>SunNative(file,b));
  for(const v of [DxfVersion.AutoCad2000,DxfVersion.AutoCad2004])for(const b of [false,true])Run(`sun/older-opaque/${VersionName(v)}/${BooleanName(b)}`,()=>SunOlderOpaque(v,b));
  Run('sun/atomicity-and-profile',SunAtomicity);Run('sun/caller-reentrancy',SunReentrancy);
}
export function SunHost(doc,kind,name){if(kind==='VIEW')return doc.Views.Add(new View(name));if(kind==='VPORT')return doc.VPorts.AddRecord(new VPort(name));const viewport=new Viewport();doc.Entities.Add(viewport);return viewport;}
export const SunOf=host=>host.Sun;
export function SunSettings(){return Object.assign(new DxfSun(),{Enabled:true,ColorIndex:3,TrueColor:0x123456,Intensity:-2.125,ShadowsEnabled:false,JulianDay:2455826,StoredTime:54000000,DaylightSavingTime:true,ShadowType:DxfSunShadowType.AreaSampled,ShadowMapSize:4096,ShadowSoftness:255});}
export function SunSetup(v,kind='VPORT'){const doc=new DxfDocument(v),host=SunHost(doc,kind,'SunOwner'),sun=SunSettings();doc.Objects.SetSun(host,sun);return{doc,host,sun};}
export function SunRaw(v,b){const{doc}=SunSetup(v),s=new MemoryStream();try{Check(doc.Save(s,b),'SUN seed save');s.Position=0;return DxfRawDocument.Load(s);}finally{s.Dispose();}}
export function SunLoad(raw){const s=new MemoryStream();try{raw.Save(s);s.Position=0;const doc=DxfDocument.Load(s);Check(doc!==null,'SUN load failed.');return doc;}finally{s.Dispose();}}
export function SunRoundTrip(doc,b,file=null){const s=new MemoryStream();try{Check(doc.Save(s,b),'SUN save');if(file!==null)OleWriteArtifact(file,s.ToArray());s.Position=0;const loaded=DxfDocument.Load(s);Check(loaded!==null,'SUN roundtrip load failed.');return loaded;}finally{s.Dispose();}}
export function SunAssert(sun,host){
  Check(sun.Owner===host&&SunOf(host)===sun,'Reciprocal owned SUN');Equal(1,sun.StoredVersion,'Stored version');Check(sun.Enabled&&!sun.ShadowsEnabled&&sun.DaylightSavingTime,'Stored flags');Equal(3,sun.ColorIndex,'Independent ACI');Equal(0x123456,sun.TrueColor,'Independent truecolor');Equal(-2.125,sun.Intensity,'Finite stored intensity without speculative range');Equal(2455826,sun.JulianDay,'Raw Julian day');Equal(54000000,sun.StoredTime,'Raw native time without conversion');Equal(DxfSunShadowType.AreaSampled,sun.ShadowType,'Primary enum shadow type two');Equal(4096,sun.ShadowMapSize,'Map size');Equal(255,sun.ShadowSoftness,'Unsigned softness');
}
export function SunValues(v,b,kind){let{doc,host,sun}=SunSetup(v,kind);const hostId=host.Handle,sunId=sun.Handle;
  for(let cycle=0;cycle<3;cycle++){SunAssert(sun,host);Equal(0,doc.Objects.Validate().Count,'SUN graph validation');doc=SunRoundTrip(doc,b,cycle===2?`sun-${kind}-${VersionName(v)}-${BooleanName(b)}.dxf`:null);host=doc.GetObjectByHandle(hostId);sun=doc.GetObjectByHandle(sunId);}
  SunAssert(sun,host);for(const size of [64,128,256,512,1024,2048,4096])sun.ShadowMapSize=size;sun.TrueColor=null;sun.ColorIndex=256;sun.ShadowType=DxfSunShadowType.ShadowMaps;sun.StoredTime=-2147483648;sun.JulianDay=2147483647;sun.Intensity=0;sun.ShadowSoftness=0;
  doc=SunRoundTrip(doc,b);sun=doc.GetObjectByHandle(sunId);Equal(null,sun.TrueColor,'Absent truecolor retained');Equal(-2147483648,sun.StoredTime,'Raw signed time');Equal(2147483647,sun.JulianDay,'Raw signed day');
  const stream=new MemoryStream();try{Check(doc.Save(stream,b),'CLASS save');stream.Position=0;const raw=DxfRawDocument.Load(stream),definition=OleSingle(records(raw,'CLASSES').filter(r=>r.Name==='CLASS'&&has(r,1,'SUN')));Equal('SCENEOE',value(definition,3),'Native application name');Equal(1153,value(definition,90),'Native proxy flags');Equal(1,value(definition,91),'Physical SUN count');}finally{stream.Dispose();}
}
export const SunRemove=(doc,host)=>host instanceof View?doc.Views.Remove(host):host instanceof VPort?doc.VPorts.Remove(host):doc.Entities.Remove(host);
export function SunLifecycle(v,b,kind){const{doc,host,sun}=SunSetup(v,kind),ext=new DxfDictionary(),record=new DxfXRecord();record.Data.Add(tag(331,host.Handle));record.Data.Add(tag(340,sun.Handle));ext.Add('POINTERS',record);doc.Objects.SetExtensionDictionary(sun,ext);sun.PersistentReactors.Add(host);
  const app=new XData(new ApplicationRegistry('SUN_TEST'));app.XDataRecord.Add(new XDataRecord(XDataCode.DatabaseHandle,host.Handle));sun.XData.Add(app);Throws(NotSupportedException,()=>host.Clone());Check(!SunRemove(doc,host),'Owned SUN prevents host removal');
  let destination=new DxfDocument(v),target=SunHost(destination,kind,'CopiedSunOwner'),copy=destination.Objects.CloneSun(sun,target);Check(sun!==copy,'Independent SUN clone');SunAssert(copy,target);let copiedRecord=copy.ExtensionDictionary.get_Item('POINTERS');Equal(target.Handle,copiedRecord.Data.get_Item(0).Value,'Source host remapped');Equal(copy.Handle,copiedRecord.Data.get_Item(1).Value,'Internal SUN remapped');Check(OleSingle(copy.PersistentReactors)===target,'Owner reactor remapped');Equal(target.Handle,copy.XData.get_Item('SUN_TEST').XDataRecord.get_Item(0).Value,'XData host remapped');
  Equal(0,destination.Objects.Validate().Count,'Cloned SUN graph validation');destination=SunRoundTrip(destination,b);copy=OleSingle(Array.from(destination.Objects.Items).filter(o=>o instanceof DxfSun));target=copy.Owner;copiedRecord=copy.ExtensionDictionary.get_Item('POINTERS');
  const incoming=new DxfIdBuffer();incoming.References.Add(copy);destination.NamedObjects.Add('INCOMING',incoming);const id=copy.Handle,count=destination.Objects.Items.Count;Throws(InvalidOperationException,()=>destination.Objects.EraseOwnedTree(copy));Equal(count,destination.Objects.Items.Count,'Blocked erasure atomic');Check(SunOf(target)===copy,'Blocked erasure retains slot');incoming.References.Clear();destination.Objects.EraseOwnedTree(copy);Check(copy.IsErased&&copiedRecord.IsErased&&copy.ExtensionDictionary.IsErased,'Complete owned subtree erased');Equal(null,SunOf(target),'SUN slot cleared');Equal(null,destination.GetObjectByHandle(id),'SUN handle unregistered');Throws(InvalidOperationException,()=>{copy.Enabled=false;});Throws(ArgumentException,()=>destination.Objects.SetSun(target,copy));Check(SunRemove(destination,target),'Host removable after explicit SUN erasure');Equal(0,destination.Objects.Validate().Count,'Erased graph validates');
}
export function SunHostPrivateContext(v,b,kind){for(const context of [0,1,2]){const{doc,host,sun}=SunSetup(v,kind),stream=new MemoryStream();try{Check(doc.Save(stream,b),'Host context seed');stream.Position=0;let raw=DxfRawDocument.Load(stream);const record=OleSingle(OleRecords(raw).filter(r=>r.Name===kind&&has(r,5,host.Handle))),decoy=context===2?[tag(1001,'SUN_TRAILER'),tag(1000,'Stored metadata'),tag(361,'7ABCDE')]:context===1?[tag(100,'PrivateSunCarrier'),tag(361,'7ABCDE')]:[tag(102,'{PRIVATE_SUN'),tag(102,'{NESTED'),tag(361,'7ABCDE'),tag(102,'}'),tag(102,'}')];raw=raw.WithRecord(record,[...record.Tags,...decoy]);const loaded=SunLoad(raw);Check(SunOf(loaded.GetObjectByHandle(host.Handle))===loaded.GetObjectByHandle(sun.Handle),'Private group, later subclass or XData trailer does not redefine public SUN slot');}finally{stream.Dispose();}}}
function rejectedLoad(bytes){const input=new MemoryStream(bytes);try{try{return DxfDocument.Load(input)===null;}catch(e){if(!(e instanceof FormatException||e instanceof ArgumentException||e instanceof InvalidDataException))throw e;return true;}}finally{input.Dispose();}}
export function SunMalformed(v,b,defect){let raw=SunRaw(v,b),sun=sunRecord(raw);const sunId=value(sun,5),host=OleSingle(records(raw,'TABLES').filter(r=>r.Name==='VPORT'&&has(r,361,sunId)));let t=tags(sun);const set=(c,v)=>{const at=t.findIndex(t=>t.Code===c);Check(at>=0,'SUN mutation target');t[at]=tag(c,v);};
  switch(defect){
    case'duplicate-marker':t.push(tag(100,'AcDbSun'));break;
    case'nonfinite':{const out=new MemoryStream();try{raw.Save(out);let bytes=Buffer.from(out.ToArray());if(b){const at=bytes.indexOf(dbl(-2.125));Check(at>=0,'SUN nonfinite injection target');dbl(Infinity).copy(bytes,at);}else bytes=Buffer.from(bytes.toString('utf8').replaceAll('-2.125','Infinity'));Check(rejectedLoad(bytes),'SUN nonfinite raw value rejected');}finally{out.Dispose();}return;}
    case'missing-version':t=t.filter(t=>t.Code!==90);break;case'duplicate-version':t.push(tag(90,1));break;case'missing-time':t=t.filter(t=>t.Code!==92);break;case'duplicate-intensity':t.push(tag(40,2));break;
    case'color-low':set(63,-1);break;case'color-high':set(63,257);break;case'rgb-low':set(421,-1);break;case'rgb-high':set(421,0x1000000);break;case'shadow-low':set(70,-1);break;case'shadow-high':set(70,3);break;case'map-small':set(71,32);break;case'map-nonpower':set(71,100);break;case'map-large':set(71,8192);break;case'softness-low':set(280,-1);break;case'softness-high':set(280,256);break;
    case'owner-missing':t=t.filter(t=>t.Code!==330);break;case'owner-wrong':set(330,value(records(raw,'OBJECTS').find(r=>r.Name==='DICTIONARY'),5));break;
    case'slot-missing':raw=raw.WithRecord(host,tags(host).filter(t=>t.Code!==361));break;case'slot-wrong-kind':raw=raw.WithRecord(host,tags(host).map(t=>t.Code===361?tag(361,value(host,5)):t));break;case'slot-missing-target':raw=raw.WithRecord(host,tags(host).map(t=>t.Code===361?tag(361,'7ABCDE'):t));break;case'slot-duplicate':raw=raw.WithRecord(host,[...host.Tags,tag(361,sunId)]);break;
  }
  sun=sunRecord(raw);raw=raw.WithRecord(sun,t);const input=new MemoryStream();try{raw.Save(input);Check(rejectedLoad(input.ToArray()),'Malformed SUN rejected: '+defect);}finally{input.Dispose();}
}
export function SunOpaque(v,b,variant){let raw=SunRaw(v,b);const sun=sunRecord(raw),t=tags(sun);if(variant==='version')t[t.findIndex(t=>t.Code===90)]=tag(90,2);if(variant==='field')t.push(tag(300,'PRIVATE'));if(variant==='subclass')t.push(tag(100,'PrivateSun'));if(variant==='header')t.splice(t.findIndex(t=>t.Code===100),0,tag(1,'PRIVATE'));raw=raw.WithRecord(sun,t);const doc=SunLoad(raw),opaque=OleSingle(Array.from(doc.Objects.Items).filter(o=>o instanceof DxfOpaqueObject&&o.CodeName==='SUN'));Check(SunOf(opaque.Owner)===opaque,'Opaque SUN reciprocal slot retained');Throws(NotSupportedException,()=>doc.Objects.EraseOwnedTree(opaque));Throws(NotSupportedException,()=>opaque.Owner.Clone());const out=new MemoryStream();try{Check(doc.Save(out,b),'Opaque SUN output');out.Position=0;Equal(OwnershipTagValues(t),OwnershipTagValues(sunRecord(DxfRawDocument.Load(out)).Tags),'Whole opaque SUN record retained');}finally{out.Dispose();}}
export function SunNullIdentity(v,b){let raw=SunRaw(v,b),sun=sunRecord(raw);const id=value(sun,5);let host=OleSingle(records(raw,'TABLES').filter(r=>r.Name==='VPORT'&&has(r,361)));raw=raw.WithRecord(sun,tags(sun).map(t=>t.Code===5?tag(5,'000'+id.toLowerCase()):t));host=OleSingle(records(raw,'TABLES').filter(r=>r.Name==='VPORT'&&has(r,361)));raw=raw.WithRecord(host,tags(host).map(t=>t.Code===361?tag(361,'00'+id.toLowerCase()):t));let doc=SunLoad(raw);Equal(1,Array.from(doc.Objects.Items).filter(o=>o instanceof DxfSun).length,'Normalized physical identity accepted');sun=sunRecord(raw);raw=raw.WithoutRecord(sun);host=OleSingle(records(raw,'TABLES').filter(r=>r.Name==='VPORT'&&has(r,361)));raw=raw.WithRecord(host,tags(host).map(t=>t.Code===361?tag(361,'000'):t));doc=SunLoad(raw);Check(Array.from(doc.VPorts.Records).every(v=>v.Sun===null),'Numeric zero SUN slot remains empty');doc=SunRoundTrip(doc,b);Check(Array.from(doc.VPorts.Records).every(v=>v.Sun===null),'Explicit null save/load');}
export function SunAtomicity(){
  const{doc,host,sun}=SunSetup(DxfVersion.AutoCad2018),count=doc.Objects.Items.Count,seed=doc.DrawingVariables.HandleSeed;Throws(InvalidOperationException,()=>doc.Objects.SetSun(host,new DxfSun()));Equal(count,doc.Objects.Items.Count,'Occupied slot atomic');Equal(seed,doc.DrawingVariables.HandleSeed,'Occupied slot allocates no handle');Throws(ArgumentException,()=>doc.NamedObjects.Add('INVALID_SUN',new DxfSun()));
  for(const v of [DxfVersion.AutoCad2000,DxfVersion.AutoCad2004]){const old=new DxfDocument(v),target=SunHost(old,'VPORT','Old');void old.Objects;const before=old.Objects.Items.Count;Throws(NotSupportedException,()=>old.Objects.SetSun(target,new DxfSun()));Equal(before,old.Objects.Items.Count,'Old profile atomic');}
  const r2007=new DxfDocument(DxfVersion.AutoCad2007),view=SunHost(r2007,'VIEW','OldView');Throws(NotSupportedException,()=>r2007.Objects.SetSun(view,new DxfSun()));const layout=new Layout('UnregisteredViewport');doc.Layouts.Add(layout);Check(doc.GetObjectByHandle(layout.Viewport.Handle)!==layout.Viewport,'Fixture exposes retained-only layout viewport');{const before=doc.Objects.Items.Count;Throws(ArgumentException,()=>doc.Objects.SetSun(layout.Viewport,new DxfSun()));Equal(before,doc.Objects.Items.Count,'Retained-only attachment atomic');}
  const detached=new DxfSun();Throws(ArgumentOutOfRangeException,()=>{detached.Intensity=NaN;});Throws(ArgumentOutOfRangeException,()=>{detached.ShadowMapSize=100;});const other=new DxfDocument(DxfVersion.AutoCad2018),targetHost=SunHost(other,'VPORT','Target');void other.Objects;const originalCount=other.Objects.Items.Count;Throws(ArgumentException,()=>other.Objects.CloneSun(sun,targetHost,new Map([[host,other.Layers.get_Item('0')]])));Equal(originalCount,other.Objects.Items.Count,'Clone map failure atomic');
  const pointer=new DxfPlaceholder();doc.NamedObjects.Add('EXTERNAL',pointer);sun.PersistentReactors.Add(pointer);Throws(InvalidOperationException,()=>other.Objects.CloneSun(sun,targetHost));Equal(originalCount,other.Objects.Items.Count,'Missing map allocates no object');Check(SunOf(targetHost)===null,'Missing map leaves slot empty');const replacement=new DxfPlaceholder();other.NamedObjects.Add('REPLACEMENT',replacement);const clone=other.Objects.CloneSun(sun,targetHost,new Map([[pointer,replacement]]));Check(OleSingle(clone.PersistentReactors)===replacement,'Explicit external map accepted');
}
export function SunReentrancy(){const{doc:source,sun}=SunSetup(DxfVersion.AutoCad2018),target=new DxfDocument(DxfVersion.AutoCad2018),host=SunHost(target,'VPORT','Target');void target.Objects;let afterCallback=0;
  Throws(InvalidOperationException,()=>target.Objects.CloneSun(sun,host,mappings(()=>{target.Objects.SetSun(host,new DxfSun());afterCallback=target.Objects.Items.Count;})));Equal(afterCallback,target.Objects.Items.Count,'Destination callback causes no extra registration');Check(SunOf(host)!==null,'Callback attachment retained');target.Objects.EraseOwnedTree(SunOf(host));
  Throws(ArgumentException,()=>target.Objects.CloneSun(sun,host,mappings(()=>source.Objects.EraseOwnedTree(sun))));Check(sun.IsErased&&SunOf(host)===null,'Erased source cannot produce clone');const authored=new DxfSun(),app=new MetadataCallbackRegistry('SUN_CALLBACK');let calls=0;app.Callback=()=>{calls++;target.VPorts.Remove(host);};authored.XData.Add(new XData(app));target.Objects.SetSun(host,authored);Equal(0,calls,'SUN registration does not invoke APPID override');Check(target.GetObjectByHandle(host.Handle)===host,'SUN owner remains registered');
  const registeredApp=new MetadataCallbackRegistry('SUN_CLONE_CALLBACK');target.ApplicationRegistries.Add(registeredApp);authored.XData.Add(new XData(registeredApp));registeredApp.Callback=()=>{calls++;target.Objects.EraseOwnedTree(authored);};const secondHost=SunHost(target,'VPORT','Second'),copy=target.Objects.CloneSun(authored,secondHost);Equal(0,calls,'SUN clone copies stored metadata without override');Check(!authored.IsErased&&SunOf(secondHost)===copy,'SUN clone remains coherent');
  const one=target.VPorts.AddRecord(new VPort('MULTIPLE')),two=target.VPorts.AddRecord(new VPort('MULTIPLE'));target.Objects.SetSun(two,new DxfSun());const count=target.VPorts.Records.Count;Check(!target.VPorts.Remove('MULTIPLE')&&target.VPorts.Records.Count===count&&one.Owner!==null,'Configuration removal preflights all physical owners atomically');
}
export function SunOlderOpaque(v,b){let raw=SunRaw(DxfVersion.AutoCad2007,b),host=OleSingle(records(raw,'TABLES').filter(r=>r.Name==='VPORT'&&has(r,361)));raw=raw.WithRecord(host,tags(host).filter(t=>t.Code!==361));let root=records(raw,'OBJECTS').find(r=>r.Name==='DICTIONARY');const rootId=value(root,5),sun=sunRecord(raw),sunId=value(sun,5);raw=raw.WithRecord(sun,tags(sun).map(t=>t.Code===330?tag(330,rootId):t));root=records(raw,'OBJECTS').find(r=>r.Name==='DICTIONARY');raw=raw.WithRecord(root,[...root.Tags,tag(3,'OLD_SUN'),tag(360,sunId)]);const t=Array.from(raw.Tags);t[t.findIndex(t=>t.Code===9&&t.Value==='$ACADVER')+1]=tag(1,v===DxfVersion.AutoCad2000?'AC1015':'AC1018');let doc=SunLoad(DxfRawDocument.Create(t,b));Check(doc.NamedObjects.get_Item('OLD_SUN') instanceof DxfOpaqueObject,'Older SUN is entirely opaque');doc=SunRoundTrip(doc,b);Check(doc.NamedObjects.get_Item('OLD_SUN') instanceof DxfOpaqueObject,'Older opaque SUN survives');}
export function SunNative(file,b){
  const bytes=gunzipSync(fs.readFileSync(path.join(sourceRoot,'tests','fixtures','table-oracle',file+'.gz'))),inventory=JSON.parse(fs.readFileSync(path.join(sourceRoot,'tools','table_oracle','fixtures.json'),'utf8')),hash=OleSingle(inventory.files.filter(v=>v.file===file)).sha256;Equal(hash,createHash('sha256').update(bytes).digest('hex'),'Pinned native source hash');const original=new MemoryStream(bytes);let source;try{source=DxfRawDocument.Load(original);}finally{original.Dispose();}const sun=sunRecord(source),sourceId=value(sun,5),ownerId=value(sun,330),sourceHost=OleSingle(records(source,'TABLES').filter(r=>r.Name==='VPORT'&&has(r,5,ownerId)));Equal(sourceId,value(sourceHost,361),'Native VPORT reciprocal 361');
  const seed=new DxfDocument(DxfVersion.AutoCad2007),host=seed.VPorts.get_Item(VPort.DefaultName);void seed.Objects;const saved=new MemoryStream();let raw;try{Check(seed.Save(saved,b),'Native extraction seed');saved.Position=0;raw=DxfRawDocument.Load(saved);}finally{saved.Dispose();}
  const importedId='7F000',t=tags(sun).map(t=>t.Code===5?tag(5,importedId):t.Code===330?tag(330,host.Handle):t),targetHost=OleSingle(records(raw,'TABLES').filter(r=>r.Name==='VPORT'&&has(r,5,host.Handle)));raw=raw.WithRecord(targetHost,[...targetHost.Tags,tag(361,importedId)]);const end=OleSingle(Array.from(raw.Sections).filter(s=>s.Name==='OBJECTS')).EndTagIndex-1,all=Array.from(raw.Tags);raw=raw.WithTags([...all.slice(0,end),...t,...all.slice(end)]);const doc=SunLoad(raw),typed=doc.GetObjectByHandle(importedId);Check(typed instanceof DxfSun,'Native SUN typed');Equal(DxfSunShadowType.AreaSampled,typed.ShadowType,'Native shadow type2');Equal(54000000,typed.StoredTime,'Native raw time');Equal(0xffffff,typed.TrueColor,'Native truecolor');Equal(0,doc.Objects.Validate().Count,'Native graph validates');
  const out=new MemoryStream();try{Check(doc.Save(out,b),'Native SUN output');OleWriteArtifact(`sun-native-${file.replace(/\.dxf$/,'')}-${BooleanName(b)}.dxf`,out.ToArray());out.Position=0;Equal(OwnershipTagValues(t),OwnershipTagValues(sunRecord(DxfRawDocument.Load(out)).Tags),'Native complete record exact after disclosed identity and external owner relocation');}finally{out.Dispose();}
}
