// Port of pinned TextHexTests.cs; reflection factories use the same JavaScript codec class.
import { DxfDocument, MemoryStream, XData, XDataRecord, XDataCode, ApplicationRegistry, Line, Vector3 } from '../../index.js';
import { TextCodeValueReader } from '../../netDxf/IO/TextCodeValueReader.js';
import { FormatException, EndOfStreamException } from '../../runtime/Errors.js';
import { Run, Check, Equal, SupportedVersions, VersionName } from './TestHarness.js';
export function RegisterTextHexTests(){for(const code of [...Array.from({length:10},(_,i)=>310+i),1004]){const prefix=`text/binary-chunk/${code}`;
  Run(prefix+'/mixed-case',()=>TextHexValue(code,'00aF10Ff',Uint8Array.of(0,175,16,255)));Run(prefix+'/empty',()=>TextHexValue(code,'',new Uint8Array()));Run(prefix+'/all-byte-values',()=>TextHexAllBytes(code));
  Run(prefix+'/odd-length',()=>{for(const v of ['0','ABC','0011223'])TextHexRejected(FormatException,code,v,2);});Run(prefix+'/missing-value',()=>TextHexRejected(EndOfStreamException,code,null,2));
  Run(prefix+'/invalid-digit',()=>{for(const v of ['0G','G0','FFZZ',' 0','0 ','\t0','0\t','-1','0x','Ｆ0','00\0F'])TextHexRejected(FormatException,code,v,2);});Run(prefix+'/line-diagnostic',()=>TextHexRejected(FormatException,code,'Z0',4));
}for(const v of SupportedVersions)for(const b of [false,true])Run(`xdata/binary-chunks/${VersionName(v)}/${b?'binary':'text'}`,()=>XDataBinaryChunkRoundTrip(v,b));}
export function TextHexValue(code,value,expected){const reader=new TextCodeValueReader(`${code}\n${value}\n0\nEOF\n`);reader.Next();Equal(expected,reader.ReadBytes(),'Hex decoding changed the binary payload.');reader.Next();Equal('EOF',reader.ReadString(),'record after binary chunk');}
export function TextHexAllBytes(code){const all=Uint8Array.from({length:256},(_,i)=>i);for(let start=0;start<all.length;start+=127){const part=all.slice(start,start+127),upper=Buffer.from(part).toString('hex').toUpperCase();TextHexValue(code,upper,part);TextHexValue(code,upper.toLowerCase(),part);}}
export function TextHexRejected(Type,code,value,line){const reader=new TextCodeValueReader((line===4?'999\ncomment\n':'')+code+'\n'+(value===null?'':value+'\n'));if(line===4)reader.Next();let failure;try{reader.Next();}catch(error){failure=error;}Check(failure instanceof Type,`Expected ${Type.name}; malformed binary data must not become an empty payload.`);Check(failure.message.includes('group code '+code),'Malformed binary chunk diagnostic must identify its group code.');Check(failure.message.includes('line '+line),'Malformed binary chunk diagnostic must identify the value line.');}
export function XDataBinaryChunkRoundTrip(version,binary){const app='DXF_HEX_CONFORMANCE',expected=Uint8Array.from({length:256},(_,i)=>i),xdata=new XData(new ApplicationRegistry(app));
  for(let i=0;i<expected.length;i+=127)xdata.XDataRecord.Add(new XDataRecord(XDataCode.BinaryData,expected.slice(i,i+127)));const line=new Line(Vector3.Zero,new Vector3(1,2,3));line.XData.Add(xdata);const doc=new DxfDocument(version);doc.Entities.Add(line);
  const stream=new MemoryStream();try{Check(doc.Save(stream,binary),'XData fixture failed to save.');stream.Position=0;const loaded=DxfDocument.Load(stream);Check(loaded!==null,'XData fixture failed to load.');const lines=Array.from(loaded.Entities.Lines);Equal(1,lines.length,'Single line');const records=Array.from(lines[0].XData.get_Item(app).XDataRecord);Equal(3,records.length,'binary XData chunk count');Check(records.every(r=>r.Code===XDataCode.BinaryData),'XData record types changed.');Equal(expected,Uint8Array.from(records.flatMap(r=>Array.from(r.Value))),'Binary XData payload did not round trip exactly.');}finally{stream.Dispose();}}
