// Port of pinned TransparencyBoundaryTests.cs; exact packed values and ancillary tags retained.
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { DxfDocument, DxfRawDocument, DxfTag, MemoryStream, Layer, Transparency, LayerState, LayerStateProperties, LayerPropertiesRestoreFlags } from '../../node-entry.js';
import { ArgumentOutOfRangeException } from '../../runtime/Errors.js';
import { Run, Check, Equal, Throws, SupportedVersions, VersionName, BooleanName } from './TestHarness.js';
const artifacts=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../../artifacts/conformance/fixtures');
const single=items=>{const a=Array.from(items);Equal(1,a.length,'Expected one item');return a[0];};
const hex=p=>(p>>>0).toString(16).toUpperCase().padStart(8,'0');
function artifact(name,bytes){fs.mkdirSync(artifacts,{recursive:true});fs.writeFileSync(path.join(artifacts,name),bytes);}
export function RegisterTransparencyBoundaryTests(){for(const v of SupportedVersions)for(const b of [false,true]){const suffix=`${VersionName(v)}/${BooleanName(b)}`;for(const count of [0,1,2])Run(`transparency/boundary/layer-${count}/${suffix}`,()=>TransparencyAncillary(v,b,count));for(const packed of [0x020000fe,0x020000ff,0x810012ff|0,0])Run(`transparency/boundary/state-${hex(packed)}/${suffix}`,()=>TransparencyLayerState(v,b,packed));Run(`transparency/boundary/authored/${suffix}`,()=>TransparencyAuthored(v,b));}}
function saveArtifact(doc,version,binary,stem,phase){const stream=new MemoryStream();try{Check(doc.Save(stream,binary),'Transparency artifact save');artifact(`${stem}-${VersionName(version)}-${BooleanName(binary)}-${phase}.dxf`,stream.ToArray());}finally{stream.Dispose();}}
export function TransparencyRaw(doc,binary){const stream=new MemoryStream();try{Check(doc.Save(stream,binary),'Transparency boundary save');stream.Position=0;return DxfRawDocument.Load(stream);}finally{stream.Dispose();}}
export function TransparencyLoad(raw,binary){const stream=new MemoryStream();try{raw.Save(stream,binary);stream.Position=0;const doc=DxfDocument.Load(stream);Check(doc!==null,'Transparency boundary load');return doc;}finally{stream.Dispose();}}
function layerRecord(raw,name){return single(single(Array.from(raw.Sections).filter(s=>s.Name==='TABLES')).Records.filter(r=>r.Name==='LAYER'&&Array.from(r.Tags).some(t=>t.Code===2&&t.Value===name)));}
function app(record){const tags=Array.from(record.Tags),at=tags.findIndex(t=>t.Code===1001&&t.Value==='AcCmTransparency');if(at<0)return [];let end=at+1;while(end<tags.length&&tags[end].Code!==1001)end++;return tags.slice(at+1,end);}
function packet(tags){return Array.from(tags,t=>t.Code+':'+(t.Value instanceof Uint8Array?Buffer.from(t.Value).toString('hex').toUpperCase():String(t.Value))).join('|');}
function stateRecord(raw){return single(single(Array.from(raw.Sections).filter(s=>s.Name==='OBJECTS')).Records.filter(r=>r.Name==='XRECORD'&&Array.from(r.Tags).some(t=>t.Code===440)));}
export function TransparencyAncillary(version,binary,slots){const seed=new DxfDocument(version);seed.Layers.Add(new Layer('PRIVATE_ALPHA'));const raw=TransparencyRaw(seed,binary),record=layerRecord(raw,'PRIVATE_ALPHA'),tags=[new DxfTag(1000,'private-before'),new DxfTag(1004,Uint8Array.of(3,0,255))];if(slots===2)tags.push(new DxfTag(1071,0x02000080));if(slots!==0)tags.push(new DxfTag(1071,0x020000ff));tags.push(new DxfTag(1040,1.25),new DxfTag(1000,'private-after'));
  const doc=TransparencyLoad(raw.WithRecord(record,[...record.Tags,new DxfTag(1001,'AcCmTransparency'),...tags]),binary),layer=doc.Layers.get_Item('PRIVATE_ALPHA');Equal(slots===0?null:0x020000ff,layer.Transparency.StoredAlphaValue,'Last1071 projection/presence');Equal(packet(tags),packet(app(layerRecord(TransparencyRaw(doc,binary),layer.Name))),'Untouched ancillary packet');saveArtifact(doc,version,binary,'transparency-ancillary-'+slots,'untouched');const copy=layer.Clone();copy.Name='PRIVATE_ALPHA_COPY';doc.Layers.Add(copy);Equal(packet(tags),packet(app(layerRecord(TransparencyRaw(doc,binary),copy.Name))),'Cloned ancillary packet');saveArtifact(doc,version,binary,'transparency-ancillary-'+slots,'cloned');Throws(ArgumentOutOfRangeException,()=>{layer.Transparency.Value=-1;});Equal(packet(tags),packet(app(layerRecord(TransparencyRaw(doc,binary),layer.Name))),'Failed edit changed ancillary packet');
  for(const value of [0,25]){layer.Transparency.Value=value;const index=tags.findLastIndex(t=>t.Code===1071),replacement=new DxfTag(1071,Transparency.ToAlphaValue(new Transparency(value)));if(index<0)tags.push(replacement);else tags[index]=replacement;Equal(packet(tags),packet(app(layerRecord(TransparencyRaw(doc,binary),layer.Name))),'Edit must preserve every ancillary tag and earlier1071 slot');const loaded=TransparencyLoad(TransparencyRaw(doc,binary),binary);Equal(value,loaded.Layers.get_Item(layer.Name).Transparency.Value,'Edited ancillary transparency reload');saveArtifact(doc,version,binary,'transparency-ancillary-'+slots,value===0?'zero':'25');}
  layer.Transparency=new Transparency(0);tags[tags.findLastIndex(t=>t.Code===1071)]=new DxfTag(1071,0x020000ff);Equal(packet(tags),packet(app(layerRecord(TransparencyRaw(doc,binary),layer.Name))),'Whole-value assignment must replace cached transparency and retain ancillary tags');saveArtifact(doc,version,binary,'transparency-ancillary-'+slots,'assigned');
}
export function TransparencyLayerState(version,binary,packed){const doc=new DxfDocument(version),layer=new Layer('STATE_ALPHA_LAYER');layer.Transparency=Transparency.FromAlphaValue(packed);doc.Layers.Add(layer);doc.Layers.StateManager.AddNew('STATE_ALPHA');saveArtifact(doc,version,binary,`transparency-state-${hex(packed)}`,'captured');const raw=TransparencyRaw(doc,binary),record=stateRecord(raw),tags=Array.from(record.Tags),start=tags.findIndex(t=>t.Code===330&&t.Value===layer.Handle),slot=tags.findIndex((t,i)=>i>=start&&t.Code===440);Equal(packed===0?0x01000000:packed,tags[slot].Value,'State capture preserves effective zero convention and all unambiguous packed values');tags[slot]=new DxfTag(440,packed);const input=raw.WithRecord(record,tags),bytes=new MemoryStream();try{input.Save(bytes,binary);artifact(`transparency-state-${hex(packed)}-${VersionName(version)}-${BooleanName(binary)}-input.dxf`,bytes.ToArray());}finally{bytes.Dispose();}
  const loaded=TransparencyLoad(input,binary),properties=loaded.Layers.StateManager.get_Item('STATE_ALPHA').Properties,alpha=properties.get_Item(layer.Name).Transparency;Equal(packed,alpha.StoredAlphaValue,'Layer-state input alpha presence');if(packed===0)Equal(0,alpha.Value,'Layer-state numeric zero effective opaque contract');Equal(packed,properties.get_Item(layer.Name).Clone().Transparency.StoredAlphaValue,'Layer-state clone packed alpha');saveArtifact(loaded,version,binary,`transparency-state-${hex(packed)}`,'preserved');
  const las=path.join(artifacts,`transparency-las-${hex(packed)}-${VersionName(version)}-${BooleanName(binary)}-source.las`);Check(loaded.Layers.StateManager.get_Item('STATE_ALPHA').Save(las),'Packed LAS save');const lasState=LayerState.Load(las);Check(lasState!==null,'Packed LAS load');Equal(packed,lasState.Properties.get_Item(layer.Name).Transparency.StoredAlphaValue,'LAS packed alpha presence');Equal(alpha.Value,lasState.Properties.get_Item(layer.Name).Transparency.Value,'LAS effective alpha');Check(lasState.Save(path.join(artifacts,`transparency-las-${hex(packed)}-${VersionName(version)}-${BooleanName(binary)}-resaved.las`)),'LAS exact resave');
  const temp=fs.mkdtempSync(path.join(os.tmpdir(),'netdxf-alpha-'));try{const lines=fs.readFileSync(las,'utf8').split(/\r\n|\n|\r/);if(lines.at(-1)==='')lines.pop();fs.writeFileSync(path.join(temp,'bad.las'),lines.slice(0,-1).join('\n')+'\n');Check(LayerState.Load(path.join(temp,'bad.las'))===null,'LAS accepted a dangling value');}finally{fs.rmSync(temp,{recursive:true,force:true});}
  if(packed===0){const target=new Layer('TRANSFER_ALPHA');target.Transparency=Transparency.FromAlphaValue(0x02000080);loaded.Layers.Add(target);TransparencyRaw(loaded,binary);const applied=new LayerStateProperties(target.Name);applied.Transparency=alpha.Clone();applied.CopyTo(target,LayerPropertiesRestoreFlags.Transparency);Check(target.Transparency.StoredAlphaValue===null&&target.Transparency.Value===0,'State-to-layer transfer must preserve effective opaque zero');Equal(0,TransparencyLoad(TransparencyRaw(loaded,binary),binary).Layers.get_Item(target.Name).Transparency.Value,'State-to-layer zero meaning changed on reload');const normal=new Layer('CAPTURE_ALPHA');normal.Transparency=Transparency.FromAlphaValue(0);const captured=new LayerStateProperties(normal);Check(captured.Transparency.StoredAlphaValue===null&&captured.Transparency.Value===100,'Constructor capture must retain effective normal zero');captured.CopyFrom(normal,LayerPropertiesRestoreFlags.Transparency);Check(captured.Transparency.StoredAlphaValue===null&&captured.Transparency.Value===100,'CopyFrom capture must retain effective normal zero');Equal(0,alpha.StoredAlphaValue,'Carrier transfer changed source raw zero');loaded.Layers.Add(normal);properties.Add(normal.Name,captured);saveArtifact(loaded,version,binary,`transparency-state-${hex(packed)}`,'transfer');}
  const outputTags=Array.from(stateRecord(TransparencyRaw(loaded,binary)).Tags),owner=outputTags.findIndex(t=>t.Code===330&&t.Value===layer.Handle);Equal(packed,outputTags[outputTags.findIndex((t,i)=>i>=owner&&t.Code===440)].Value,'Layer-state exact alpha reload/save');
}
export function TransparencyAuthored(version,binary){const doc=new DxfDocument(version);doc.Layers.Add(new Layer('DEFAULT_ALPHA'));doc.Layers.StateManager.AddNew('DEFAULT_ALPHA_STATE');const raw=TransparencyRaw(doc,binary);Check(!Array.from(layerRecord(raw,'DEFAULT_ALPHA').Tags).some(t=>t.Code===1001&&t.Value==='AcCmTransparency'),'Default authored layer acquired transparency XData');Check(Array.from(single(Array.from(raw.Sections).filter(s=>s.Name==='OBJECTS')).Records).filter(r=>r.Name==='XRECORD').flatMap(r=>Array.from(r.Tags)).filter(t=>t.Code===440).every(t=>t.Value===0),'Authored state opaque encoding changed');const output=new MemoryStream();try{Check(doc.Save(output,binary),'Authored alpha artifact');artifact(`transparency-authored-${VersionName(version)}-${BooleanName(binary)}.dxf`,output.ToArray());}finally{output.Dispose();}}
