// Port of pinned UcsBaseTests.cs; stored orthographic relationships are not geometric evaluation.
import fs from 'node:fs';
import { createHash } from 'node:crypto';
import { DxfDocument, DxfRawDocument, DxfTag, DxfVersion, UCS, UcsOrthographicType, View, ViewUcs, VPort, Vector3, MemoryStream } from '../../index.js';
import { ArgumentException, ArgumentOutOfRangeException, FormatException, InvalidDataException } from '../../runtime/Errors.js';
import { Run, Check, Equal, Throws, SupportedVersions, VersionName, BooleanName } from './TestHarness.js';
const single=items=>{const a=Array.from(items);Equal(1,a.length,'Expected one item');return a[0];};
const uses=ucs=>Array.from(ucs.GetReferences()).reduce((n,r)=>n+r.Uses,0);
const seed=doc=>doc.NumHandles;
const defects=['negative-type','unknown-type','missing-type','zero-type','zero-type-null','duplicate-type','duplicate-reference','missing-target','wrong-target-kind','discarded-target','missing-target-identity','invalid-owner-name','duplicate-owner-name','missing-owner-identity'];
function artifact(name,bytes){const dir=new URL('../../artifacts/conformance/fixtures/',import.meta.url);fs.mkdirSync(dir,{recursive:true});fs.writeFileSync(new URL(name,dir),bytes);}
export function RegisterUcsBaseTests(){for(const v of SupportedVersions)for(const b of [false,true]){const suffix=`${VersionName(v)}/${BooleanName(b)}`;for(const [name,fn]of[['producer',UcsBaseProducer],['explicit-null',UcsBaseNull],['canonical-forward',UcsBaseCanonical],['private-context',UcsBasePrivate],['cycles',UcsBaseCycles],['all-types',UcsBaseTypes]])Run(`ucs-base/${name}/${suffix}`,()=>fn(v,b));for(const d of defects)Run(`ucs-base/malformed/${suffix}/${d}`,()=>UcsBaseMalformed(v,b,d));}Run('ucs-base/atomic-reference-lifecycle',UcsBaseLifecycle);Run('ucs-base/explicit-clone-mapping',UcsBaseClone);}
export function UcsBaseRaw(version,binary){const root=new URL('../../../tests/fixtures/ucs-record-base/carriers/',import.meta.url),name=`carrier-ucs-base-R${VersionName(version).replace('AutoCad','')}-${binary?'binary':'ascii'}.dxf`,bytes=fs.readFileSync(new URL(name,root)),metadata=JSON.parse(fs.readFileSync(new URL('manifest.json',root),'utf8')),entry=single(metadata.files.filter(i=>i.file===name));Equal(entry.sha256,createHash('sha256').update(bytes).digest('hex'),'Pinned independent producer bytes');UcsBaseAssertTransport(bytes,binary);const input=new MemoryStream(bytes);try{return DxfRawDocument.Load(input);}finally{input.Dispose();}}
export function UcsBaseRecord(raw,name){return single(Array.from(single(Array.from(raw.Sections).filter(s=>s.Name==='TABLES')).Records).filter(r=>r.Name==='UCS'&&Array.from(r.Tags).some(t=>t.Code===2&&t.Value===name)));}
export function UcsBaseAssertTransport(bytes,binary){const sentinel=Buffer.from('AutoCAD Binary DXF\r\n\x1a\0','ascii');Equal(binary,Buffer.from(bytes).subarray(0,sentinel.length).equals(sentinel),'Actual input bytes use the named DXF transport');}
export function UcsBaseLoad(raw){const bytes=new MemoryStream();try{raw.Save(bytes,raw.IsBinary);UcsBaseAssertTransport(bytes.ToArray(),raw.IsBinary);bytes.Position=0;const doc=DxfDocument.Load(bytes);Check(doc!==null,'UCS base load failed.');return doc;}finally{bytes.Dispose();}}
export function UcsBaseRoundTrip(doc,binary,output=null){const bytes=new MemoryStream();try{Check(doc.Save(bytes,binary),'UCS base save');if(output!==null)artifact(output,bytes.ToArray());bytes.Position=0;const next=DxfDocument.Load(bytes);Check(next!==null,'UCS base roundtrip load failed.');return next;}finally{bytes.Dispose();}}
export function UcsBaseAssert(doc){const child=doc.UCSs.get_Item('LEFT_FROM_SURVEY'),parent=doc.UCSs.get_Item('SURVEY_BASE'),world=doc.UCSs.get_Item('BOTTOM_FROM_WORLD');Equal(5,child.OrthographicViewType,'Stored group79 differs from origin override');Check(child.BaseUcs===parent,'Actual base object identity');Equal('E',child.Handle,'Independent child handle');Equal('F',parent.Handle,'Independent base handle');Equal(new Vector3(7,8,9),child.OrthographicOrigins.get_Item(UcsOrthographicType.Right),'Distinct group71 origin override');Equal(-8.5,child.Elevation,'Child elevation');Equal(new Vector3(100,200,300),child.Origin,'Stored child origin');Equal(0,parent.OrthographicViewType,'Ordinary base frame');Check(parent.BaseUcs===null,'Ordinary UCS has no base');Equal(2,world.OrthographicViewType,'WORLD-based orthographic type');Check(world.BaseUcs===null,'Absent base means WORLD');Check(Array.from(parent.GetReferences()).some(r=>r.Reference===child&&r.Uses===1),'UCS base incoming count');Check(!doc.UCSs.Remove(parent),'Referenced base cannot be removed');Equal(1,Array.from(doc.Entities.Lines).length,'Following geometry retained');Equal(0,doc.Objects.Validate().Count,'Database remains valid');}
export function UcsBaseProducer(version,binary){let doc=UcsBaseLoad(UcsBaseRaw(version,binary));for(let cycle=0;cycle<3;cycle++){UcsBaseAssert(doc);doc=UcsBaseRoundTrip(doc,binary,cycle===2?`ucs-base-${VersionName(version)}-${BooleanName(binary)}.dxf`:null);}UcsBaseAssert(doc);const child=doc.UCSs.get_Item('LEFT_FROM_SURVEY'),parent=child.BaseUcs;child.SetOrthographicBase(2);Check(doc.UCSs.Remove(parent),'Retarget to WORLD releases base');Equal(2,child.OrthographicViewType,'Edited WORLD type');doc=UcsBaseRoundTrip(doc,binary);Check(doc.UCSs.get_Item('LEFT_FROM_SURVEY').BaseUcs===null,'WORLD edit persists');}
export function UcsBaseNull(version,binary){let raw=UcsBaseRaw(version,binary);const child=UcsBaseRecord(raw,'LEFT_FROM_SURVEY');raw=raw.WithRecord(child,Array.from(child.Tags,t=>t.Code===346?new DxfTag(346,'0000'):t));const doc=UcsBaseLoad(raw),typed=doc.UCSs.get_Item('LEFT_FROM_SURVEY');Equal(5,typed.OrthographicViewType,'Explicit-null type');Check(typed.BaseUcs===null,'Numeric null remains WORLD');const clone=typed.Clone('NULL_COPY');doc.UCSs.Add(clone);const bytes=new MemoryStream(),cleared=new MemoryStream();try{Check(doc.Save(bytes,binary),'Explicit-null output');bytes.Position=0;const after=DxfRawDocument.Load(bytes);for(const name of ['LEFT_FROM_SURVEY','NULL_COPY'])Equal('0',single(Array.from(UcsBaseRecord(after,name).Tags).filter(t=>t.Code===346)).Value,'Physical null346 presence retained through load and clone');artifact(`ucs-base-null-${VersionName(version)}-${BooleanName(binary)}.dxf`,bytes.ToArray());typed.SetOrthographicBase(5);clone.SetOrthographicBase(0);Check(doc.Save(cleared,binary),'Cleared null presence');cleared.Position=0;const edited=DxfRawDocument.Load(cleared);Check(!Array.from(UcsBaseRecord(edited,'LEFT_FROM_SURVEY').Tags).some(t=>t.Code===346)&&!Array.from(UcsBaseRecord(edited,'NULL_COPY').Tags).some(t=>t.Code===346),'Explicit edits can clear physical base slot');}finally{cleared.Dispose();bytes.Dispose();}}
export function UcsBaseCanonical(version,binary){let raw=UcsBaseRaw(version,binary),parent=UcsBaseRecord(raw,'SURVEY_BASE');raw=raw.WithRecord(parent,Array.from(parent.Tags,t=>t.Code===5?new DxfTag(5,'000f'):t));const child=UcsBaseRecord(raw,'LEFT_FROM_SURVEY');raw=raw.WithRecord(child,Array.from(child.Tags,t=>t.Code===346?new DxfTag(346,'00f'):t));UcsBaseAssert(UcsBaseLoad(raw));}
export function UcsBasePrivate(version,binary){for(const context of [0,1,2,3]){let raw=UcsBaseRaw(version,binary);const child=UcsBaseRecord(raw,'LEFT_FROM_SURVEY'),tags=Array.from(child.Tags),tag=(c,v)=>new DxfTag(c,v);if(context===3){tags.splice(tags.findIndex(t=>t.Code===79),0,tag(102,'{PRIVATE'),tag(1001,'PRIVATE_APP'),tag(1000,'Private payload'),tag(102,'}'));raw=raw.WithRecord(child,tags);UcsBaseAssert(UcsBaseLoad(raw));continue;}tags.push(...(context===0?[tag(102,'{PRIVATE'),tag(102,'{NESTED')]:context===1?[tag(100,'PrivateUcs')]:[tag(1001,'UCS_TRAILER'),tag(1000,'Stored metadata')]),tag(79,7),tag(346,'ABCDEF'));if(context===0)tags.push(tag(102,'}'),tag(102,'}'));raw=raw.WithRecord(child,tags);UcsBaseAssert(UcsBaseLoad(raw));}}
export function UcsBaseTypes(version,binary){let doc=new DxfDocument(version),parent=doc.UCSs.Add(new UCS('BASE'));for(let type=1;type<=6;type++)doc.UCSs.Add(new UCS('TYPE_'+type)).SetOrthographicBase(type,parent);doc=UcsBaseRoundTrip(doc,binary);parent=doc.UCSs.get_Item('BASE');Equal(6,uses(parent),'Every orthographic type holds its own reference');for(let type=1;type<=6;type++){const child=doc.UCSs.get_Item('TYPE_'+type);Equal(type,child.OrthographicViewType,'All stored view types survive');Check(child.BaseUcs===parent,'All types resolve the same actual base');child.SetOrthographicBase(type);}Check(doc.UCSs.Remove(parent),'All WORLD edits release the common base');doc=UcsBaseRoundTrip(doc,binary);for(let type=1;type<=6;type++){const child=doc.UCSs.get_Item('TYPE_'+type);Equal(type,child.OrthographicViewType,'All WORLD types survive');Check(child.BaseUcs===null,'All WORLD types omit their base');}}
export function UcsBaseCycles(version,binary){let doc=new DxfDocument(version),first=doc.UCSs.Add(new UCS('CYCLE_A')),second=doc.UCSs.Add(new UCS('CYCLE_B')),self=doc.UCSs.Add(new UCS('SELF'));first.SetOrthographicBase(1,second);second.SetOrthographicBase(2,first);self.SetOrthographicBase(3,self);doc=UcsBaseRoundTrip(doc,binary);first=doc.UCSs.get_Item('CYCLE_A');second=doc.UCSs.get_Item('CYCLE_B');self=doc.UCSs.get_Item('SELF');Check(first.BaseUcs===second&&second.BaseUcs===first&&self.BaseUcs===self,'Cycles remain explicit stored references without recursive evaluation');Check(!doc.UCSs.Remove(first)&&!doc.UCSs.Remove(second)&&!doc.UCSs.Remove(self),'Cycle references protect deletion');first.SetOrthographicBase(0);self.SetOrthographicBase(0);Check(doc.UCSs.Remove(second)&&doc.UCSs.Remove(first)&&doc.UCSs.Remove(self),'Explicit unlink releases cycles without cascade');}
export function UcsBaseMalformed(version,binary,defect){let raw=UcsBaseRaw(version,binary),child=UcsBaseRecord(raw,'LEFT_FROM_SURVEY');const tags=Array.from(child.Tags),set=(c,v)=>{const at=tags.findIndex(t=>t.Code===c);Check(at>=0,'Expected fixture field');tags[at]=new DxfTag(c,v);};
  switch(defect){case 'negative-type':set(79,-1);break;case 'unknown-type':set(79,7);break;case 'missing-type':for(let i=tags.length-1;i>=0;i--)if(tags[i].Code===79)tags.splice(i,1);break;case 'zero-type':set(79,0);break;case 'zero-type-null':set(79,0);set(346,'0');break;case 'duplicate-type':tags.push(new DxfTag(79,5));break;case 'duplicate-reference':tags.push(new DxfTag(346,'F'));break;case 'missing-target':set(346,'ABCDEF');break;case 'wrong-target-kind':set(346,single(Array.from(single(Array.from(single(Array.from(raw.Sections).filter(s=>s.Name==='ENTITIES')).Records).filter(r=>r.Name==='LINE')).Tags).filter(t=>t.Code===5)).Value);break;
    case 'discarded-target':{const target=UcsBaseRecord(raw,'SURVEY_BASE');raw=raw.WithRecord(target,Array.from(target.Tags,t=>t.Code===2?new DxfTag(2,'INVALID/NAME'):t));break;}
    case 'missing-target-identity':{const target=UcsBaseRecord(raw,'SURVEY_BASE');raw=raw.WithRecord(target,Array.from(target.Tags).filter(t=>t.Code!==5));break;}
    case 'invalid-owner-name':set(2,'INVALID/NAME');break;case 'duplicate-owner-name':set(2,'BOTTOM_FROM_WORLD');break;case 'missing-owner-identity':for(let i=tags.length-1;i>=0;i--)if(tags[i].Code===5)tags.splice(i,1);break;}
  child=UcsBaseRecord(raw,'LEFT_FROM_SURVEY');raw=raw.WithRecord(child,tags);const bytes=new MemoryStream();try{raw.Save(bytes,binary);UcsBaseAssertTransport(bytes.ToArray(),binary);bytes.Position=0;let rejected=false;try{rejected=DxfDocument.Load(bytes)===null;}catch(error){if(error instanceof FormatException||error instanceof ArgumentException||error instanceof InvalidDataException)rejected=true;else throw error;}Check(rejected,'Malformed or unretained UCS base relationship must reject: '+defect);}finally{bytes.Dispose();}
}
export function UcsBaseLifecycle(){const doc=new DxfDocument(DxfVersion.AutoCad2018);void doc.Objects;const first=doc.UCSs.Add(new UCS('FIRST')),second=doc.UCSs.Add(new UCS('SECOND')),child=doc.UCSs.Add(new UCS('CHILD'));child.SetOrthographicBase(5,first);const view=doc.Views.Add(Object.assign(new View('USES_FIRST'),{Ucs:Object.assign(new ViewUcs(),{NamedUcs:first})})),port=doc.VPorts.AddRecord(Object.assign(new VPort('USES_FIRST'),{NamedUcs:first}));Equal(3,uses(first),'UCS, VIEW and VPORT counts combine');const before=seed(doc);for(const bad of [-1,7])Throws(ArgumentOutOfRangeException,()=>child.SetOrthographicBase(bad,second));Throws(ArgumentException,()=>child.SetOrthographicBase(0,second));const foreign=new DxfDocument(DxfVersion.AutoCad2018),foreignUcs=foreign.UCSs.Add(new UCS('SECOND'));Throws(ArgumentException,()=>child.SetOrthographicBase(2,foreignUcs));Throws(ArgumentException,()=>child.SetOrthographicBase(2,new UCS('DETACHED')));Check(child.BaseUcs===first&&child.OrthographicViewType===5,'Rejected pair changes neither value');Equal(before,seed(doc),'Rejected pair allocates no handles');Equal(3,uses(first),'Rejected pair preserves all counts');child.SetOrthographicBase(6,second);Equal(2,uses(first),'Previous base count released');Equal(1,uses(second),'New base count added');child.SetOrthographicBase(4,second);Equal(1,uses(second),'Retarget same identity does not duplicate use');child.Name='RENAMED_CHILD';second.Name='RENAMED_BASE';Check(single(second.GetReferences()).Reference===child,'Rename preserves reference identity bookkeeping');Check(!doc.UCSs.Remove(second),'Referenced base protected after rename');Check(doc.UCSs.Remove(child),'Removing referring UCS releases outgoing base');Check(doc.UCSs.Remove(second),'Base can be removed after last dependent');view.Ucs.NamedUcs=null;port.NamedUcs=null;Check(doc.UCSs.Remove(first),'Mixed owner references release correctly');}
export function UcsBaseClone(){const source=new DxfDocument(DxfVersion.AutoCad2018),parent=source.UCSs.Add(new UCS('PARENT')),child=source.UCSs.Add(new UCS('CHILD'));child.SetOrthographicBase(5,parent);child.SetOrthographicOrigin(UcsOrthographicType.Right,new Vector3(7,8,9));const copy=child.Clone('COPY');Check(copy.BaseUcs===parent&&copy.OrthographicViewType===5,'Detached clone retains actual base identity');const destination=new DxfDocument(DxfVersion.AutoCad2018);void destination.Objects;const sameName=destination.UCSs.Add(new UCS('PARENT')),before=seed(destination),count=destination.UCSs.Count;Throws(ArgumentException,()=>destination.UCSs.Add(copy));Equal(before,seed(destination),'Foreign adoption preflights before handle allocation');Equal(count,destination.UCSs.Count,'Foreign adoption keeps collection atomic');Check(copy.Owner===null&&copy.Handle===null&&copy.BaseUcs===parent,'Failed adoption preserves detached clone and source dependency');copy.SetOrthographicBase(copy.OrthographicViewType,sameName);destination.UCSs.Add(copy);Check(copy.BaseUcs===sameName,'Explicit remap permits destination adoption');Check(!destination.UCSs.Remove(sameName),'Mapped destination target protected');copy.SetOrthographicOrigin(UcsOrthographicType.Right,Vector3.Zero);Equal(new Vector3(7,8,9),child.OrthographicOrigins.get_Item(UcsOrthographicType.Right),'Base relation clone does not share origin overrides');const ignored=child.Clone('COPY');Check(destination.UCSs.Add(ignored)===copy&&ignored.Owner===null,'Existing-name lookup does not adopt foreign candidate');Check(destination.UCSs.Remove(copy)&&destination.UCSs.Remove(sameName),'Explicit clone teardown releases destination references');Check(child.BaseUcs===parent&&parent.Owner===source.UCSs,'Source identity unaffected');}
