// Complete original non-IO cases. Writer/opaque/loaded-profile controls stay
// unported until the typed Load/Save assertions can be executed without omission.
import * as api from '../../index.js';
import { PeekDocumentObjects } from '../../netDxf/DxfDocument.Objects.js';
import { ColumnModel } from './MTextColumnTests.js';
import { ArgumentOutOfRangeException, InvalidOperationException, NotSupportedException } from '../../runtime/Errors.js';
import { Run, Check, Equal, Throws, SupportedVersions } from './TestHarness.js';
export class CompatibilityState {
  constructor(document){Object.assign(this,{document,database:PeekDocumentObjects(document),version:document.DrawingVariables.AcadVer,seed:document.NumHandles,headerSeed:document.DrawingVariables.HandleSeed,registered:Array.from(document.AddedObjects),apps:document.ApplicationRegistries.Count,classes:document.Classes.Count});}
  CheckUnchanged(){const d=this.document;Check(this.database===PeekDocumentObjects(d),'Analysis created/replaced object database.');Equal(this.version,d.DrawingVariables.AcadVer);Equal(this.seed,d.NumHandles);Equal(this.headerSeed,d.DrawingVariables.HandleSeed);const current=Array.from(d.AddedObjects);Check(current.length===this.registered.length&&current.every((p,i)=>p.Key===this.registered[i].Key&&p.Value===this.registered[i].Value),'Analysis changed registrations.');Equal(this.apps,d.ApplicationRegistries.Count);Equal(this.classes,d.Classes.Count);}
}
export const CompatibilityDescription=item=>`${item.Code}|${item.Kind}|${item.SourceHandle}|${item.SourceCodeName}|${item.PropertyPath}|${item.Message}`;
export function CompatibilityAnalyze(document,target){const state=new CompatibilityState(document),report=document.AnalyzeVersionCompatibility(target);state.CheckUnchanged();Equal(document.DrawingVariables.AcadVer,report.SourceVersion);Equal(target,report.TargetVersion);const second=document.AnalyzeVersionCompatibility(target);state.CheckUnchanged();Equal(Array.from(report.Diagnostics,CompatibilityDescription),Array.from(second.Diagnostics,CompatibilityDescription));return report;}
export function CompatibilityPlacement(placement){
  const d=new api.DxfDocument(18),line=new api.Line(api.Vector3.Zero,api.Vector3.UnitX);line.ColorName='';line.ShadowMode=0;let source;
  if(placement==='attdef'||placement==='attrib'){const block=new api.Block('ATTRIBUTE_BLOCK'),definition=new api.AttributeDefinition('TAG');block.AttributeDefinitions.Add(definition);d.Blocks.Add(block);if(placement==='attdef')source=definition;else{const insert=new api.Insert(block);d.Entities.Add(insert);source=Array.from(insert.Attributes)[0];}source.ColorName='';source.ShadowMode=0;}
  else{source=line;if(placement==='model')d.Entities.Add(line);else if(placement==='paper'){const layout=new api.Layout('CompatibilityPaper');d.Layouts.Add(layout);layout.AssociatedBlock.Entities.Add(line);}else{const block=new api.Block('UNUSED_BLOCK');block.Entities.Add(line);d.Blocks.Add(block);if(placement==='nested-block'){const outer=new api.Block('OUTER_UNUSED');outer.Entities.Add(new api.Insert(block));d.Blocks.Add(outer);}}}
  const report=CompatibilityAnalyze(d,13),matches=Array.from(report.Diagnostics).filter(v=>v.SourceObject===source);Equal(2,matches.length);Equal(['ColorName','ShadowMode'],matches.map(v=>v.PropertyPath).sort());
}
export function CompatibilityPristine(){const d=new api.DxfDocument(18);Check(PeekDocumentObjects(d)===null);for(const target of SupportedVersions)CompatibilityAnalyze(d,target);const state=new CompatibilityState(d);Throws(ArgumentOutOfRangeException,()=>d.AnalyzeVersionCompatibility(0));Throws(ArgumentOutOfRangeException,()=>d.AnalyzeVersionCompatibility(2147483647));const old=d.AnalyzeVersionCompatibility(api.DxfVersion.AutoCad12);Equal(1,old.Diagnostics.Count);Equal('DXF_WRITER_PROFILE_UNSUPPORTED',old.Diagnostics.get_Item(0).Code);state.CheckUnchanged();}
export function CompatibilitySnapshot(){const d=new api.DxfDocument(18),source=new api.Line(api.Vector3.Zero,api.Vector3.UnitX);source.ColorName='';d.Entities.Add(source);const report=CompatibilityAnalyze(d,13),item=Array.from(report.Diagnostics).find(v=>v.Code==='ENTITY_COLOR_NAME_PROFILE'),captured=CompatibilityDescription(item);Check(item.SourceObject===source);Throws(NotSupportedException,()=>report.Diagnostics.Clear());source.ColorName=null;d.Entities.Remove(source);d.DrawingVariables.AcadVer=14;Equal(captured,CompatibilityDescription(item));Check(item.SourceObject===source);Equal(18,report.SourceVersion);Check(report.HasKnownRejections);Check(!CompatibilityAnalyze(d,13).HasKnownRejections);}
export function CompatibilityCallbacks(){
  const d=new api.DxfDocument(17),text=new api.MText('FIRSTSECONDTHIRD');text.Columns=ColumnModel(0,api.MTextColumnStorage.Embedded);d.Entities.Add(text.ConvertToLinkedColumns(['FIRST','SECOND','THIRD']));
  class MetadataCallbackRegistry extends api.ApplicationRegistry {Callback=null;Clone(...args){if(!args.length)this.Callback?.();return super.Clone(...args);}}
  const application=new MetadataCallbackRegistry('COMPATIBILITY_CALLBACK');d.ApplicationRegistries.Add(application);Array.from(d.Entities.MTexts)[0].XData.Add(new api.XData(application));let calls=0;application.Callback=()=>{calls++;throw new InvalidOperationException('Analysis invoked clone callback');};for(const target of SupportedVersions)CompatibilityAnalyze(d,target);Equal(0,calls);
}
export function RegisterVersionCompatibilityTests(){for(const placement of ['model','paper','unused-block','nested-block','attdef','attrib'])Run('version-compatibility/traversal/'+placement,()=>CompatibilityPlacement(placement));Run('version-compatibility/pristine-purity',CompatibilityPristine);Run('version-compatibility/live-reference-snapshot',CompatibilitySnapshot);Run('version-compatibility/metadata-callbacks',CompatibilityCallbacks);}
