// Port of pinned ViewLiveSectionTests.cs; actual Section objects remain inert stored geometry.
import fs from 'node:fs';
import { createHash } from 'node:crypto';
import { DxfDocument, DxfRawDocument, DxfTag, DxfVersion, View, Section, Block, Vector3, MemoryStream } from '../../index.js';
import { ArgumentException, InvalidOperationException, InvalidDataException, NotSupportedException, FormatException } from '../../runtime/Errors.js';
import { Run, Check, Equal, SupportedVersions, VersionName, BooleanName } from './TestHarness.js';
const single=items=>{const a=Array.from(items);Equal(1,a.length,'Expected one item');return a[0];};
const records=raw=>Array.from(raw.Sections).flatMap(s=>Array.from(s.Records));
const defects=['missing','wrong-type','duplicate','duplicate-null','section-identity','view-identity','private-handle','private-ref','later-subclass','padded','zero','absent'];
function artifact(name,bytes){const dir=new URL('../../artifacts/conformance/fixtures/',import.meta.url);fs.mkdirSync(dir,{recursive:true});fs.writeFileSync(new URL(name,dir),bytes);}
// Exact shared SectionExample/SectionBytes fixture construction from SectionTests.cs.
function example(code='SECTION'){const s=Object.assign(new Section(code),{Name:'東京 Literal\\U+0041',State:4,Flags:17,VerticalDirection:new Vector3(1,2,3),TopHeight:5.25,BottomHeight:-15.5,IndicatorTransparency:70,StoredIndicatorColor:256,StoredNativeIndicatorColor:9,IndicatorColorName:'Book$Color'});s.Vertices.Add(new Vector3(1,2,3));s.Vertices.Add(new Vector3(-4,5,6));s.BackLineVertices.Add(new Vector3(9,8,7));return s;}
function sectionBytes(doc,binary){const output=new MemoryStream();try{Check(doc.Save(output,binary),'SECTION save');return output.ToArray();}finally{output.Dispose();}}
function loadBytes(bytes){const input=new MemoryStream(bytes);try{return DxfDocument.Load(input);}finally{input.Dispose();}}
export function RegisterViewLiveSectionTests(){for(const v of SupportedVersions.filter(v=>v>=DxfVersion.AutoCad2007))for(const b of [false,true]){const suffix=`${VersionName(v)}/${BooleanName(b)}`;Run(`view-live-section/producer/${suffix}`,()=>ViewSectionProducer(v,b));Run(`view-live-section/lifecycle/${suffix}`,()=>ViewSectionLifecycle(v,b));Run(`view-live-section/foreign/${suffix}`,()=>ViewSectionForeign(v,b));for(const d of defects)Run(`view-live-section/input/${suffix}/${d}`,()=>ViewSectionInput(v,b,d));}for(const v of SupportedVersions.filter(v=>v<DxfVersion.AutoCad2007))for(const b of [false,true])Run(`view-live-section/version/${VersionName(v)}/${BooleanName(b)}`,()=>ViewSectionVersion(v,b));}
export function ViewSectionLoad(raw,binary){const input=new MemoryStream();try{raw.WithTags(Array.from(raw.Tags).filter(t=>t.Code!==999)).Save(input,binary);Equal(binary,Buffer.from(input.ToArray()).subarray(0,18).equals(Buffer.from('AutoCAD Binary DXF')),'VIEW test input transport');input.Position=0;const doc=DxfDocument.Load(input);if(doc===null)throw new InvalidDataException('VIEW load returned null');return doc;}finally{input.Dispose();}}
export function ViewSectionRaw(version){const doc=new DxfDocument(version),section=example('SECTIONOBJECT');doc.Entities.Add(section);doc.Views.Add(Object.assign(new View('Live'),{LiveSection:section}));doc.Views.Add(Object.assign(new View('Null'),{LiveSection:null}));doc.Views.Add(new View('Absent'));const input=new MemoryStream(sectionBytes(doc,false));try{return DxfRawDocument.Load(input);}finally{input.Dispose();}}
export function ViewSectionReject(action){let rejected=false;try{action();}catch(error){if(error instanceof ArgumentException||error instanceof InvalidOperationException||error instanceof InvalidDataException||error instanceof NotSupportedException||error instanceof FormatException)rejected=true;else throw error;}Check(rejected,'VIEW live-section operation was accepted');}
export function ViewSectionProducer(version,binary){const root=new URL('../../../tests/fixtures/view-live-section/',import.meta.url),filename=`ezdxf-view-live-section-R${VersionName(version).replace('AutoCad','')}-${binary?'binary':'ascii'}.dxf`,manifest=JSON.parse(fs.readFileSync(new URL('manifest.json',root),'utf8')),entry=single(manifest.fixtures.filter(e=>e.path===filename)),bytes=fs.readFileSync(new URL(filename,root));Equal(entry.sha256,createHash('sha256').update(bytes).digest('hex'),'VIEW producer fixture hash');Equal(binary,Buffer.from(bytes).subarray(0,18).equals(Buffer.from('AutoCAD Binary DXF')),'VIEW producer input transport');const doc=loadBytes(bytes);if(doc===null)throw new InvalidDataException('Producer VIEW input');const view=doc.Views.get_Item('LiveSectionProducer'),section=single(doc.Entities.Sections);Check(view.LiveSection===section,'Producer VIEW physical target');Equal(entry.section_handle,section.Handle,'Producer section identity');Check(view.HasStoredLiveSection&&doc.Views.get_Item('NullSectionProducer').HasStoredLiveSection&&!doc.Views.get_Item('AbsentSectionProducer').HasStoredLiveSection,'Producer null presence');const output=sectionBytes(doc,binary);artifact(`view-live-section-producer-${VersionName(version)}-${BooleanName(binary)}.dxf`,output);const again=loadBytes(output);Check(again.Views.get_Item(view.Name).LiveSection===single(again.Entities.Sections),'Producer roundtrip identity');}
export function ViewSectionLifecycle(version,binary){const doc=ViewSectionLoad(ViewSectionRaw(version),binary),section=single(doc.Entities.Sections),view=doc.Views.get_Item('Live'),second=view.Clone('Second');doc.Views.Add(second);Check(second.LiveSection===section,'Local clone shared target');const originalOwner=section.Owner,originalHandle=section.Handle;Check(!doc.Entities.Remove(section),'Referenced SECTION removed');ViewSectionReject(()=>doc.Objects.EraseSection(section));Check(section.Owner===originalOwner&&section.Handle===originalHandle&&!section.IsErased,'Rejected removal changed section identity');view.ClearLiveSectionReference();Check(!view.HasStoredLiveSection&&view.LiveSection===null,'Clear retained field');Check(!doc.Entities.Remove(section),'Second consumer did not protect section');second.LiveSection=null;Check(second.HasStoredLiveSection&&second.LiveSection===null,'Explicit null not retained');const roundtrip=loadBytes(sectionBytes(doc,binary));Check(!roundtrip.Views.get_Item('Live').HasStoredLiveSection&&roundtrip.Views.get_Item('Second').HasStoredLiveSection,'Cleared/null output collapsed');second.LiveSection=section;Check(doc.Views.Remove(second),'View consumer removal failed');Check(doc.Entities.Remove(section),'Removed view left stale incoming count');Check(section.Owner===null&&view.LiveSection===null,'Removal owned section through view');const replacement=example('SECTIONOBJECT');doc.Entities.Add(replacement);view.LiveSection=replacement;artifact(`view-live-section-authored-${VersionName(version)}-${BooleanName(binary)}.dxf`,sectionBytes(doc,binary));view.ClearLiveSectionReference();doc.Objects.EraseSection(replacement);Check(replacement.IsErased,'Released section erasure failed');ViewSectionReject(()=>{view.LiveSection=replacement;});const block=new Block('SectionHost');doc.Blocks.Add(block);const nested=example('SECTIONOBJECT');block.Entities.Add(nested);view.LiveSection=nested;Check(!doc.Blocks.Remove(block),'Containing block removed through live reference');view.ClearLiveSectionReference();Check(doc.Blocks.Remove(block),'Released containing block not removed');}
export function ViewSectionForeign(version,binary){const source=ViewSectionLoad(ViewSectionRaw(version),binary),target=new DxfDocument(version),sourceView=source.Views.get_Item('Live'),copy=sourceView.Clone('Foreign'),sameName=example('SECTIONOBJECT');target.Entities.Add(sameName);const seed=target.DrawingVariables.HandleSeed,count=target.Views.Count;ViewSectionReject(()=>target.Views.Add(copy));Equal(seed,target.DrawingVariables.HandleSeed,'Foreign adoption consumed handles');Equal(count,target.Views.Count,'Foreign adoption inserted view');Check(copy.Owner===null&&copy.Handle===null,'Foreign adoption attached refused clone');copy.LiveSection=sameName;target.Views.Add(copy);Check(copy.LiveSection===sameName,'Explicit foreign remap failed');ViewSectionReject(()=>{copy.LiveSection=sourceView.LiveSection;});Check(copy.LiveSection===sameName,'Refused replacement changed existing reference');ViewSectionReject(()=>{copy.LiveSection=new Section();});artifact(`view-live-section-foreign-${VersionName(version)}-${BooleanName(binary)}.dxf`,sectionBytes(target,binary));Check(sourceView.LiveSection!==copy.LiveSection&&sourceView.LiveSection.Owner!==null,'Foreign remap changed source');}
export function ViewSectionInput(version,binary,defect){let raw=ViewSectionRaw(version);const section=single(records(raw).filter(r=>r.Name==='SECTIONOBJECT')),handle=Array.from(section.Tags).find(t=>t.Code===5).Value,layer=Array.from(records(raw).find(r=>r.Name==='LAYER').Tags).find(t=>t.Code===5).Value;
  // Descending physical replacements keep every earlier record's source indices valid.
  const all=Array.from(raw.Tags);
  for(const record of records(raw).sort((a,b)=>b.StartTagIndex-a.StartTagIndex)){const tags=Array.from(record.Tags),live=record.Name==='VIEW'&&tags.some(t=>t.Code===2&&t.Value==='Live');
    if(record.Name==='SECTIONOBJECT'&&defect==='section-identity')tags.splice(2,0,new DxfTag(5,handle));else if(record.Name==='SECTIONOBJECT'&&defect==='private-handle'){for(let i=tags.length-1;i>=0;i--)if(tags[i].Code===5)tags.splice(i,1);tags.splice(1,0,new DxfTag(102,'{PRIVATE'),new DxfTag(5,handle),new DxfTag(102,'}'));}else if(live){const at=tags.findIndex(t=>t.Code===334);Check(at>=0,'Expected live-section field');switch(defect){case 'missing':tags[at]=new DxfTag(334,'ABCDEF01');break;case 'wrong-type':tags[at]=new DxfTag(334,layer);break;case 'duplicate':tags.splice(at,0,new DxfTag(334,handle));break;case 'duplicate-null':tags.splice(at,0,new DxfTag(334,'0'));break;case 'view-identity':tags.splice(2,0,tags.find(t=>t.Code===5));break;case 'private-ref':tags.splice(at,0,new DxfTag(102,'{PRIVATE'),new DxfTag(334,'ABCDEF01'),new DxfTag(102,'}'));break;case 'later-subclass':tags.push(new DxfTag(100,'PrivateView'),new DxfTag(334,'ABCDEF01'));break;case 'padded':tags[at]=new DxfTag(334,'000'+handle.toLowerCase());break;case 'zero':tags[at]=new DxfTag(334,'0000');break;case 'absent':tags.splice(at,1);break;}}
    all.splice(record.StartTagIndex,record.EndTagIndex-record.StartTagIndex,...tags);
  }
  raw=raw.WithTags(all);
  if(['missing','wrong-type','duplicate','duplicate-null','section-identity','view-identity','private-handle'].includes(defect)){ViewSectionReject(()=>ViewSectionLoad(raw,binary));return;}const doc=ViewSectionLoad(raw,binary),view=doc.Views.get_Item('Live');if(defect==='absent')Check(!view.HasStoredLiveSection&&view.LiveSection===null,'Absent VIEW field became present');else if(defect==='zero')Check(view.HasStoredLiveSection&&view.LiveSection===null,'Numeric-null VIEW field changed');else Check(view.LiveSection===single(doc.Entities.Sections),'VIEW reference used private/alternate target');
}
export function ViewSectionVersion(version,binary){const doc=new DxfDocument(version),view=Object.assign(new View('Unsupported'),{LiveSection:null});let seed=doc.DrawingVariables.HandleSeed;ViewSectionReject(()=>doc.Views.Add(view));Equal(seed,doc.DrawingVariables.HandleSeed,'Version rejection allocated identity');view.ClearLiveSectionReference();doc.Views.Add(view);ViewSectionReject(()=>{view.LiveSection=null;});Check(!view.HasStoredLiveSection,'Rejected field assignment mutated presence');const modern=new DxfDocument(DxfVersion.AutoCad2018);modern.Views.Add(Object.assign(new View('Null'),{LiveSection:null}));modern.DrawingVariables.AcadVer=version;const stream=new MemoryStream(new Uint8Array([1,2,3,4,5]),true);stream.Position=2;seed=modern.DrawingVariables.HandleSeed;try{let rejected=false;try{rejected=!modern.Save(stream,binary);}catch(error){if(error instanceof NotSupportedException)rejected=true;else throw error;}Check(rejected,'Older profile silently dropped live-section field');Equal(seed,modern.DrawingVariables.HandleSeed,'Profile rejection allocated identity');Equal(2,stream.Position,'Profile rejection moved stream');Equal(new Uint8Array([1,2,3,4,5]),stream.ToArray(),'Profile rejection changed stream bytes');}finally{stream.Dispose();}}
