// Port of pinned ViewUcsTests.cs; independent fixtures and original lifecycle assertions.
import fs from 'node:fs';
import { createHash } from 'node:crypto';
import { DxfDocument, DxfRawDocument, DxfTag, UCS, UcsFlags, View, ViewUcs, VPort, Vector3, XData, XDataRecord, XDataCode, ApplicationRegistry, MemoryStream } from '../../index.js';
import { ArgumentException, ArgumentOutOfRangeException, InvalidOperationException } from '../../runtime/Errors.js';
import { GetTypedIOConfiguration } from '../../runtime/TypedDocumentIO.js';
import { Run, Check, Equal, Throws, SupportedVersions, VersionName, BooleanName } from './TestHarness.js';
const codes=[72,110,120,130,111,121,131,112,122,132,79,146,345,346];
const defects=['missing-enable','disabled','bad-enable','duplicate-enable','zero-axis','missing-110','missing-120','missing-130','missing-111','missing-121','missing-131','missing-112','missing-122','missing-132','bad-ortho','base-without-ortho','missing-named-target','missing-base-target','wrong-target-type','duplicate-reference','ucs-unsupported-type','ucs-duplicate-flags','vport-missing-target','vport-wrong-target-type','vport-base-without-ortho'];
const single=items=>{const a=Array.from(items);Equal(1,a.length,'Expected one item');return a[0];};
const records=raw=>Array.from(raw.Sections).flatMap(s=>Array.from(s.Records));
const uses=ucs=>Array.from(ucs.GetReferences()).reduce((n,r)=>n+r.Uses,0);
function artifact(name,bytes){const dir=new URL('../../artifacts/conformance/fixtures/',import.meta.url);fs.mkdirSync(dir,{recursive:true});fs.writeFileSync(new URL(name,dir),bytes);}
export function RegisterViewUcsTests(){Run('view-ucs/model-and-lifecycle',ViewUcsLifecycle);Run('view-ucs/clone-and-document-isolation',ViewUcsCloneIsolation);Run('view-ucs/invalid-values',ViewUcsInvalidValues);Run('view-ucs/foreign-registry/ucs',()=>ViewUcsForeignRegistry(true));Run('view-ucs/foreign-registry/view',()=>ViewUcsForeignRegistry(false));
  for(const u of [false,true])for(const s of ['throw','attach','detach','move','collision','attach-throw','move-collision'])Run(`view-ucs/rename/${BooleanName(u)}/${s}`,()=>ViewUcsRename(u,s));
  for(const v of SupportedVersions)for(const b of [false,true]){const suffix=`${VersionName(v)}/${BooleanName(b)}`;Run(`view-ucs/independent/${suffix}`,()=>ViewUcsIndependent(v,b));Run(`view-ucs/reordered/${suffix}`,()=>ViewUcsReordered(v,b));Run(`view-ucs/absence-and-authoring/${suffix}`,()=>ViewUcsAuthoring(v,b));for(const d of defects)Run(`view-ucs/invalid/${suffix}/${d}`,()=>ViewUcsMalformed(v,b,d));}
}
export function ViewUcsRaw(version){const root=new URL('../../../tests/fixtures/view-ucs/',import.meta.url),name=`independent-view-ucs-R${VersionName(version).replace('AutoCad','')}.dxf`,manifest=JSON.parse(fs.readFileSync(new URL('manifest.json',root),'utf8')),fixture=single(manifest.fixtures.filter(f=>f.path===name)),bytes=fs.readFileSync(new URL(name,root));Equal(fixture.sha256,createHash('sha256').update(bytes).digest('hex'),'Independent fixture provenance');const input=new MemoryStream(bytes);try{return DxfRawDocument.Load(input);}finally{input.Dispose();}}
export function ViewUcsInput(raw,binary){const result=new MemoryStream();raw.Save(result,binary);result.Position=0;return result;}
export function ViewUcsLoad(raw,binary){const input=ViewUcsInput(raw,binary);try{const doc=DxfDocument.Load(input);if(doc===null)throw new InvalidOperationException('UCS fixture failed to load.');return doc;}finally{input.Dispose();}}
export function ViewUcsRecord(raw,type,name){return single(records(raw).filter(r=>r.Name===type&&Array.from(r.Tags).some(t=>t.Code===2&&t.Value===name)));}
export function EditViewUcsRecord(raw,type,name,edit){const record=ViewUcsRecord(raw,type,name),tags=Array.from(record.Tags);edit(tags);const all=Array.from(raw.Tags);return raw.WithTags([...all.slice(0,record.StartTagIndex),...tags,...all.slice(record.EndTagIndex)]);}
export function PutViewUcsTag(tags,code,value){const i=tags.findIndex(t=>t.Code===code);if(i>=0)tags[i]=new DxfTag(code,value);else{const at=tags.findIndex(t=>t.Code===1001);Check(at>=0,'Fixture XData boundary');tags.splice(at,0,new DxfTag(code,value));}}
export function CheckViewUcsModel(doc){const named=doc.UCSs.get_Item('NamedFrame'),base=doc.UCSs.get_Item('BaseFrame');Equal(UcsFlags.Referenced,named.Flags,'UCS flags lost');Equal(new Vector3(10.125,-20.25,30.5),named.Origin,'Named UCS origin');Equal(new Vector3(-3.5,4.25,8),base.Origin,'Base UCS origin');
  for(const name of ['NamedReview','UcsReview']){const view=doc.Views.get_Item(name),ucs=view.Ucs;Check(ucs!==null,'Associated UCS was discarded.');Equal(new Vector3(5.125,-6.25,7.5),ucs.Origin,'VIEW UCS origin');Equal(new Vector3(0,2,0),ucs.XAxis,'VIEW UCS X direction magnitude');Equal(new Vector3(-3,0,0),ucs.YAxis,'VIEW UCS Y direction magnitude');Equal(-9.875,ucs.Elevation,'VIEW UCS elevation');Equal(new Vector3(2,-3,7),view.ViewDirection,'Primary VIEW direction changed');const isNamed=name==='NamedReview';Check(ucs.NamedUcs===(isNamed?named:null)&&ucs.BaseUcs===(isNamed?null:base),'VIEW references lost their registered identities.');Equal(isNamed?0:5,ucs.OrthographicType,'VIEW orthographic type');Equal('independent',view.XData.get_Item('UCS_QA').XDataRecord.get_Item(0).Value,'VIEW XData');}
  Check(doc.Viewport.NamedUcs===named&&doc.Viewport.BaseUcs===null,'Active VPORT named reference');const port=doc.VPorts.get_Item('OrthoConfig');Check(port.BaseUcs===base&&port.NamedUcs===null,'VPORT base reference');Equal(4,port.UcsOrthographicType,'VPORT orthographic type');Check(named.HasReferences()&&base.HasReferences(),'Loaded hard-pointer references were not tracked.');Equal(2,uses(named),'Named reference uses');Equal(2,uses(base),'Base reference uses');const line=single(doc.Entities.Lines);Equal(new Vector3(1,2,3),line.StartPoint,'Following LINE start');Equal(new Vector3(4,5,6),line.EndPoint,'Following LINE end');
}
function identity(doc){return [doc.UCSs.get_Item('NamedFrame').Handle,doc.UCSs.get_Item('BaseFrame').Handle,doc.Views.get_Item('NamedReview').Handle,doc.Views.get_Item('UcsReview').Handle];}
export function ViewUcsIndependent(version,binary){let doc=ViewUcsLoad(ViewUcsRaw(version),binary);CheckViewUcsModel(doc);const identities=identity(doc);
  for(let cycle=0;cycle<3;cycle++){const transport=cycle%2===0?binary:!binary,output=new MemoryStream();try{Check(doc.Save(output,transport),'VIEW UCS save failed.');if(cycle===0)artifact(`view-ucs-${VersionName(version)}-${binary?'binary':'text'}.dxf`,output.ToArray());output.Position=0;const raw=DxfRawDocument.Load(output),named=Array.from(ViewUcsRecord(raw,'VIEW','NamedReview').Tags),base=Array.from(ViewUcsRecord(raw,'VIEW','UcsReview').Tags);Equal(identities[0],single(named.filter(t=>t.Code===345)).Value,'Named pointer handle changed');Check(!named.some(t=>t.Code===346),'Absent base pointer was invented.');Equal(identities[1],single(base.filter(t=>t.Code===346)).Value,'Base pointer handle changed');Check(!base.some(t=>t.Code===345),'Absent named pointer was invented.');output.Position=0;doc=DxfDocument.Load(output);Check(doc!==null,'VIEW UCS reload failed.');CheckViewUcsModel(doc);Equal(identities,identity(doc),'UCS/VIEW identity changed across transports.');}finally{output.Dispose();}}
}
export function ViewUcsReordered(version,binary){let raw=ViewUcsRaw(version);for(const name of ['NamedReview','UcsReview'])raw=EditViewUcsRecord(raw,'VIEW',name,tags=>{const fields=tags.filter(t=>codes.includes(t.Code)).sort((a,b)=>b.Code-a.Code);for(let i=tags.length-1;i>=0;i--)if(codes.includes(tags[i].Code))tags.splice(i,1);tags.splice(tags.findIndex(t=>t.Code===1001),0,...fields);});CheckViewUcsModel(ViewUcsLoad(raw,binary));}
export function ViewUcsMalformed(version,binary,defect){let raw=ViewUcsRaw(version);const type=defect.startsWith('ucs-')?'UCS':defect.startsWith('vport-')?'VPORT':'VIEW',name=type==='UCS'?'NamedFrame':type==='VPORT'?'OrthoConfig':['base-without-ortho','missing-base-target'].includes(defect)?'UcsReview':'NamedReview',line=single(Array.from(single(records(raw).filter(r=>r.Name==='LINE')).Tags).filter(t=>t.Code===5)).Value;
  raw=EditViewUcsRecord(raw,type,name,tags=>{const match=/^missing-(\d+)$/.exec(defect);if(match){for(let i=tags.length-1;i>=0;i--)if(tags[i].Code===Number(match[1]))tags.splice(i,1);return;}
    switch(defect){case 'missing-enable':for(let i=tags.length-1;i>=0;i--)if(tags[i].Code===72)tags.splice(i,1);break;case 'disabled':PutViewUcsTag(tags,72,0);break;case 'bad-enable':PutViewUcsTag(tags,72,2);break;case 'duplicate-enable':tags.splice(tags.findIndex(t=>t.Code===72),0,new DxfTag(72,1));break;case 'zero-axis':PutViewUcsTag(tags,121,0);break;case 'bad-ortho':PutViewUcsTag(tags,79,7);break;case 'base-without-ortho':case 'vport-base-without-ortho':PutViewUcsTag(tags,79,0);break;case 'missing-named-target':PutViewUcsTag(tags,345,'FFFF');break;case 'missing-base-target':case 'vport-missing-target':PutViewUcsTag(tags,346,'FFFF');break;case 'wrong-target-type':PutViewUcsTag(tags,345,line);break;case 'vport-wrong-target-type':PutViewUcsTag(tags,346,line);break;case 'duplicate-reference':tags.splice(tags.findIndex(t=>t.Code===345),0,new DxfTag(345,'FFFF'));break;case 'ucs-unsupported-type':PutViewUcsTag(tags,79,7);break;case 'ucs-duplicate-flags':tags.splice(tags.findIndex(t=>t.Code===70),0,new DxfTag(70,0));break;default:throw new ArgumentException(defect);}});
  const input=ViewUcsInput(raw,binary);try{if(GetTypedIOConfiguration()==='Debug')Throws(Error,()=>DxfDocument.Load(input));else Check(DxfDocument.Load(input)===null,'Invalid associated UCS input was admitted: '+defect);Check(input.CanRead,'Rejected UCS input closed caller stream.');}finally{input.Dispose();}
}
export function ViewUcsAuthoring(version,binary){const doc=new DxfDocument(version),target=doc.UCSs.Add(Object.assign(new UCS('Authored'),{Flags:UcsFlags.XrefResolved|UcsFlags.ExternallyDependent})),plain=doc.Views.Add(new View('Plain')),associated=doc.Views.Add(Object.assign(new View('Associated'),{Ucs:Object.assign(new ViewUcs(),{OrthographicType:2,Origin:new Vector3(1.125,-2.5,3.75),BaseUcs:target})})),output=new MemoryStream(),world=new MemoryStream();try{Check(doc.Save(output,binary),'Authored UCS did not save.');output.Position=0;const raw=DxfRawDocument.Load(output),tags=Array.from(ViewUcsRecord(raw,'VIEW',plain.Name).Tags);Equal(0,single(tags.filter(t=>t.Code===72)).Value,'Disabled UCS flag');Check(!tags.some(t=>t.Code!==72&&codes.includes(t.Code)),'Plain view received a UCS bundle.');output.Position=0;const loaded=DxfDocument.Load(output);Check(loaded.Views.get_Item(plain.Name).Ucs===null,'Absent bundle was invented.');Equal(target.Flags,loaded.UCSs.get_Item(target.Name).Flags,'UCS flag edit was lost');Equal(associated.Ucs.Origin,loaded.Views.get_Item(associated.Name).Ucs.Origin,'Authored associated origin changed');associated.Ucs.BaseUcs=null;associated.Ucs.OrthographicType=3;Check(doc.Save(world,binary),'WORLD base did not save.');world.Position=0;Check(!Array.from(ViewUcsRecord(DxfRawDocument.Load(world),'VIEW',associated.Name).Tags).some(t=>t.Code===346),'WORLD base was assigned a fabricated handle.');}finally{world.Dispose();output.Dispose();}}
export function ViewUcsLifecycle(){const doc=new DxfDocument(),target=doc.UCSs.Add(new UCS('Target')),view=doc.Views.Add(Object.assign(new View('First'),{Ucs:Object.assign(new ViewUcs(),{NamedUcs:target,BaseUcs:target,OrthographicType:1})})),port=doc.VPorts.AddRecord(Object.assign(new VPort('Tiles'),{NamedUcs:target})),tile=doc.VPorts.AddRecord(port.Clone());Equal(4,uses(target),'Distinct reference slots were collapsed');Equal(3,Array.from(target.GetReferences()).length,'Physical tiles were collapsed by configuration name');Check(!doc.UCSs.Remove(target),'Referenced UCS was removed.');target.Name='RenamedTarget';view.Name='RenamedView';view.Ucs.NamedUcs=null;Equal(3,uses(target),'Rename broke outbound reference removal');const detached=view.Ucs;view.Ucs=null;detached.NamedUcs=target;Equal(2,uses(target),'Detached bundle retained a reference subscription');Check(doc.VPorts.Remove(port),'First tile did not remove.');Equal(1,uses(target),'Tile removal erased sibling reference');Check(doc.VPorts.Remove(tile)&&doc.UCSs.Remove(target),'Last reference did not release UCS.');const one=Object.assign(new View('One'),{Ucs:new ViewUcs()}),two=new View('Two');Throws(ArgumentException,()=>{two.Ucs=one.Ucs;});Check(two.Ucs===null&&one.Ucs!==null,'Rejected bundle attachment changed ownership.');}
export function ViewUcsCloneIsolation(){const source=new DxfDocument(),original=source.UCSs.Add(new UCS('Source')),view=source.Views.Add(Object.assign(new View('View'),{Ucs:Object.assign(new ViewUcs(),{NamedUcs:original})})),copy=view.Clone('Copy');Check(copy.Ucs!==view.Ucs,'Clone shared mutable UCS values.');Check(copy.Ucs.NamedUcs===original,'Detached clone lost its reference identity.');copy.Ucs.Origin=Vector3.UnitX;Equal(Vector3.Zero,view.Ucs.Origin,'Clone values mutated source');const destination=new DxfDocument();Throws(ArgumentException,()=>destination.Views.Add(copy));Check(copy.Owner===null&&copy.Handle===null&&destination.Views.Count===0,'Rejected cross-document add partially registered clone.');const mapped=destination.UCSs.Add(original.Clone());copy.Ucs.NamedUcs=mapped;destination.Views.Add(copy);const foreign=destination.UCSs.Add(new UCS('Foreign')),handle=original.Handle;Throws(ArgumentException,()=>{view.Ucs.NamedUcs=foreign;});Check(view.Ucs.NamedUcs===original&&original.Handle===handle&&original.Owner===source.UCSs,'Rejected foreign assignment changed source identity.');Check(source.Views.Remove(view)&&!original.HasReferences(),'View removal left UCS references.');}
export function ViewUcsInvalidValues(){const value=new ViewUcs();for(const invalid of [NaN,Infinity,-Infinity]){Throws(ArgumentOutOfRangeException,()=>{value.Elevation=invalid;});Throws(ArgumentOutOfRangeException,()=>{value.Origin=new Vector3(invalid,0,0);});}Throws(ArgumentException,()=>{value.XAxis=Vector3.Zero;});Throws(ArgumentException,()=>{value.YAxis=Vector3.Zero;});Throws(ArgumentOutOfRangeException,()=>{value.OrthographicType=7;});const doc=new DxfDocument(),target=doc.UCSs.Add(new UCS('Target')),view=doc.Views.Add(Object.assign(new View('View'),{Ucs:new ViewUcs()})),output=new MemoryStream();view.Ucs.BaseUcs=target;try{if(GetTypedIOConfiguration()==='Debug')Throws(InvalidOperationException,()=>doc.Save(output));else Check(!doc.Save(output),'Invalid base relationship saved successfully.');Equal(0,output.Length,'Invalid UCS relationship wrote partial output');}finally{output.Dispose();}}
export function ViewUcsRename(isUcs,scenario){const source=new DxfDocument(),destination=new DxfDocument(),sourceTarget=source.UCSs.Add(new UCS('Referenced')),destinationTarget=destination.UCSs.Add(new UCS('Referenced')),record=isUcs?new UCS('Before'):Object.assign(new View('Before'),{Ucs:Object.assign(new ViewUcs(),{NamedUcs:sourceTarget})});
  const table=doc=>isUcs?doc.UCSs:doc.Views,add=doc=>table(doc).Add(record),remove=doc=>Check(table(doc).Remove(record),'Rename observer could not detach record.'),get=(doc,name)=>table(doc).get_Item(name),collision=doc=>table(doc).Add(isUcs?new UCS('After'):new View('After'));if(!scenario.startsWith('attach'))add(source);let dependent=null;if(isUcs&&['throw','collision'].includes(scenario))dependent=source.Views.Add(Object.assign(new View('Dependent'),{Ucs:Object.assign(new ViewUcs(),{NamedUcs:record})}));if(scenario==='move-collision')collision(destination);
  record.NameChanged.Add(()=>{if(scenario.startsWith('attach'))add(source);if(['detach','move','move-collision'].includes(scenario))remove(source);if(['move','move-collision'].includes(scenario)){if(!isUcs)record.Ucs.NamedUcs=destinationTarget;add(destination);}if(scenario==='collision')collision(source);if(['throw','attach-throw'].includes(scenario))throw new InvalidOperationException('Rejected by user observer.');});
  if(['throw','attach-throw'].includes(scenario))Throws(InvalidOperationException,()=>{record.Name='After';});else if(['collision','move-collision'].includes(scenario))Throws(ArgumentException,()=>{record.Name='After';});else record.Name='After';const failed=['throw','attach-throw','collision','move-collision'].includes(scenario);Equal(failed?'Before':'After',record.Name,'Rename transaction changed the actual name incorrectly');const final=scenario.startsWith('move')?destination:source;
  if(scenario==='detach')Check(record.Owner===null&&get(source,'Before')===null&&get(source,'After')===null,'Detached rename left a collection index.');else{Check(get(final,record.Name)===record,'Rename committed to the wrong owner or index.');if(scenario.startsWith('move'))Check(get(source,'Before')===null&&get(source,'After')===null,'Moving during rename retained the source index.');}
  if(dependent!==null){Equal(1,uses(record),'Rejected rename changed incoming uses');dependent.Ucs.NamedUcs=null;Check(!record.HasReferences(),'Incoming reference could not be removed after rejected rename.');}if(!isUcs){record.Ucs.NamedUcs=null;Check(!sourceTarget.HasReferences()&&!destinationTarget.HasReferences(),'Rename or owner transfer corrupted outbound reference uses.');}
}
export function ViewUcsForeignRegistry(isUcs){const source=new DxfDocument(),destination=new DxfDocument(),registry=source.ApplicationRegistries.Add(new ApplicationRegistry('FOREIGN_UCS_DATA')),handle=registry.Handle,record=isUcs?new UCS('ForeignData'):new View('ForeignData'),data=new XData(registry);data.XDataRecord.Add(new XDataRecord(XDataCode.String,'retained'));record.XData.Add(data);const dest=isUcs?destination.UCSs:destination.Views;Throws(ArgumentException,()=>dest.Add(record));Check(record.Owner===null&&record.Handle===null,'Foreign registry rejection partially registered the table record.');Check(!destination.ApplicationRegistries.Contains(registry.Name),'Foreign registry rejection changed the destination registry table.');Check(registry.Owner===source.ApplicationRegistries&&registry.Handle===handle&&source.GetObjectByHandle(handle)===registry,'Foreign registry rejection changed source identity.');const clone=record.Clone();dest.Add(clone);Check(clone.XData.get_Item(registry.Name).ApplicationRegistry!==registry,'Clone reused the foreign registry.');Check(registry.Owner===source.ApplicationRegistries&&registry.Handle===handle,'Adding a clone mutated the source registry.');Check(!dest.Remove(record),'A detached same-name record removed an owned record.');let referenced;
  if(isUcs){referenced=source.UCSs.Add(record);source.Views.Add(Object.assign(new View('Dependent'),{Ucs:Object.assign(new ViewUcs(),{NamedUcs:referenced})}));}else{referenced=source.UCSs.Add(new UCS('ReferencedFrame'));record.Ucs=Object.assign(new ViewUcs(),{NamedUcs:referenced});source.Views.Add(record);}const recordHandle=record.Handle;Check(recordHandle!==null,'The source table record was not registered.');Check(!dest.Remove(record),'A foreign same-name record reached removal.');Check(source.GetObjectByHandle(recordHandle)===record&&destination.GetObjectByHandle(clone.Handle)===clone,'Rejected removal changed either document\'s identity map.');Equal(1,uses(referenced),'Rejected removal changed foreign UCS reference uses');
}
