<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Transpose.Compiler.Library" Version="26.9.5288" />
    <PackageReference Include="Transpose.BCL" Version="26.9.4872" ExcludeAssets="all" PrivateAssets="all" />
  </ItemGroup>
</Project>
