using netDxf;using netDxf.Entities;using netDxf.IO;using System.Text.Json;
string root=args[0],output=args[1];Directory.CreateDirectory(output);var rows=new List<object>();int failed=0;
void Check(bool value,string why){if(!value)throw new Exception(why);}
DxfDocument Load(byte[] bytes){return DxfDocument.Load(new MemoryStream(bytes))??throw new Exception("Load refused");}
byte[] Save(DxfDocument d,bool binary){using var s=new MemoryStream();Check(d.Save(s,binary),"Save refused");return s.ToArray();}
void Refuse(DxfDocument d,bool binary){byte[] bytes={3,5,7};using var s=new MemoryStream();s.Write(bytes);s.Position=1;bool ok;try{ok=d.Save(s,binary);}catch(Exception){ok=false;}Check(!ok&&s.Position==1&&s.ToArray().SequenceEqual(bytes),"Pinned reactor metadata should refuse before output");}
foreach(string kind in new[]{"native","producer"})foreach(int year in new[]{2000,2004,2007,2010,2013,2018})foreach(bool binary in new[]{false,true})
{
 string label=$"{kind}-{year}-{binary}";
 void Run(string scenario,Action action){try{action();rows.Add(new{name=label+"/"+scenario,passed=true,error=""});Console.WriteLine("PASS "+label+"/"+scenario);}catch(Exception e){failed++;rows.Add(new{name=label+"/"+scenario,passed=false,error=e.ToString()});Console.WriteLine("FAIL "+label+"/"+scenario+": "+e.Message);}}
 var raw=DxfRawDocument.Load(new MemoryStream(File.ReadAllBytes(Path.Combine(root,$"{kind}-R{year}-{(binary?"binary":"ascii")}.dxf"))));string target=kind=="native"?"8E":"3A0";
 var record=raw.Sections.SelectMany(s=>s.Records).Single(r=>r.Tags.Any(t=>t.Code==5&&Equals(t.Value,target)));var tags=record.Tags.ToList();tags[0]=new DxfTag(0,"FUTURE_BOUNDARY_CURVE");raw=raw.WithRecord(record,tags);using var buffer=new MemoryStream();raw.Save(buffer,binary);byte[] input=buffer.ToArray();
 Run("retained-source",()=>{var d=Load(input);var source=(DxfOpaqueEntity)d.GetObjectByHandle(target);var uses=d.Entities.Hatches.SelectMany(h=>h.BoundaryPaths.SelectMany(p=>p.Entities.Select(e=>(h,e)))).Where(pair=>ReferenceEquals(pair.e,source)).ToArray();Check(uses.Length>0&&source.Reactors.Count==uses.Length,"Actual source/reactor identity");Check(uses.All(pair=>ReferenceEquals(pair.h.Owner,source.Owner)&&source.PersistentReactors.Contains(pair.h)),"Actual persistent backlink");Check(!d.Entities.Remove(source),"Live HATCH source removal allowed");foreach(bool written in new[]{false,true}){var bytes=Save(d,written);var other=Load(bytes);Check(other.GetObjectByHandle(target) is DxfOpaqueEntity,"Reload dropped opaque source");File.WriteAllBytes(Path.Combine(output,label+"-"+written+".dxf"),bytes);}});
 Run("unlink-retire",()=>{var d=Load(input);var source=(DxfOpaqueEntity)d.GetObjectByHandle(target);var hatches=d.Entities.Hatches.Where(h=>h.BoundaryPaths.Any(p=>p.Entities.Any(e=>ReferenceEquals(e,source)))).ToArray();foreach(var h in hatches)h.UnLinkBoundary();Check(source.Owner!=null&&source.Reactors.Count==0,"Unlink should retain source and clear managed associations");Refuse(d,binary);Check(d.Entities.Remove(source),"Unlinked opaque source cannot retire");Save(d,!binary);});
 Run("path-removal",()=>{var d=Load(input);var source=(DxfOpaqueEntity)d.GetObjectByHandle(target);foreach(var h in d.Entities.Hatches.ToArray()){foreach(var path in h.BoundaryPaths.Where(p=>p.Entities.Any(e=>ReferenceEquals(e,source))).ToArray())h.BoundaryPaths.Remove(path);if(h.BoundaryPaths.Count==0)Check(d.Entities.Remove(h),"Empty hatch cleanup");}Check(source.Owner==null,"Final source path should retire unreferenced opaque source");Save(d,!binary);});
}
File.WriteAllText(Path.Combine(output,"results.json"),JsonSerializer.Serialize(rows,new JsonSerializerOptions{WriteIndented=true}));Console.WriteLine($"Opaque HATCH: {rows.Count-failed}/{rows.Count} passed");Environment.ExitCode=failed==0?0:1;
